package com.divisosofttech.spot_fix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketVoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketVoteAllPropertiesEquals(TicketVote expected, TicketVote actual) {
        assertTicketVoteAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketVoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketVoteAllUpdatablePropertiesEquals(TicketVote expected, TicketVote actual) {
        assertTicketVoteUpdatableFieldsEquals(expected, actual);
        assertTicketVoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketVoteAutoGeneratedPropertiesEquals(TicketVote expected, TicketVote actual) {
        assertThat(actual)
            .as("Verify TicketVote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketVoteUpdatableFieldsEquals(TicketVote expected, TicketVote actual) {
        assertThat(actual)
            .as("Verify TicketVote relevant properties")
            .satisfies(a -> assertThat(a.getVoteType()).as("check voteType").isEqualTo(expected.getVoteType()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketVoteUpdatableRelationshipsEquals(TicketVote expected, TicketVote actual) {
        assertThat(actual)
            .as("Verify TicketVote relationships")
            .satisfies(a -> assertThat(a.getTicket()).as("check ticket").isEqualTo(expected.getTicket()));
    }
}
