# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: spot_fix
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NDdkNGZkZWIyNzNmZTBlNWYyYzhmOWYxODY3YzQ2MGM4NjU4NzA0ZTY4NTQ4ODFiZjY2MmVhNjdhZTMzZjNlYmQxNzZkZWE5OTYwMmRhNGE2YzEzYWMxMjczYzk5MDljYWJkYzhlZGE0NmIyOWY2MzEzMGFlNjY4NDdmNTJkZmI=
