/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketDTO } from './TicketDTO';
import {
    TicketDTOFromJSON,
    TicketDTOFromJSONTyped,
    TicketDTOToJSON,
    TicketDTOToJSONTyped,
} from './TicketDTO';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface AttachmentDTO
 */
export interface AttachmentDTO {
    /**
     * 
     * @type {number}
     * @memberof AttachmentDTO
     */
    id?: number;
    /**
     * 
     * @type {AttachmentDTOAttachmentTypeEnum}
     * @memberof AttachmentDTO
     */
    attachmentType: AttachmentDTOAttachmentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    fileType?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentDTO
     */
    fileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    checksum?: string;
    /**
     * 
     * @type {Date}
     * @memberof AttachmentDTO
     */
    uploadedDate: Date;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    transcript?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentDTO
     */
    durationSeconds?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentDTO
     */
    language?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AttachmentDTO
     */
    deleted: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AttachmentDTO
     */
    updatedDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AttachmentDTO
     */
    deletedDate?: Date;
    /**
     * 
     * @type {TicketDTO}
     * @memberof AttachmentDTO
     */
    ticket: TicketDTO;
    /**
     * 
     * @type {UserDTO}
     * @memberof AttachmentDTO
     */
    uploadedBy: UserDTO;
}


/**
 * @export
 */
export const AttachmentDTOAttachmentTypeEnum = {
    Image: 'IMAGE',
    Video: 'VIDEO',
    Audio: 'AUDIO',
    Pdf: 'PDF',
    Document: 'DOCUMENT',
    ContractorUpdate: 'CONTRACTOR_UPDATE',
    CompletionReport: 'COMPLETION_REPORT'
} as const;
export type AttachmentDTOAttachmentTypeEnum = typeof AttachmentDTOAttachmentTypeEnum[keyof typeof AttachmentDTOAttachmentTypeEnum];


/**
 * Check if a given object implements the AttachmentDTO interface.
 */
export function instanceOfAttachmentDTO(value: object): value is AttachmentDTO {
    if (!('attachmentType' in value) || value['attachmentType'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('uploadedDate' in value) || value['uploadedDate'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    if (!('uploadedBy' in value) || value['uploadedBy'] === undefined) return false;
    return true;
}

export function AttachmentDTOFromJSON(json: any): AttachmentDTO {
    return AttachmentDTOFromJSONTyped(json, false);
}

export function AttachmentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'attachmentType': json['attachmentType'],
        'fileName': json['fileName'],
        'filePath': json['filePath'],
        'fileType': json['fileType'] == null ? undefined : json['fileType'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'uploadedDate': (new Date(json['uploadedDate'])),
        'transcript': json['transcript'] == null ? undefined : json['transcript'],
        'durationSeconds': json['durationSeconds'] == null ? undefined : json['durationSeconds'],
        'language': json['language'] == null ? undefined : json['language'],
        'deleted': json['deleted'],
        'updatedDate': json['updatedDate'] == null ? undefined : (new Date(json['updatedDate'])),
        'deletedDate': json['deletedDate'] == null ? undefined : (new Date(json['deletedDate'])),
        'ticket': TicketDTOFromJSON(json['ticket']),
        'uploadedBy': UserDTOFromJSON(json['uploadedBy']),
    };
}

export function AttachmentDTOToJSON(json: any): AttachmentDTO {
    return AttachmentDTOToJSONTyped(json, false);
}

export function AttachmentDTOToJSONTyped(value?: AttachmentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'attachmentType': value['attachmentType'],
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'fileType': value['fileType'],
        'fileSize': value['fileSize'],
        'checksum': value['checksum'],
        'uploadedDate': value['uploadedDate'].toISOString(),
        'transcript': value['transcript'],
        'durationSeconds': value['durationSeconds'],
        'language': value['language'],
        'deleted': value['deleted'],
        'updatedDate': value['updatedDate'] == null ? value['updatedDate'] : value['updatedDate'].toISOString(),
        'deletedDate': value['deletedDate'] == null ? value['deletedDate'] : value['deletedDate'].toISOString(),
        'ticket': TicketDTOToJSON(value['ticket']),
        'uploadedBy': UserDTOToJSON(value['uploadedBy']),
    };
}

