/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JWTToken
 */
export interface JWTToken {
    /**
     * 
     * @type {string}
     * @memberof JWTToken
     */
    idToken?: string;
}

/**
 * Check if a given object implements the JWTToken interface.
 */
export function instanceOfJWTToken(value: object): value is JWTToken {
    return true;
}

export function JWTTokenFromJSON(json: any): JWTToken {
    return JWTTokenFromJSONTyped(json, false);
}

export function JWTTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): JWTToken {
    if (json == null) {
        return json;
    }
    return {
        
        'idToken': json['id_token'] == null ? undefined : json['id_token'],
    };
}

export function JWTTokenToJSON(json: any): JWTToken {
    return JWTTokenToJSONTyped(json, false);
}

export function JWTTokenToJSONTyped(value?: JWTToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id_token': value['idToken'],
    };
}

