/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginVM
 */
export interface LoginVM {
    /**
     * 
     * @type {string}
     * @memberof LoginVM
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LoginVM
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof LoginVM
     */
    rememberMe?: boolean;
}

/**
 * Check if a given object implements the LoginVM interface.
 */
export function instanceOfLoginVM(value: object): value is LoginVM {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginVMFromJSON(json: any): LoginVM {
    return LoginVMFromJSONTyped(json, false);
}

export function LoginVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginVM {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'rememberMe': json['rememberMe'] == null ? undefined : json['rememberMe'],
    };
}

export function LoginVMToJSON(json: any): LoginVM {
    return LoginVMToJSONTyped(json, false);
}

export function LoginVMToJSONTyped(value?: LoginVM | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'rememberMe': value['rememberMe'],
    };
}

