/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManagedUserVM
 */
export interface ManagedUserVM {
    /**
     * 
     * @type {number}
     * @memberof ManagedUserVM
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ManagedUserVM
     */
    activated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    langKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof ManagedUserVM
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    lastModifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof ManagedUserVM
     */
    lastModifiedDate?: Date;
    /**
     * 
     * @type {Set<string>}
     * @memberof ManagedUserVM
     */
    authorities?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof ManagedUserVM
     */
    password?: string;
}

/**
 * Check if a given object implements the ManagedUserVM interface.
 */
export function instanceOfManagedUserVM(value: object): value is ManagedUserVM {
    if (!('login' in value) || value['login'] === undefined) return false;
    return true;
}

export function ManagedUserVMFromJSON(json: any): ManagedUserVM {
    return ManagedUserVMFromJSONTyped(json, false);
}

export function ManagedUserVMFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedUserVM {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'login': json['login'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'activated': json['activated'] == null ? undefined : json['activated'],
        'langKey': json['langKey'] == null ? undefined : json['langKey'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'authorities': json['authorities'] == null ? undefined : new Set(json['authorities']),
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function ManagedUserVMToJSON(json: any): ManagedUserVM {
    return ManagedUserVMToJSONTyped(json, false);
}

export function ManagedUserVMToJSONTyped(value?: ManagedUserVM | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'login': value['login'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'imageUrl': value['imageUrl'],
        'activated': value['activated'],
        'langKey': value['langKey'],
        'createdBy': value['createdBy'],
        'createdDate': value['createdDate'] == null ? value['createdDate'] : value['createdDate'].toISOString(),
        'lastModifiedBy': value['lastModifiedBy'],
        'lastModifiedDate': value['lastModifiedDate'] == null ? value['lastModifiedDate'] : value['lastModifiedDate'].toISOString(),
        'authorities': value['authorities'] == null ? undefined : Array.from(value['authorities'] as Set<any>),
        'password': value['password'],
    };
}

