/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordChangeDTO
 */
export interface PasswordChangeDTO {
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeDTO
     */
    currentPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeDTO
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the PasswordChangeDTO interface.
 */
export function instanceOfPasswordChangeDTO(value: object): value is PasswordChangeDTO {
    return true;
}

export function PasswordChangeDTOFromJSON(json: any): PasswordChangeDTO {
    return PasswordChangeDTOFromJSONTyped(json, false);
}

export function PasswordChangeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordChangeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['currentPassword'] == null ? undefined : json['currentPassword'],
        'newPassword': json['newPassword'] == null ? undefined : json['newPassword'],
    };
}

export function PasswordChangeDTOToJSON(json: any): PasswordChangeDTO {
    return PasswordChangeDTOToJSONTyped(json, false);
}

export function PasswordChangeDTOToJSONTyped(value?: PasswordChangeDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPassword': value['currentPassword'],
        'newPassword': value['newPassword'],
    };
}

