/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketDTO } from './TicketDTO';
import {
    TicketDTOFromJSON,
    TicketDTOFromJSONTyped,
    TicketDTOToJSON,
    TicketDTOToJSONTyped,
} from './TicketDTO';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface TicketVoteDTO
 */
export interface TicketVoteDTO {
    /**
     * 
     * @type {number}
     * @memberof TicketVoteDTO
     */
    id?: number;
    /**
     * 
     * @type {TicketVoteDTOVoteTypeEnum}
     * @memberof TicketVoteDTO
     */
    voteType: TicketVoteDTOVoteTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof TicketVoteDTO
     */
    createdDate: Date;
    /**
     * 
     * @type {TicketDTO}
     * @memberof TicketVoteDTO
     */
    ticket: TicketDTO;
    /**
     * 
     * @type {UserDTO}
     * @memberof TicketVoteDTO
     */
    user: UserDTO;
}


/**
 * @export
 */
export const TicketVoteDTOVoteTypeEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type TicketVoteDTOVoteTypeEnum = typeof TicketVoteDTOVoteTypeEnum[keyof typeof TicketVoteDTOVoteTypeEnum];


/**
 * Check if a given object implements the TicketVoteDTO interface.
 */
export function instanceOfTicketVoteDTO(value: object): value is TicketVoteDTO {
    if (!('voteType' in value) || value['voteType'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function TicketVoteDTOFromJSON(json: any): TicketVoteDTO {
    return TicketVoteDTOFromJSONTyped(json, false);
}

export function TicketVoteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketVoteDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'voteType': json['voteType'],
        'createdDate': (new Date(json['createdDate'])),
        'ticket': TicketDTOFromJSON(json['ticket']),
        'user': UserDTOFromJSON(json['user']),
    };
}

export function TicketVoteDTOToJSON(json: any): TicketVoteDTO {
    return TicketVoteDTOToJSONTyped(json, false);
}

export function TicketVoteDTOToJSONTyped(value?: TicketVoteDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'voteType': value['voteType'],
        'createdDate': value['createdDate'].toISOString(),
        'ticket': TicketDTOToJSON(value['ticket']),
        'user': UserDTOToJSON(value['user']),
    };
}

