/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepartmentDTO } from './DepartmentDTO';
import {
    DepartmentDTOFromJSON,
    DepartmentDTOFromJSONTyped,
    DepartmentDTOToJSON,
    DepartmentDTOToJSONTyped,
} from './DepartmentDTO';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';
import type { WardDTO } from './WardDTO';
import {
    WardDTOFromJSON,
    WardDTOFromJSONTyped,
    WardDTOToJSON,
    WardDTOToJSONTyped,
} from './WardDTO';
import type { LocationDTO } from './LocationDTO';
import {
    LocationDTOFromJSON,
    LocationDTOFromJSONTyped,
    LocationDTOToJSON,
    LocationDTOToJSONTyped,
} from './LocationDTO';

/**
 * 
 * @export
 * @interface TicketDTO
 */
export interface TicketDTO {
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    description?: string;
    /**
     * 
     * @type {TicketDTOStatusEnum}
     * @memberof TicketDTO
     */
    status: TicketDTOStatusEnum;
    /**
     * 
     * @type {TicketDTOPriorityEnum}
     * @memberof TicketDTO
     */
    priority: TicketDTOPriorityEnum;
    /**
     * 
     * @type {TicketDTOVisibilityEnum}
     * @memberof TicketDTO
     */
    visibility: TicketDTOVisibilityEnum;
    /**
     * 
     * @type {TicketDTOCategoryEnum}
     * @memberof TicketDTO
     */
    category: TicketDTOCategoryEnum;
    /**
     * 
     * @type {Date}
     * @memberof TicketDTO
     */
    createdDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketDTO
     */
    updatedDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketDTO
     */
    expectedResolutionDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TicketDTO
     */
    resolvedDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    aiSummary?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TicketDTO
     */
    aiDuplicate?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    duplicateScore?: number;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    aiConfidence?: number;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    duplicateTicketId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TicketDTO
     */
    deleted: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TicketDTO
     */
    deletedDate?: Date;
    /**
     * 
     * @type {UserDTO}
     * @memberof TicketDTO
     */
    reportedBy: UserDTO;
    /**
     * 
     * @type {LocationDTO}
     * @memberof TicketDTO
     */
    location: LocationDTO;
    /**
     * 
     * @type {WardDTO}
     * @memberof TicketDTO
     */
    ward: WardDTO;
    /**
     * 
     * @type {DepartmentDTO}
     * @memberof TicketDTO
     */
    assignedDepartment?: DepartmentDTO;
}


/**
 * @export
 */
export const TicketDTOStatusEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type TicketDTOStatusEnum = typeof TicketDTOStatusEnum[keyof typeof TicketDTOStatusEnum];

/**
 * @export
 */
export const TicketDTOPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type TicketDTOPriorityEnum = typeof TicketDTOPriorityEnum[keyof typeof TicketDTOPriorityEnum];

/**
 * @export
 */
export const TicketDTOVisibilityEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type TicketDTOVisibilityEnum = typeof TicketDTOVisibilityEnum[keyof typeof TicketDTOVisibilityEnum];

/**
 * @export
 */
export const TicketDTOCategoryEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type TicketDTOCategoryEnum = typeof TicketDTOCategoryEnum[keyof typeof TicketDTOCategoryEnum];


/**
 * Check if a given object implements the TicketDTO interface.
 */
export function instanceOfTicketDTO(value: object): value is TicketDTO {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('reportedBy' in value) || value['reportedBy'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('ward' in value) || value['ward'] === undefined) return false;
    return true;
}

export function TicketDTOFromJSON(json: any): TicketDTO {
    return TicketDTOFromJSONTyped(json, false);
}

export function TicketDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'],
        'priority': json['priority'],
        'visibility': json['visibility'],
        'category': json['category'],
        'createdDate': (new Date(json['createdDate'])),
        'updatedDate': json['updatedDate'] == null ? undefined : (new Date(json['updatedDate'])),
        'expectedResolutionDate': json['expectedResolutionDate'] == null ? undefined : (new Date(json['expectedResolutionDate'])),
        'resolvedDate': json['resolvedDate'] == null ? undefined : (new Date(json['resolvedDate'])),
        'aiSummary': json['aiSummary'] == null ? undefined : json['aiSummary'],
        'aiDuplicate': json['aiDuplicate'] == null ? undefined : json['aiDuplicate'],
        'duplicateScore': json['duplicateScore'] == null ? undefined : json['duplicateScore'],
        'aiConfidence': json['aiConfidence'] == null ? undefined : json['aiConfidence'],
        'duplicateTicketId': json['duplicateTicketId'] == null ? undefined : json['duplicateTicketId'],
        'deleted': json['deleted'],
        'deletedDate': json['deletedDate'] == null ? undefined : (new Date(json['deletedDate'])),
        'reportedBy': UserDTOFromJSON(json['reportedBy']),
        'location': LocationDTOFromJSON(json['location']),
        'ward': WardDTOFromJSON(json['ward']),
        'assignedDepartment': json['assignedDepartment'] == null ? undefined : DepartmentDTOFromJSON(json['assignedDepartment']),
    };
}

export function TicketDTOToJSON(json: any): TicketDTO {
    return TicketDTOToJSONTyped(json, false);
}

export function TicketDTOToJSONTyped(value?: TicketDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'status': value['status'],
        'priority': value['priority'],
        'visibility': value['visibility'],
        'category': value['category'],
        'createdDate': value['createdDate'].toISOString(),
        'updatedDate': value['updatedDate'] == null ? value['updatedDate'] : value['updatedDate'].toISOString(),
        'expectedResolutionDate': value['expectedResolutionDate'] == null ? value['expectedResolutionDate'] : value['expectedResolutionDate'].toISOString(),
        'resolvedDate': value['resolvedDate'] == null ? value['resolvedDate'] : value['resolvedDate'].toISOString(),
        'aiSummary': value['aiSummary'],
        'aiDuplicate': value['aiDuplicate'],
        'duplicateScore': value['duplicateScore'],
        'aiConfidence': value['aiConfidence'],
        'duplicateTicketId': value['duplicateTicketId'],
        'deleted': value['deleted'],
        'deletedDate': value['deletedDate'] == null ? value['deletedDate'] : value['deletedDate'].toISOString(),
        'reportedBy': UserDTOToJSON(value['reportedBy']),
        'location': LocationDTOToJSON(value['location']),
        'ward': WardDTOToJSON(value['ward']),
        'assignedDepartment': DepartmentDTOToJSON(value['assignedDepartment']),
    };
}

