/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * 
 * @export
 * @interface UserProfileDTO
 */
export interface UserProfileDTO {
    /**
     * 
     * @type {number}
     * @memberof UserProfileDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileDTO
     */
    bio?: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof UserProfileDTO
     */
    user: UserDTO;
}

/**
 * Check if a given object implements the UserProfileDTO interface.
 */
export function instanceOfUserProfileDTO(value: object): value is UserProfileDTO {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function UserProfileDTOFromJSON(json: any): UserProfileDTO {
    return UserProfileDTOFromJSONTyped(json, false);
}

export function UserProfileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'address': json['address'] == null ? undefined : json['address'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'user': UserDTOFromJSON(json['user']),
    };
}

export function UserProfileDTOToJSON(json: any): UserProfileDTO {
    return UserProfileDTOToJSONTyped(json, false);
}

export function UserProfileDTOToJSONTyped(value?: UserProfileDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'phone': value['phone'],
        'address': value['address'],
        'avatarUrl': value['avatarUrl'],
        'bio': value['bio'],
        'user': UserDTOToJSON(value['user']),
    };
}

