/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminUserDTO,
  KeyAndPasswordVM,
  ManagedUserVM,
  PasswordChangeDTO,
} from '../models/index';
import {
    AdminUserDTOFromJSON,
    AdminUserDTOToJSON,
    KeyAndPasswordVMFromJSON,
    KeyAndPasswordVMToJSON,
    ManagedUserVMFromJSON,
    ManagedUserVMToJSON,
    PasswordChangeDTOFromJSON,
    PasswordChangeDTOToJSON,
} from '../models/index';

export interface ActivateAccountRequest {
    key: string;
}

export interface ChangePasswordRequest {
    passwordChangeDTO: PasswordChangeDTO;
}

export interface FinishPasswordResetRequest {
    keyAndPasswordVM: KeyAndPasswordVM;
}

export interface RegisterAccountRequest {
    managedUserVM: ManagedUserVM;
}

export interface RequestPasswordResetRequest {
    body: string;
}

export interface SaveAccountRequest {
    adminUserDTO: AdminUserDTO;
}

/**
 * 
 */
export class AccountResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for activateAccount without sending the request
     */
    async activateAccountRequestOpts(requestParameters: ActivateAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling activateAccount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['key'] != null) {
            queryParameters['key'] = requestParameters['key'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/activate`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async activateAccountRaw(requestParameters: ActivateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.activateAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async activateAccount(requestParameters: ActivateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.activateAccountRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for changePassword without sending the request
     */
    async changePasswordRequestOpts(requestParameters: ChangePasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passwordChangeDTO'] == null) {
            throw new runtime.RequiredError(
                'passwordChangeDTO',
                'Required parameter "passwordChangeDTO" was null or undefined when calling changePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/account/change-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordChangeDTOToJSON(requestParameters['passwordChangeDTO']),
        };
    }

    /**
     */
    async changePasswordRaw(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.changePasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async changePassword(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.changePasswordRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for finishPasswordReset without sending the request
     */
    async finishPasswordResetRequestOpts(requestParameters: FinishPasswordResetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['keyAndPasswordVM'] == null) {
            throw new runtime.RequiredError(
                'keyAndPasswordVM',
                'Required parameter "keyAndPasswordVM" was null or undefined when calling finishPasswordReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/account/reset-password/finish`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KeyAndPasswordVMToJSON(requestParameters['keyAndPasswordVM']),
        };
    }

    /**
     */
    async finishPasswordResetRaw(requestParameters: FinishPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.finishPasswordResetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async finishPasswordReset(requestParameters: FinishPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.finishPasswordResetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAccount without sending the request
     */
    async getAccountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/account`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAccountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminUserDTO>> {
        const requestOptions = await this.getAccountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminUserDTOFromJSON(jsonValue));
    }

    /**
     */
    async getAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminUserDTO> {
        const response = await this.getAccountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerAccount without sending the request
     */
    async registerAccountRequestOpts(requestParameters: RegisterAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['managedUserVM'] == null) {
            throw new runtime.RequiredError(
                'managedUserVM',
                'Required parameter "managedUserVM" was null or undefined when calling registerAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ManagedUserVMToJSON(requestParameters['managedUserVM']),
        };
    }

    /**
     */
    async registerAccountRaw(requestParameters: RegisterAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.registerAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async registerAccount(requestParameters: RegisterAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.registerAccountRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for requestPasswordReset without sending the request
     */
    async requestPasswordResetRequestOpts(requestParameters: RequestPasswordResetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling requestPasswordReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/account/reset-password/init`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async requestPasswordResetRaw(requestParameters: RequestPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.requestPasswordResetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async requestPasswordReset(requestParameters: RequestPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestPasswordResetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for saveAccount without sending the request
     */
    async saveAccountRequestOpts(requestParameters: SaveAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['adminUserDTO'] == null) {
            throw new runtime.RequiredError(
                'adminUserDTO',
                'Required parameter "adminUserDTO" was null or undefined when calling saveAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/account`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminUserDTOToJSON(requestParameters['adminUserDTO']),
        };
    }

    /**
     */
    async saveAccountRaw(requestParameters: SaveAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.saveAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async saveAccount(requestParameters: SaveAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.saveAccountRaw(requestParameters, initOverrides);
    }

}
