/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Authority,
} from '../models/index';
import {
    AuthorityFromJSON,
    AuthorityToJSON,
} from '../models/index';

export interface CreateAuthorityRequest {
    authority: Authority;
}

export interface DeleteAuthorityRequest {
    id: string;
}

export interface GetAuthorityRequest {
    id: string;
}

/**
 * 
 */
export class AuthorityResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for createAuthority without sending the request
     */
    async createAuthorityRequestOpts(requestParameters: CreateAuthorityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authority'] == null) {
            throw new runtime.RequiredError(
                'authority',
                'Required parameter "authority" was null or undefined when calling createAuthority().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/authorities`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthorityToJSON(requestParameters['authority']),
        };
    }

    /**
     */
    async createAuthorityRaw(requestParameters: CreateAuthorityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Authority>> {
        const requestOptions = await this.createAuthorityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorityFromJSON(jsonValue));
    }

    /**
     */
    async createAuthority(requestParameters: CreateAuthorityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Authority> {
        const response = await this.createAuthorityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAuthority without sending the request
     */
    async deleteAuthorityRequestOpts(requestParameters: DeleteAuthorityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAuthority().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/authorities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteAuthorityRaw(requestParameters: DeleteAuthorityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteAuthorityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteAuthority(requestParameters: DeleteAuthorityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAuthorityRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllAuthoritiesAsStream without sending the request
     */
    async getAllAuthoritiesAsStreamRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/authorities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllAuthoritiesAsStreamRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Authority>>> {
        const requestOptions = await this.getAllAuthoritiesAsStreamRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AuthorityFromJSON));
    }

    /**
     */
    async getAllAuthoritiesAsStream(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Authority>> {
        const response = await this.getAllAuthoritiesAsStreamRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAuthority without sending the request
     */
    async getAuthorityRequestOpts(requestParameters: GetAuthorityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAuthority().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/authorities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAuthorityRaw(requestParameters: GetAuthorityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Authority>> {
        const requestOptions = await this.getAuthorityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthorityFromJSON(jsonValue));
    }

    /**
     */
    async getAuthority(requestParameters: GetAuthorityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Authority> {
        const response = await this.getAuthorityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
