/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentDTO,
} from '../models/index';
import {
    CommentDTOFromJSON,
    CommentDTOToJSON,
} from '../models/index';

export interface CountCommentsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    titleContains?: string;
    titleDoesNotContain?: string;
    titleEquals?: string;
    titleNotEquals?: string;
    titleSpecified?: boolean;
    titleIn?: Array<string>;
    titleNotIn?: Array<string>;
    createdDateGreaterThan?: Date;
    createdDateLessThan?: Date;
    createdDateGreaterThanOrEqual?: Date;
    createdDateLessThanOrEqual?: Date;
    createdDateEquals?: Date;
    createdDateNotEquals?: Date;
    createdDateSpecified?: boolean;
    createdDateIn?: Array<Date>;
    createdDateNotIn?: Array<Date>;
    updatedDateGreaterThan?: Date;
    updatedDateLessThan?: Date;
    updatedDateGreaterThanOrEqual?: Date;
    updatedDateLessThanOrEqual?: Date;
    updatedDateEquals?: Date;
    updatedDateNotEquals?: Date;
    updatedDateSpecified?: boolean;
    updatedDateIn?: Array<Date>;
    updatedDateNotIn?: Array<Date>;
    deletedEquals?: boolean;
    deletedNotEquals?: boolean;
    deletedSpecified?: boolean;
    deletedIn?: Array<boolean>;
    deletedNotIn?: Array<boolean>;
    deletedDateGreaterThan?: Date;
    deletedDateLessThan?: Date;
    deletedDateGreaterThanOrEqual?: Date;
    deletedDateLessThanOrEqual?: Date;
    deletedDateEquals?: Date;
    deletedDateNotEquals?: Date;
    deletedDateSpecified?: boolean;
    deletedDateIn?: Array<Date>;
    deletedDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    userIdGreaterThan?: number;
    userIdLessThan?: number;
    userIdGreaterThanOrEqual?: number;
    userIdLessThanOrEqual?: number;
    userIdEquals?: number;
    userIdNotEquals?: number;
    userIdSpecified?: boolean;
    userIdIn?: Array<number>;
    userIdNotIn?: Array<number>;
    distinct?: boolean;
}

export interface CreateCommentRequest {
    commentDTO: CommentDTO;
}

export interface DeleteCommentRequest {
    id: number;
}

export interface GetAllCommentsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    titleContains?: string;
    titleDoesNotContain?: string;
    titleEquals?: string;
    titleNotEquals?: string;
    titleSpecified?: boolean;
    titleIn?: Array<string>;
    titleNotIn?: Array<string>;
    createdDateGreaterThan?: Date;
    createdDateLessThan?: Date;
    createdDateGreaterThanOrEqual?: Date;
    createdDateLessThanOrEqual?: Date;
    createdDateEquals?: Date;
    createdDateNotEquals?: Date;
    createdDateSpecified?: boolean;
    createdDateIn?: Array<Date>;
    createdDateNotIn?: Array<Date>;
    updatedDateGreaterThan?: Date;
    updatedDateLessThan?: Date;
    updatedDateGreaterThanOrEqual?: Date;
    updatedDateLessThanOrEqual?: Date;
    updatedDateEquals?: Date;
    updatedDateNotEquals?: Date;
    updatedDateSpecified?: boolean;
    updatedDateIn?: Array<Date>;
    updatedDateNotIn?: Array<Date>;
    deletedEquals?: boolean;
    deletedNotEquals?: boolean;
    deletedSpecified?: boolean;
    deletedIn?: Array<boolean>;
    deletedNotIn?: Array<boolean>;
    deletedDateGreaterThan?: Date;
    deletedDateLessThan?: Date;
    deletedDateGreaterThanOrEqual?: Date;
    deletedDateLessThanOrEqual?: Date;
    deletedDateEquals?: Date;
    deletedDateNotEquals?: Date;
    deletedDateSpecified?: boolean;
    deletedDateIn?: Array<Date>;
    deletedDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    userIdGreaterThan?: number;
    userIdLessThan?: number;
    userIdGreaterThanOrEqual?: number;
    userIdLessThanOrEqual?: number;
    userIdEquals?: number;
    userIdNotEquals?: number;
    userIdSpecified?: boolean;
    userIdIn?: Array<number>;
    userIdNotIn?: Array<number>;
    distinct?: boolean;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetCommentRequest {
    id: number;
}

export interface PartialUpdateCommentRequest {
    id: number;
    commentDTO: CommentDTO;
}

export interface UpdateCommentRequest {
    id: number;
    commentDTO: CommentDTO;
}

/**
 * 
 */
export class CommentResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for countComments without sending the request
     */
    async countCommentsRequestOpts(requestParameters: CountCommentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['titleContains'] != null) {
            queryParameters['title.contains'] = requestParameters['titleContains'];
        }

        if (requestParameters['titleDoesNotContain'] != null) {
            queryParameters['title.doesNotContain'] = requestParameters['titleDoesNotContain'];
        }

        if (requestParameters['titleEquals'] != null) {
            queryParameters['title.equals'] = requestParameters['titleEquals'];
        }

        if (requestParameters['titleNotEquals'] != null) {
            queryParameters['title.notEquals'] = requestParameters['titleNotEquals'];
        }

        if (requestParameters['titleSpecified'] != null) {
            queryParameters['title.specified'] = requestParameters['titleSpecified'];
        }

        if (requestParameters['titleIn'] != null) {
            queryParameters['title.in'] = requestParameters['titleIn'];
        }

        if (requestParameters['titleNotIn'] != null) {
            queryParameters['title.notIn'] = requestParameters['titleNotIn'];
        }

        if (requestParameters['createdDateGreaterThan'] != null) {
            queryParameters['createdDate.greaterThan'] = (requestParameters['createdDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThan'] != null) {
            queryParameters['createdDate.lessThan'] = (requestParameters['createdDateLessThan'] as any).toISOString();
        }

        if (requestParameters['createdDateGreaterThanOrEqual'] != null) {
            queryParameters['createdDate.greaterThanOrEqual'] = (requestParameters['createdDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThanOrEqual'] != null) {
            queryParameters['createdDate.lessThanOrEqual'] = (requestParameters['createdDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateEquals'] != null) {
            queryParameters['createdDate.equals'] = (requestParameters['createdDateEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateNotEquals'] != null) {
            queryParameters['createdDate.notEquals'] = (requestParameters['createdDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateSpecified'] != null) {
            queryParameters['createdDate.specified'] = requestParameters['createdDateSpecified'];
        }

        if (requestParameters['createdDateIn'] != null) {
            queryParameters['createdDate.in'] = requestParameters['createdDateIn'];
        }

        if (requestParameters['createdDateNotIn'] != null) {
            queryParameters['createdDate.notIn'] = requestParameters['createdDateNotIn'];
        }

        if (requestParameters['updatedDateGreaterThan'] != null) {
            queryParameters['updatedDate.greaterThan'] = (requestParameters['updatedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThan'] != null) {
            queryParameters['updatedDate.lessThan'] = (requestParameters['updatedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateGreaterThanOrEqual'] != null) {
            queryParameters['updatedDate.greaterThanOrEqual'] = (requestParameters['updatedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThanOrEqual'] != null) {
            queryParameters['updatedDate.lessThanOrEqual'] = (requestParameters['updatedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateEquals'] != null) {
            queryParameters['updatedDate.equals'] = (requestParameters['updatedDateEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateNotEquals'] != null) {
            queryParameters['updatedDate.notEquals'] = (requestParameters['updatedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateSpecified'] != null) {
            queryParameters['updatedDate.specified'] = requestParameters['updatedDateSpecified'];
        }

        if (requestParameters['updatedDateIn'] != null) {
            queryParameters['updatedDate.in'] = requestParameters['updatedDateIn'];
        }

        if (requestParameters['updatedDateNotIn'] != null) {
            queryParameters['updatedDate.notIn'] = requestParameters['updatedDateNotIn'];
        }

        if (requestParameters['deletedEquals'] != null) {
            queryParameters['deleted.equals'] = requestParameters['deletedEquals'];
        }

        if (requestParameters['deletedNotEquals'] != null) {
            queryParameters['deleted.notEquals'] = requestParameters['deletedNotEquals'];
        }

        if (requestParameters['deletedSpecified'] != null) {
            queryParameters['deleted.specified'] = requestParameters['deletedSpecified'];
        }

        if (requestParameters['deletedIn'] != null) {
            queryParameters['deleted.in'] = requestParameters['deletedIn'];
        }

        if (requestParameters['deletedNotIn'] != null) {
            queryParameters['deleted.notIn'] = requestParameters['deletedNotIn'];
        }

        if (requestParameters['deletedDateGreaterThan'] != null) {
            queryParameters['deletedDate.greaterThan'] = (requestParameters['deletedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThan'] != null) {
            queryParameters['deletedDate.lessThan'] = (requestParameters['deletedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateGreaterThanOrEqual'] != null) {
            queryParameters['deletedDate.greaterThanOrEqual'] = (requestParameters['deletedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThanOrEqual'] != null) {
            queryParameters['deletedDate.lessThanOrEqual'] = (requestParameters['deletedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateEquals'] != null) {
            queryParameters['deletedDate.equals'] = (requestParameters['deletedDateEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateNotEquals'] != null) {
            queryParameters['deletedDate.notEquals'] = (requestParameters['deletedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateSpecified'] != null) {
            queryParameters['deletedDate.specified'] = requestParameters['deletedDateSpecified'];
        }

        if (requestParameters['deletedDateIn'] != null) {
            queryParameters['deletedDate.in'] = requestParameters['deletedDateIn'];
        }

        if (requestParameters['deletedDateNotIn'] != null) {
            queryParameters['deletedDate.notIn'] = requestParameters['deletedDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['userIdGreaterThan'] != null) {
            queryParameters['userId.greaterThan'] = requestParameters['userIdGreaterThan'];
        }

        if (requestParameters['userIdLessThan'] != null) {
            queryParameters['userId.lessThan'] = requestParameters['userIdLessThan'];
        }

        if (requestParameters['userIdGreaterThanOrEqual'] != null) {
            queryParameters['userId.greaterThanOrEqual'] = requestParameters['userIdGreaterThanOrEqual'];
        }

        if (requestParameters['userIdLessThanOrEqual'] != null) {
            queryParameters['userId.lessThanOrEqual'] = requestParameters['userIdLessThanOrEqual'];
        }

        if (requestParameters['userIdEquals'] != null) {
            queryParameters['userId.equals'] = requestParameters['userIdEquals'];
        }

        if (requestParameters['userIdNotEquals'] != null) {
            queryParameters['userId.notEquals'] = requestParameters['userIdNotEquals'];
        }

        if (requestParameters['userIdSpecified'] != null) {
            queryParameters['userId.specified'] = requestParameters['userIdSpecified'];
        }

        if (requestParameters['userIdIn'] != null) {
            queryParameters['userId.in'] = requestParameters['userIdIn'];
        }

        if (requestParameters['userIdNotIn'] != null) {
            queryParameters['userId.notIn'] = requestParameters['userIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/comments/count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async countCommentsRaw(requestParameters: CountCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.countCommentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async countComments(requestParameters: CountCommentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createComment without sending the request
     */
    async createCommentRequestOpts(requestParameters: CreateCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commentDTO'] == null) {
            throw new runtime.RequiredError(
                'commentDTO',
                'Required parameter "commentDTO" was null or undefined when calling createComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/comments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentDTOToJSON(requestParameters['commentDTO']),
        };
    }

    /**
     */
    async createCommentRaw(requestParameters: CreateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentDTO>> {
        const requestOptions = await this.createCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentDTOFromJSON(jsonValue));
    }

    /**
     */
    async createComment(requestParameters: CreateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentDTO> {
        const response = await this.createCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteComment without sending the request
     */
    async deleteCommentRequestOpts(requestParameters: DeleteCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/comments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteCommentRaw(requestParameters: DeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteComment(requestParameters: DeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCommentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllComments without sending the request
     */
    async getAllCommentsRequestOpts(requestParameters: GetAllCommentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['titleContains'] != null) {
            queryParameters['title.contains'] = requestParameters['titleContains'];
        }

        if (requestParameters['titleDoesNotContain'] != null) {
            queryParameters['title.doesNotContain'] = requestParameters['titleDoesNotContain'];
        }

        if (requestParameters['titleEquals'] != null) {
            queryParameters['title.equals'] = requestParameters['titleEquals'];
        }

        if (requestParameters['titleNotEquals'] != null) {
            queryParameters['title.notEquals'] = requestParameters['titleNotEquals'];
        }

        if (requestParameters['titleSpecified'] != null) {
            queryParameters['title.specified'] = requestParameters['titleSpecified'];
        }

        if (requestParameters['titleIn'] != null) {
            queryParameters['title.in'] = requestParameters['titleIn'];
        }

        if (requestParameters['titleNotIn'] != null) {
            queryParameters['title.notIn'] = requestParameters['titleNotIn'];
        }

        if (requestParameters['createdDateGreaterThan'] != null) {
            queryParameters['createdDate.greaterThan'] = (requestParameters['createdDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThan'] != null) {
            queryParameters['createdDate.lessThan'] = (requestParameters['createdDateLessThan'] as any).toISOString();
        }

        if (requestParameters['createdDateGreaterThanOrEqual'] != null) {
            queryParameters['createdDate.greaterThanOrEqual'] = (requestParameters['createdDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThanOrEqual'] != null) {
            queryParameters['createdDate.lessThanOrEqual'] = (requestParameters['createdDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateEquals'] != null) {
            queryParameters['createdDate.equals'] = (requestParameters['createdDateEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateNotEquals'] != null) {
            queryParameters['createdDate.notEquals'] = (requestParameters['createdDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateSpecified'] != null) {
            queryParameters['createdDate.specified'] = requestParameters['createdDateSpecified'];
        }

        if (requestParameters['createdDateIn'] != null) {
            queryParameters['createdDate.in'] = requestParameters['createdDateIn'];
        }

        if (requestParameters['createdDateNotIn'] != null) {
            queryParameters['createdDate.notIn'] = requestParameters['createdDateNotIn'];
        }

        if (requestParameters['updatedDateGreaterThan'] != null) {
            queryParameters['updatedDate.greaterThan'] = (requestParameters['updatedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThan'] != null) {
            queryParameters['updatedDate.lessThan'] = (requestParameters['updatedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateGreaterThanOrEqual'] != null) {
            queryParameters['updatedDate.greaterThanOrEqual'] = (requestParameters['updatedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThanOrEqual'] != null) {
            queryParameters['updatedDate.lessThanOrEqual'] = (requestParameters['updatedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateEquals'] != null) {
            queryParameters['updatedDate.equals'] = (requestParameters['updatedDateEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateNotEquals'] != null) {
            queryParameters['updatedDate.notEquals'] = (requestParameters['updatedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateSpecified'] != null) {
            queryParameters['updatedDate.specified'] = requestParameters['updatedDateSpecified'];
        }

        if (requestParameters['updatedDateIn'] != null) {
            queryParameters['updatedDate.in'] = requestParameters['updatedDateIn'];
        }

        if (requestParameters['updatedDateNotIn'] != null) {
            queryParameters['updatedDate.notIn'] = requestParameters['updatedDateNotIn'];
        }

        if (requestParameters['deletedEquals'] != null) {
            queryParameters['deleted.equals'] = requestParameters['deletedEquals'];
        }

        if (requestParameters['deletedNotEquals'] != null) {
            queryParameters['deleted.notEquals'] = requestParameters['deletedNotEquals'];
        }

        if (requestParameters['deletedSpecified'] != null) {
            queryParameters['deleted.specified'] = requestParameters['deletedSpecified'];
        }

        if (requestParameters['deletedIn'] != null) {
            queryParameters['deleted.in'] = requestParameters['deletedIn'];
        }

        if (requestParameters['deletedNotIn'] != null) {
            queryParameters['deleted.notIn'] = requestParameters['deletedNotIn'];
        }

        if (requestParameters['deletedDateGreaterThan'] != null) {
            queryParameters['deletedDate.greaterThan'] = (requestParameters['deletedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThan'] != null) {
            queryParameters['deletedDate.lessThan'] = (requestParameters['deletedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateGreaterThanOrEqual'] != null) {
            queryParameters['deletedDate.greaterThanOrEqual'] = (requestParameters['deletedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThanOrEqual'] != null) {
            queryParameters['deletedDate.lessThanOrEqual'] = (requestParameters['deletedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateEquals'] != null) {
            queryParameters['deletedDate.equals'] = (requestParameters['deletedDateEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateNotEquals'] != null) {
            queryParameters['deletedDate.notEquals'] = (requestParameters['deletedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateSpecified'] != null) {
            queryParameters['deletedDate.specified'] = requestParameters['deletedDateSpecified'];
        }

        if (requestParameters['deletedDateIn'] != null) {
            queryParameters['deletedDate.in'] = requestParameters['deletedDateIn'];
        }

        if (requestParameters['deletedDateNotIn'] != null) {
            queryParameters['deletedDate.notIn'] = requestParameters['deletedDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['userIdGreaterThan'] != null) {
            queryParameters['userId.greaterThan'] = requestParameters['userIdGreaterThan'];
        }

        if (requestParameters['userIdLessThan'] != null) {
            queryParameters['userId.lessThan'] = requestParameters['userIdLessThan'];
        }

        if (requestParameters['userIdGreaterThanOrEqual'] != null) {
            queryParameters['userId.greaterThanOrEqual'] = requestParameters['userIdGreaterThanOrEqual'];
        }

        if (requestParameters['userIdLessThanOrEqual'] != null) {
            queryParameters['userId.lessThanOrEqual'] = requestParameters['userIdLessThanOrEqual'];
        }

        if (requestParameters['userIdEquals'] != null) {
            queryParameters['userId.equals'] = requestParameters['userIdEquals'];
        }

        if (requestParameters['userIdNotEquals'] != null) {
            queryParameters['userId.notEquals'] = requestParameters['userIdNotEquals'];
        }

        if (requestParameters['userIdSpecified'] != null) {
            queryParameters['userId.specified'] = requestParameters['userIdSpecified'];
        }

        if (requestParameters['userIdIn'] != null) {
            queryParameters['userId.in'] = requestParameters['userIdIn'];
        }

        if (requestParameters['userIdNotIn'] != null) {
            queryParameters['userId.notIn'] = requestParameters['userIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/comments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllCommentsRaw(requestParameters: GetAllCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommentDTO>>> {
        const requestOptions = await this.getAllCommentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommentDTOFromJSON));
    }

    /**
     */
    async getAllComments(requestParameters: GetAllCommentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommentDTO>> {
        const response = await this.getAllCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getComment without sending the request
     */
    async getCommentRequestOpts(requestParameters: GetCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/comments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCommentRaw(requestParameters: GetCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentDTO>> {
        const requestOptions = await this.getCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentDTOFromJSON(jsonValue));
    }

    /**
     */
    async getComment(requestParameters: GetCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentDTO> {
        const response = await this.getCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateComment without sending the request
     */
    async partialUpdateCommentRequestOpts(requestParameters: PartialUpdateCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdateComment().'
            );
        }

        if (requestParameters['commentDTO'] == null) {
            throw new runtime.RequiredError(
                'commentDTO',
                'Required parameter "commentDTO" was null or undefined when calling partialUpdateComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/comments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CommentDTOToJSON(requestParameters['commentDTO']),
        };
    }

    /**
     */
    async partialUpdateCommentRaw(requestParameters: PartialUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentDTO>> {
        const requestOptions = await this.partialUpdateCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentDTOFromJSON(jsonValue));
    }

    /**
     */
    async partialUpdateComment(requestParameters: PartialUpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentDTO> {
        const response = await this.partialUpdateCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateComment without sending the request
     */
    async updateCommentRequestOpts(requestParameters: UpdateCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateComment().'
            );
        }

        if (requestParameters['commentDTO'] == null) {
            throw new runtime.RequiredError(
                'commentDTO',
                'Required parameter "commentDTO" was null or undefined when calling updateComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/comments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CommentDTOToJSON(requestParameters['commentDTO']),
        };
    }

    /**
     */
    async updateCommentRaw(requestParameters: UpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentDTO>> {
        const requestOptions = await this.updateCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateComment(requestParameters: UpdateCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentDTO> {
        const response = await this.updateCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
