/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DepartmentDTO,
} from '../models/index';
import {
    DepartmentDTOFromJSON,
    DepartmentDTOToJSON,
} from '../models/index';

export interface CountDepartmentsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    nameContains?: string;
    nameDoesNotContain?: string;
    nameEquals?: string;
    nameNotEquals?: string;
    nameSpecified?: boolean;
    nameIn?: Array<string>;
    nameNotIn?: Array<string>;
    contactEmailContains?: string;
    contactEmailDoesNotContain?: string;
    contactEmailEquals?: string;
    contactEmailNotEquals?: string;
    contactEmailSpecified?: boolean;
    contactEmailIn?: Array<string>;
    contactEmailNotIn?: Array<string>;
    contactPhoneContains?: string;
    contactPhoneDoesNotContain?: string;
    contactPhoneEquals?: string;
    contactPhoneNotEquals?: string;
    contactPhoneSpecified?: boolean;
    contactPhoneIn?: Array<string>;
    contactPhoneNotIn?: Array<string>;
    activeEquals?: boolean;
    activeNotEquals?: boolean;
    activeSpecified?: boolean;
    activeIn?: Array<boolean>;
    activeNotIn?: Array<boolean>;
    distinct?: boolean;
}

export interface CreateDepartmentRequest {
    departmentDTO: DepartmentDTO;
}

export interface DeleteDepartmentRequest {
    id: number;
}

export interface GetAllDepartmentsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    nameContains?: string;
    nameDoesNotContain?: string;
    nameEquals?: string;
    nameNotEquals?: string;
    nameSpecified?: boolean;
    nameIn?: Array<string>;
    nameNotIn?: Array<string>;
    contactEmailContains?: string;
    contactEmailDoesNotContain?: string;
    contactEmailEquals?: string;
    contactEmailNotEquals?: string;
    contactEmailSpecified?: boolean;
    contactEmailIn?: Array<string>;
    contactEmailNotIn?: Array<string>;
    contactPhoneContains?: string;
    contactPhoneDoesNotContain?: string;
    contactPhoneEquals?: string;
    contactPhoneNotEquals?: string;
    contactPhoneSpecified?: boolean;
    contactPhoneIn?: Array<string>;
    contactPhoneNotIn?: Array<string>;
    activeEquals?: boolean;
    activeNotEquals?: boolean;
    activeSpecified?: boolean;
    activeIn?: Array<boolean>;
    activeNotIn?: Array<boolean>;
    distinct?: boolean;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetDepartmentRequest {
    id: number;
}

export interface PartialUpdateDepartmentRequest {
    id: number;
    departmentDTO: DepartmentDTO;
}

export interface UpdateDepartmentRequest {
    id: number;
    departmentDTO: DepartmentDTO;
}

/**
 * 
 */
export class DepartmentResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for countDepartments without sending the request
     */
    async countDepartmentsRequestOpts(requestParameters: CountDepartmentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['nameContains'] != null) {
            queryParameters['name.contains'] = requestParameters['nameContains'];
        }

        if (requestParameters['nameDoesNotContain'] != null) {
            queryParameters['name.doesNotContain'] = requestParameters['nameDoesNotContain'];
        }

        if (requestParameters['nameEquals'] != null) {
            queryParameters['name.equals'] = requestParameters['nameEquals'];
        }

        if (requestParameters['nameNotEquals'] != null) {
            queryParameters['name.notEquals'] = requestParameters['nameNotEquals'];
        }

        if (requestParameters['nameSpecified'] != null) {
            queryParameters['name.specified'] = requestParameters['nameSpecified'];
        }

        if (requestParameters['nameIn'] != null) {
            queryParameters['name.in'] = requestParameters['nameIn'];
        }

        if (requestParameters['nameNotIn'] != null) {
            queryParameters['name.notIn'] = requestParameters['nameNotIn'];
        }

        if (requestParameters['contactEmailContains'] != null) {
            queryParameters['contactEmail.contains'] = requestParameters['contactEmailContains'];
        }

        if (requestParameters['contactEmailDoesNotContain'] != null) {
            queryParameters['contactEmail.doesNotContain'] = requestParameters['contactEmailDoesNotContain'];
        }

        if (requestParameters['contactEmailEquals'] != null) {
            queryParameters['contactEmail.equals'] = requestParameters['contactEmailEquals'];
        }

        if (requestParameters['contactEmailNotEquals'] != null) {
            queryParameters['contactEmail.notEquals'] = requestParameters['contactEmailNotEquals'];
        }

        if (requestParameters['contactEmailSpecified'] != null) {
            queryParameters['contactEmail.specified'] = requestParameters['contactEmailSpecified'];
        }

        if (requestParameters['contactEmailIn'] != null) {
            queryParameters['contactEmail.in'] = requestParameters['contactEmailIn'];
        }

        if (requestParameters['contactEmailNotIn'] != null) {
            queryParameters['contactEmail.notIn'] = requestParameters['contactEmailNotIn'];
        }

        if (requestParameters['contactPhoneContains'] != null) {
            queryParameters['contactPhone.contains'] = requestParameters['contactPhoneContains'];
        }

        if (requestParameters['contactPhoneDoesNotContain'] != null) {
            queryParameters['contactPhone.doesNotContain'] = requestParameters['contactPhoneDoesNotContain'];
        }

        if (requestParameters['contactPhoneEquals'] != null) {
            queryParameters['contactPhone.equals'] = requestParameters['contactPhoneEquals'];
        }

        if (requestParameters['contactPhoneNotEquals'] != null) {
            queryParameters['contactPhone.notEquals'] = requestParameters['contactPhoneNotEquals'];
        }

        if (requestParameters['contactPhoneSpecified'] != null) {
            queryParameters['contactPhone.specified'] = requestParameters['contactPhoneSpecified'];
        }

        if (requestParameters['contactPhoneIn'] != null) {
            queryParameters['contactPhone.in'] = requestParameters['contactPhoneIn'];
        }

        if (requestParameters['contactPhoneNotIn'] != null) {
            queryParameters['contactPhone.notIn'] = requestParameters['contactPhoneNotIn'];
        }

        if (requestParameters['activeEquals'] != null) {
            queryParameters['active.equals'] = requestParameters['activeEquals'];
        }

        if (requestParameters['activeNotEquals'] != null) {
            queryParameters['active.notEquals'] = requestParameters['activeNotEquals'];
        }

        if (requestParameters['activeSpecified'] != null) {
            queryParameters['active.specified'] = requestParameters['activeSpecified'];
        }

        if (requestParameters['activeIn'] != null) {
            queryParameters['active.in'] = requestParameters['activeIn'];
        }

        if (requestParameters['activeNotIn'] != null) {
            queryParameters['active.notIn'] = requestParameters['activeNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/departments/count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async countDepartmentsRaw(requestParameters: CountDepartmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.countDepartmentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async countDepartments(requestParameters: CountDepartmentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countDepartmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createDepartment without sending the request
     */
    async createDepartmentRequestOpts(requestParameters: CreateDepartmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['departmentDTO'] == null) {
            throw new runtime.RequiredError(
                'departmentDTO',
                'Required parameter "departmentDTO" was null or undefined when calling createDepartment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/departments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DepartmentDTOToJSON(requestParameters['departmentDTO']),
        };
    }

    /**
     */
    async createDepartmentRaw(requestParameters: CreateDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>> {
        const requestOptions = await this.createDepartmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentDTOFromJSON(jsonValue));
    }

    /**
     */
    async createDepartment(requestParameters: CreateDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO> {
        const response = await this.createDepartmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDepartment without sending the request
     */
    async deleteDepartmentRequestOpts(requestParameters: DeleteDepartmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDepartment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/departments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteDepartmentRaw(requestParameters: DeleteDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDepartmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteDepartment(requestParameters: DeleteDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDepartmentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllDepartments without sending the request
     */
    async getAllDepartmentsRequestOpts(requestParameters: GetAllDepartmentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['nameContains'] != null) {
            queryParameters['name.contains'] = requestParameters['nameContains'];
        }

        if (requestParameters['nameDoesNotContain'] != null) {
            queryParameters['name.doesNotContain'] = requestParameters['nameDoesNotContain'];
        }

        if (requestParameters['nameEquals'] != null) {
            queryParameters['name.equals'] = requestParameters['nameEquals'];
        }

        if (requestParameters['nameNotEquals'] != null) {
            queryParameters['name.notEquals'] = requestParameters['nameNotEquals'];
        }

        if (requestParameters['nameSpecified'] != null) {
            queryParameters['name.specified'] = requestParameters['nameSpecified'];
        }

        if (requestParameters['nameIn'] != null) {
            queryParameters['name.in'] = requestParameters['nameIn'];
        }

        if (requestParameters['nameNotIn'] != null) {
            queryParameters['name.notIn'] = requestParameters['nameNotIn'];
        }

        if (requestParameters['contactEmailContains'] != null) {
            queryParameters['contactEmail.contains'] = requestParameters['contactEmailContains'];
        }

        if (requestParameters['contactEmailDoesNotContain'] != null) {
            queryParameters['contactEmail.doesNotContain'] = requestParameters['contactEmailDoesNotContain'];
        }

        if (requestParameters['contactEmailEquals'] != null) {
            queryParameters['contactEmail.equals'] = requestParameters['contactEmailEquals'];
        }

        if (requestParameters['contactEmailNotEquals'] != null) {
            queryParameters['contactEmail.notEquals'] = requestParameters['contactEmailNotEquals'];
        }

        if (requestParameters['contactEmailSpecified'] != null) {
            queryParameters['contactEmail.specified'] = requestParameters['contactEmailSpecified'];
        }

        if (requestParameters['contactEmailIn'] != null) {
            queryParameters['contactEmail.in'] = requestParameters['contactEmailIn'];
        }

        if (requestParameters['contactEmailNotIn'] != null) {
            queryParameters['contactEmail.notIn'] = requestParameters['contactEmailNotIn'];
        }

        if (requestParameters['contactPhoneContains'] != null) {
            queryParameters['contactPhone.contains'] = requestParameters['contactPhoneContains'];
        }

        if (requestParameters['contactPhoneDoesNotContain'] != null) {
            queryParameters['contactPhone.doesNotContain'] = requestParameters['contactPhoneDoesNotContain'];
        }

        if (requestParameters['contactPhoneEquals'] != null) {
            queryParameters['contactPhone.equals'] = requestParameters['contactPhoneEquals'];
        }

        if (requestParameters['contactPhoneNotEquals'] != null) {
            queryParameters['contactPhone.notEquals'] = requestParameters['contactPhoneNotEquals'];
        }

        if (requestParameters['contactPhoneSpecified'] != null) {
            queryParameters['contactPhone.specified'] = requestParameters['contactPhoneSpecified'];
        }

        if (requestParameters['contactPhoneIn'] != null) {
            queryParameters['contactPhone.in'] = requestParameters['contactPhoneIn'];
        }

        if (requestParameters['contactPhoneNotIn'] != null) {
            queryParameters['contactPhone.notIn'] = requestParameters['contactPhoneNotIn'];
        }

        if (requestParameters['activeEquals'] != null) {
            queryParameters['active.equals'] = requestParameters['activeEquals'];
        }

        if (requestParameters['activeNotEquals'] != null) {
            queryParameters['active.notEquals'] = requestParameters['activeNotEquals'];
        }

        if (requestParameters['activeSpecified'] != null) {
            queryParameters['active.specified'] = requestParameters['activeSpecified'];
        }

        if (requestParameters['activeIn'] != null) {
            queryParameters['active.in'] = requestParameters['activeIn'];
        }

        if (requestParameters['activeNotIn'] != null) {
            queryParameters['active.notIn'] = requestParameters['activeNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/departments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllDepartmentsRaw(requestParameters: GetAllDepartmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DepartmentDTO>>> {
        const requestOptions = await this.getAllDepartmentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DepartmentDTOFromJSON));
    }

    /**
     */
    async getAllDepartments(requestParameters: GetAllDepartmentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DepartmentDTO>> {
        const response = await this.getAllDepartmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDepartment without sending the request
     */
    async getDepartmentRequestOpts(requestParameters: GetDepartmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDepartment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/departments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getDepartmentRaw(requestParameters: GetDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>> {
        const requestOptions = await this.getDepartmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentDTOFromJSON(jsonValue));
    }

    /**
     */
    async getDepartment(requestParameters: GetDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO> {
        const response = await this.getDepartmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateDepartment without sending the request
     */
    async partialUpdateDepartmentRequestOpts(requestParameters: PartialUpdateDepartmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdateDepartment().'
            );
        }

        if (requestParameters['departmentDTO'] == null) {
            throw new runtime.RequiredError(
                'departmentDTO',
                'Required parameter "departmentDTO" was null or undefined when calling partialUpdateDepartment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/departments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DepartmentDTOToJSON(requestParameters['departmentDTO']),
        };
    }

    /**
     */
    async partialUpdateDepartmentRaw(requestParameters: PartialUpdateDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>> {
        const requestOptions = await this.partialUpdateDepartmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentDTOFromJSON(jsonValue));
    }

    /**
     */
    async partialUpdateDepartment(requestParameters: PartialUpdateDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO> {
        const response = await this.partialUpdateDepartmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDepartment without sending the request
     */
    async updateDepartmentRequestOpts(requestParameters: UpdateDepartmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateDepartment().'
            );
        }

        if (requestParameters['departmentDTO'] == null) {
            throw new runtime.RequiredError(
                'departmentDTO',
                'Required parameter "departmentDTO" was null or undefined when calling updateDepartment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/departments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DepartmentDTOToJSON(requestParameters['departmentDTO']),
        };
    }

    /**
     */
    async updateDepartmentRaw(requestParameters: UpdateDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DepartmentDTO>> {
        const requestOptions = await this.updateDepartmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DepartmentDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateDepartment(requestParameters: UpdateDepartmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DepartmentDTO> {
        const response = await this.updateDepartmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
