/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LocationDTO,
} from '../models/index';
import {
    LocationDTOFromJSON,
    LocationDTOToJSON,
} from '../models/index';

export interface CountLocationsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    addressTextContains?: string;
    addressTextDoesNotContain?: string;
    addressTextEquals?: string;
    addressTextNotEquals?: string;
    addressTextSpecified?: boolean;
    addressTextIn?: Array<string>;
    addressTextNotIn?: Array<string>;
    landmarkContains?: string;
    landmarkDoesNotContain?: string;
    landmarkEquals?: string;
    landmarkNotEquals?: string;
    landmarkSpecified?: boolean;
    landmarkIn?: Array<string>;
    landmarkNotIn?: Array<string>;
    latitudeGreaterThan?: number;
    latitudeLessThan?: number;
    latitudeGreaterThanOrEqual?: number;
    latitudeLessThanOrEqual?: number;
    latitudeEquals?: number;
    latitudeNotEquals?: number;
    latitudeSpecified?: boolean;
    latitudeIn?: Array<number>;
    latitudeNotIn?: Array<number>;
    longitudeGreaterThan?: number;
    longitudeLessThan?: number;
    longitudeGreaterThanOrEqual?: number;
    longitudeLessThanOrEqual?: number;
    longitudeEquals?: number;
    longitudeNotEquals?: number;
    longitudeSpecified?: boolean;
    longitudeIn?: Array<number>;
    longitudeNotIn?: Array<number>;
    wardIdGreaterThan?: number;
    wardIdLessThan?: number;
    wardIdGreaterThanOrEqual?: number;
    wardIdLessThanOrEqual?: number;
    wardIdEquals?: number;
    wardIdNotEquals?: number;
    wardIdSpecified?: boolean;
    wardIdIn?: Array<number>;
    wardIdNotIn?: Array<number>;
    distinct?: boolean;
}

export interface CreateLocationRequest {
    locationDTO: LocationDTO;
}

export interface DeleteLocationRequest {
    id: number;
}

export interface GetAllLocationsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    addressTextContains?: string;
    addressTextDoesNotContain?: string;
    addressTextEquals?: string;
    addressTextNotEquals?: string;
    addressTextSpecified?: boolean;
    addressTextIn?: Array<string>;
    addressTextNotIn?: Array<string>;
    landmarkContains?: string;
    landmarkDoesNotContain?: string;
    landmarkEquals?: string;
    landmarkNotEquals?: string;
    landmarkSpecified?: boolean;
    landmarkIn?: Array<string>;
    landmarkNotIn?: Array<string>;
    latitudeGreaterThan?: number;
    latitudeLessThan?: number;
    latitudeGreaterThanOrEqual?: number;
    latitudeLessThanOrEqual?: number;
    latitudeEquals?: number;
    latitudeNotEquals?: number;
    latitudeSpecified?: boolean;
    latitudeIn?: Array<number>;
    latitudeNotIn?: Array<number>;
    longitudeGreaterThan?: number;
    longitudeLessThan?: number;
    longitudeGreaterThanOrEqual?: number;
    longitudeLessThanOrEqual?: number;
    longitudeEquals?: number;
    longitudeNotEquals?: number;
    longitudeSpecified?: boolean;
    longitudeIn?: Array<number>;
    longitudeNotIn?: Array<number>;
    wardIdGreaterThan?: number;
    wardIdLessThan?: number;
    wardIdGreaterThanOrEqual?: number;
    wardIdLessThanOrEqual?: number;
    wardIdEquals?: number;
    wardIdNotEquals?: number;
    wardIdSpecified?: boolean;
    wardIdIn?: Array<number>;
    wardIdNotIn?: Array<number>;
    distinct?: boolean;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetLocationRequest {
    id: number;
}

export interface PartialUpdateLocationRequest {
    id: number;
    locationDTO: LocationDTO;
}

export interface UpdateLocationRequest {
    id: number;
    locationDTO: LocationDTO;
}

/**
 * 
 */
export class LocationResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for countLocations without sending the request
     */
    async countLocationsRequestOpts(requestParameters: CountLocationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['addressTextContains'] != null) {
            queryParameters['addressText.contains'] = requestParameters['addressTextContains'];
        }

        if (requestParameters['addressTextDoesNotContain'] != null) {
            queryParameters['addressText.doesNotContain'] = requestParameters['addressTextDoesNotContain'];
        }

        if (requestParameters['addressTextEquals'] != null) {
            queryParameters['addressText.equals'] = requestParameters['addressTextEquals'];
        }

        if (requestParameters['addressTextNotEquals'] != null) {
            queryParameters['addressText.notEquals'] = requestParameters['addressTextNotEquals'];
        }

        if (requestParameters['addressTextSpecified'] != null) {
            queryParameters['addressText.specified'] = requestParameters['addressTextSpecified'];
        }

        if (requestParameters['addressTextIn'] != null) {
            queryParameters['addressText.in'] = requestParameters['addressTextIn'];
        }

        if (requestParameters['addressTextNotIn'] != null) {
            queryParameters['addressText.notIn'] = requestParameters['addressTextNotIn'];
        }

        if (requestParameters['landmarkContains'] != null) {
            queryParameters['landmark.contains'] = requestParameters['landmarkContains'];
        }

        if (requestParameters['landmarkDoesNotContain'] != null) {
            queryParameters['landmark.doesNotContain'] = requestParameters['landmarkDoesNotContain'];
        }

        if (requestParameters['landmarkEquals'] != null) {
            queryParameters['landmark.equals'] = requestParameters['landmarkEquals'];
        }

        if (requestParameters['landmarkNotEquals'] != null) {
            queryParameters['landmark.notEquals'] = requestParameters['landmarkNotEquals'];
        }

        if (requestParameters['landmarkSpecified'] != null) {
            queryParameters['landmark.specified'] = requestParameters['landmarkSpecified'];
        }

        if (requestParameters['landmarkIn'] != null) {
            queryParameters['landmark.in'] = requestParameters['landmarkIn'];
        }

        if (requestParameters['landmarkNotIn'] != null) {
            queryParameters['landmark.notIn'] = requestParameters['landmarkNotIn'];
        }

        if (requestParameters['latitudeGreaterThan'] != null) {
            queryParameters['latitude.greaterThan'] = requestParameters['latitudeGreaterThan'];
        }

        if (requestParameters['latitudeLessThan'] != null) {
            queryParameters['latitude.lessThan'] = requestParameters['latitudeLessThan'];
        }

        if (requestParameters['latitudeGreaterThanOrEqual'] != null) {
            queryParameters['latitude.greaterThanOrEqual'] = requestParameters['latitudeGreaterThanOrEqual'];
        }

        if (requestParameters['latitudeLessThanOrEqual'] != null) {
            queryParameters['latitude.lessThanOrEqual'] = requestParameters['latitudeLessThanOrEqual'];
        }

        if (requestParameters['latitudeEquals'] != null) {
            queryParameters['latitude.equals'] = requestParameters['latitudeEquals'];
        }

        if (requestParameters['latitudeNotEquals'] != null) {
            queryParameters['latitude.notEquals'] = requestParameters['latitudeNotEquals'];
        }

        if (requestParameters['latitudeSpecified'] != null) {
            queryParameters['latitude.specified'] = requestParameters['latitudeSpecified'];
        }

        if (requestParameters['latitudeIn'] != null) {
            queryParameters['latitude.in'] = requestParameters['latitudeIn'];
        }

        if (requestParameters['latitudeNotIn'] != null) {
            queryParameters['latitude.notIn'] = requestParameters['latitudeNotIn'];
        }

        if (requestParameters['longitudeGreaterThan'] != null) {
            queryParameters['longitude.greaterThan'] = requestParameters['longitudeGreaterThan'];
        }

        if (requestParameters['longitudeLessThan'] != null) {
            queryParameters['longitude.lessThan'] = requestParameters['longitudeLessThan'];
        }

        if (requestParameters['longitudeGreaterThanOrEqual'] != null) {
            queryParameters['longitude.greaterThanOrEqual'] = requestParameters['longitudeGreaterThanOrEqual'];
        }

        if (requestParameters['longitudeLessThanOrEqual'] != null) {
            queryParameters['longitude.lessThanOrEqual'] = requestParameters['longitudeLessThanOrEqual'];
        }

        if (requestParameters['longitudeEquals'] != null) {
            queryParameters['longitude.equals'] = requestParameters['longitudeEquals'];
        }

        if (requestParameters['longitudeNotEquals'] != null) {
            queryParameters['longitude.notEquals'] = requestParameters['longitudeNotEquals'];
        }

        if (requestParameters['longitudeSpecified'] != null) {
            queryParameters['longitude.specified'] = requestParameters['longitudeSpecified'];
        }

        if (requestParameters['longitudeIn'] != null) {
            queryParameters['longitude.in'] = requestParameters['longitudeIn'];
        }

        if (requestParameters['longitudeNotIn'] != null) {
            queryParameters['longitude.notIn'] = requestParameters['longitudeNotIn'];
        }

        if (requestParameters['wardIdGreaterThan'] != null) {
            queryParameters['wardId.greaterThan'] = requestParameters['wardIdGreaterThan'];
        }

        if (requestParameters['wardIdLessThan'] != null) {
            queryParameters['wardId.lessThan'] = requestParameters['wardIdLessThan'];
        }

        if (requestParameters['wardIdGreaterThanOrEqual'] != null) {
            queryParameters['wardId.greaterThanOrEqual'] = requestParameters['wardIdGreaterThanOrEqual'];
        }

        if (requestParameters['wardIdLessThanOrEqual'] != null) {
            queryParameters['wardId.lessThanOrEqual'] = requestParameters['wardIdLessThanOrEqual'];
        }

        if (requestParameters['wardIdEquals'] != null) {
            queryParameters['wardId.equals'] = requestParameters['wardIdEquals'];
        }

        if (requestParameters['wardIdNotEquals'] != null) {
            queryParameters['wardId.notEquals'] = requestParameters['wardIdNotEquals'];
        }

        if (requestParameters['wardIdSpecified'] != null) {
            queryParameters['wardId.specified'] = requestParameters['wardIdSpecified'];
        }

        if (requestParameters['wardIdIn'] != null) {
            queryParameters['wardId.in'] = requestParameters['wardIdIn'];
        }

        if (requestParameters['wardIdNotIn'] != null) {
            queryParameters['wardId.notIn'] = requestParameters['wardIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/locations/count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async countLocationsRaw(requestParameters: CountLocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.countLocationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async countLocations(requestParameters: CountLocationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countLocationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createLocation without sending the request
     */
    async createLocationRequestOpts(requestParameters: CreateLocationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['locationDTO'] == null) {
            throw new runtime.RequiredError(
                'locationDTO',
                'Required parameter "locationDTO" was null or undefined when calling createLocation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/locations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LocationDTOToJSON(requestParameters['locationDTO']),
        };
    }

    /**
     */
    async createLocationRaw(requestParameters: CreateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationDTO>> {
        const requestOptions = await this.createLocationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationDTOFromJSON(jsonValue));
    }

    /**
     */
    async createLocation(requestParameters: CreateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationDTO> {
        const response = await this.createLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteLocation without sending the request
     */
    async deleteLocationRequestOpts(requestParameters: DeleteLocationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteLocation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/locations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteLocationRaw(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteLocationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteLocation(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLocationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllLocations without sending the request
     */
    async getAllLocationsRequestOpts(requestParameters: GetAllLocationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['addressTextContains'] != null) {
            queryParameters['addressText.contains'] = requestParameters['addressTextContains'];
        }

        if (requestParameters['addressTextDoesNotContain'] != null) {
            queryParameters['addressText.doesNotContain'] = requestParameters['addressTextDoesNotContain'];
        }

        if (requestParameters['addressTextEquals'] != null) {
            queryParameters['addressText.equals'] = requestParameters['addressTextEquals'];
        }

        if (requestParameters['addressTextNotEquals'] != null) {
            queryParameters['addressText.notEquals'] = requestParameters['addressTextNotEquals'];
        }

        if (requestParameters['addressTextSpecified'] != null) {
            queryParameters['addressText.specified'] = requestParameters['addressTextSpecified'];
        }

        if (requestParameters['addressTextIn'] != null) {
            queryParameters['addressText.in'] = requestParameters['addressTextIn'];
        }

        if (requestParameters['addressTextNotIn'] != null) {
            queryParameters['addressText.notIn'] = requestParameters['addressTextNotIn'];
        }

        if (requestParameters['landmarkContains'] != null) {
            queryParameters['landmark.contains'] = requestParameters['landmarkContains'];
        }

        if (requestParameters['landmarkDoesNotContain'] != null) {
            queryParameters['landmark.doesNotContain'] = requestParameters['landmarkDoesNotContain'];
        }

        if (requestParameters['landmarkEquals'] != null) {
            queryParameters['landmark.equals'] = requestParameters['landmarkEquals'];
        }

        if (requestParameters['landmarkNotEquals'] != null) {
            queryParameters['landmark.notEquals'] = requestParameters['landmarkNotEquals'];
        }

        if (requestParameters['landmarkSpecified'] != null) {
            queryParameters['landmark.specified'] = requestParameters['landmarkSpecified'];
        }

        if (requestParameters['landmarkIn'] != null) {
            queryParameters['landmark.in'] = requestParameters['landmarkIn'];
        }

        if (requestParameters['landmarkNotIn'] != null) {
            queryParameters['landmark.notIn'] = requestParameters['landmarkNotIn'];
        }

        if (requestParameters['latitudeGreaterThan'] != null) {
            queryParameters['latitude.greaterThan'] = requestParameters['latitudeGreaterThan'];
        }

        if (requestParameters['latitudeLessThan'] != null) {
            queryParameters['latitude.lessThan'] = requestParameters['latitudeLessThan'];
        }

        if (requestParameters['latitudeGreaterThanOrEqual'] != null) {
            queryParameters['latitude.greaterThanOrEqual'] = requestParameters['latitudeGreaterThanOrEqual'];
        }

        if (requestParameters['latitudeLessThanOrEqual'] != null) {
            queryParameters['latitude.lessThanOrEqual'] = requestParameters['latitudeLessThanOrEqual'];
        }

        if (requestParameters['latitudeEquals'] != null) {
            queryParameters['latitude.equals'] = requestParameters['latitudeEquals'];
        }

        if (requestParameters['latitudeNotEquals'] != null) {
            queryParameters['latitude.notEquals'] = requestParameters['latitudeNotEquals'];
        }

        if (requestParameters['latitudeSpecified'] != null) {
            queryParameters['latitude.specified'] = requestParameters['latitudeSpecified'];
        }

        if (requestParameters['latitudeIn'] != null) {
            queryParameters['latitude.in'] = requestParameters['latitudeIn'];
        }

        if (requestParameters['latitudeNotIn'] != null) {
            queryParameters['latitude.notIn'] = requestParameters['latitudeNotIn'];
        }

        if (requestParameters['longitudeGreaterThan'] != null) {
            queryParameters['longitude.greaterThan'] = requestParameters['longitudeGreaterThan'];
        }

        if (requestParameters['longitudeLessThan'] != null) {
            queryParameters['longitude.lessThan'] = requestParameters['longitudeLessThan'];
        }

        if (requestParameters['longitudeGreaterThanOrEqual'] != null) {
            queryParameters['longitude.greaterThanOrEqual'] = requestParameters['longitudeGreaterThanOrEqual'];
        }

        if (requestParameters['longitudeLessThanOrEqual'] != null) {
            queryParameters['longitude.lessThanOrEqual'] = requestParameters['longitudeLessThanOrEqual'];
        }

        if (requestParameters['longitudeEquals'] != null) {
            queryParameters['longitude.equals'] = requestParameters['longitudeEquals'];
        }

        if (requestParameters['longitudeNotEquals'] != null) {
            queryParameters['longitude.notEquals'] = requestParameters['longitudeNotEquals'];
        }

        if (requestParameters['longitudeSpecified'] != null) {
            queryParameters['longitude.specified'] = requestParameters['longitudeSpecified'];
        }

        if (requestParameters['longitudeIn'] != null) {
            queryParameters['longitude.in'] = requestParameters['longitudeIn'];
        }

        if (requestParameters['longitudeNotIn'] != null) {
            queryParameters['longitude.notIn'] = requestParameters['longitudeNotIn'];
        }

        if (requestParameters['wardIdGreaterThan'] != null) {
            queryParameters['wardId.greaterThan'] = requestParameters['wardIdGreaterThan'];
        }

        if (requestParameters['wardIdLessThan'] != null) {
            queryParameters['wardId.lessThan'] = requestParameters['wardIdLessThan'];
        }

        if (requestParameters['wardIdGreaterThanOrEqual'] != null) {
            queryParameters['wardId.greaterThanOrEqual'] = requestParameters['wardIdGreaterThanOrEqual'];
        }

        if (requestParameters['wardIdLessThanOrEqual'] != null) {
            queryParameters['wardId.lessThanOrEqual'] = requestParameters['wardIdLessThanOrEqual'];
        }

        if (requestParameters['wardIdEquals'] != null) {
            queryParameters['wardId.equals'] = requestParameters['wardIdEquals'];
        }

        if (requestParameters['wardIdNotEquals'] != null) {
            queryParameters['wardId.notEquals'] = requestParameters['wardIdNotEquals'];
        }

        if (requestParameters['wardIdSpecified'] != null) {
            queryParameters['wardId.specified'] = requestParameters['wardIdSpecified'];
        }

        if (requestParameters['wardIdIn'] != null) {
            queryParameters['wardId.in'] = requestParameters['wardIdIn'];
        }

        if (requestParameters['wardIdNotIn'] != null) {
            queryParameters['wardId.notIn'] = requestParameters['wardIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/locations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllLocationsRaw(requestParameters: GetAllLocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LocationDTO>>> {
        const requestOptions = await this.getAllLocationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LocationDTOFromJSON));
    }

    /**
     */
    async getAllLocations(requestParameters: GetAllLocationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LocationDTO>> {
        const response = await this.getAllLocationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLocation without sending the request
     */
    async getLocationRequestOpts(requestParameters: GetLocationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getLocation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/locations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getLocationRaw(requestParameters: GetLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationDTO>> {
        const requestOptions = await this.getLocationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationDTOFromJSON(jsonValue));
    }

    /**
     */
    async getLocation(requestParameters: GetLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationDTO> {
        const response = await this.getLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateLocation without sending the request
     */
    async partialUpdateLocationRequestOpts(requestParameters: PartialUpdateLocationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdateLocation().'
            );
        }

        if (requestParameters['locationDTO'] == null) {
            throw new runtime.RequiredError(
                'locationDTO',
                'Required parameter "locationDTO" was null or undefined when calling partialUpdateLocation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/locations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: LocationDTOToJSON(requestParameters['locationDTO']),
        };
    }

    /**
     */
    async partialUpdateLocationRaw(requestParameters: PartialUpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationDTO>> {
        const requestOptions = await this.partialUpdateLocationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationDTOFromJSON(jsonValue));
    }

    /**
     */
    async partialUpdateLocation(requestParameters: PartialUpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationDTO> {
        const response = await this.partialUpdateLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateLocation without sending the request
     */
    async updateLocationRequestOpts(requestParameters: UpdateLocationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateLocation().'
            );
        }

        if (requestParameters['locationDTO'] == null) {
            throw new runtime.RequiredError(
                'locationDTO',
                'Required parameter "locationDTO" was null or undefined when calling updateLocation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/locations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LocationDTOToJSON(requestParameters['locationDTO']),
        };
    }

    /**
     */
    async updateLocationRaw(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationDTO>> {
        const requestOptions = await this.updateLocationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateLocation(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationDTO> {
        const response = await this.updateLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
