/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TicketDTO,
} from '../models/index';
import {
    TicketDTOFromJSON,
    TicketDTOToJSON,
} from '../models/index';

export interface CountTicketsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    titleContains?: string;
    titleDoesNotContain?: string;
    titleEquals?: string;
    titleNotEquals?: string;
    titleSpecified?: boolean;
    titleIn?: Array<string>;
    titleNotIn?: Array<string>;
    statusEquals?: CountTicketsStatusEqualsEnum;
    statusNotEquals?: CountTicketsStatusNotEqualsEnum;
    statusSpecified?: boolean;
    statusIn?: Array<CountTicketsStatusInEnum>;
    statusNotIn?: Array<CountTicketsStatusNotInEnum>;
    priorityEquals?: CountTicketsPriorityEqualsEnum;
    priorityNotEquals?: CountTicketsPriorityNotEqualsEnum;
    prioritySpecified?: boolean;
    priorityIn?: Array<CountTicketsPriorityInEnum>;
    priorityNotIn?: Array<CountTicketsPriorityNotInEnum>;
    visibilityEquals?: CountTicketsVisibilityEqualsEnum;
    visibilityNotEquals?: CountTicketsVisibilityNotEqualsEnum;
    visibilitySpecified?: boolean;
    visibilityIn?: Array<CountTicketsVisibilityInEnum>;
    visibilityNotIn?: Array<CountTicketsVisibilityNotInEnum>;
    categoryEquals?: CountTicketsCategoryEqualsEnum;
    categoryNotEquals?: CountTicketsCategoryNotEqualsEnum;
    categorySpecified?: boolean;
    categoryIn?: Array<CountTicketsCategoryInEnum>;
    categoryNotIn?: Array<CountTicketsCategoryNotInEnum>;
    createdDateGreaterThan?: Date;
    createdDateLessThan?: Date;
    createdDateGreaterThanOrEqual?: Date;
    createdDateLessThanOrEqual?: Date;
    createdDateEquals?: Date;
    createdDateNotEquals?: Date;
    createdDateSpecified?: boolean;
    createdDateIn?: Array<Date>;
    createdDateNotIn?: Array<Date>;
    updatedDateGreaterThan?: Date;
    updatedDateLessThan?: Date;
    updatedDateGreaterThanOrEqual?: Date;
    updatedDateLessThanOrEqual?: Date;
    updatedDateEquals?: Date;
    updatedDateNotEquals?: Date;
    updatedDateSpecified?: boolean;
    updatedDateIn?: Array<Date>;
    updatedDateNotIn?: Array<Date>;
    expectedResolutionDateGreaterThan?: Date;
    expectedResolutionDateLessThan?: Date;
    expectedResolutionDateGreaterThanOrEqual?: Date;
    expectedResolutionDateLessThanOrEqual?: Date;
    expectedResolutionDateEquals?: Date;
    expectedResolutionDateNotEquals?: Date;
    expectedResolutionDateSpecified?: boolean;
    expectedResolutionDateIn?: Array<Date>;
    expectedResolutionDateNotIn?: Array<Date>;
    resolvedDateGreaterThan?: Date;
    resolvedDateLessThan?: Date;
    resolvedDateGreaterThanOrEqual?: Date;
    resolvedDateLessThanOrEqual?: Date;
    resolvedDateEquals?: Date;
    resolvedDateNotEquals?: Date;
    resolvedDateSpecified?: boolean;
    resolvedDateIn?: Array<Date>;
    resolvedDateNotIn?: Array<Date>;
    aiDuplicateEquals?: boolean;
    aiDuplicateNotEquals?: boolean;
    aiDuplicateSpecified?: boolean;
    aiDuplicateIn?: Array<boolean>;
    aiDuplicateNotIn?: Array<boolean>;
    duplicateScoreGreaterThan?: number;
    duplicateScoreLessThan?: number;
    duplicateScoreGreaterThanOrEqual?: number;
    duplicateScoreLessThanOrEqual?: number;
    duplicateScoreEquals?: number;
    duplicateScoreNotEquals?: number;
    duplicateScoreSpecified?: boolean;
    duplicateScoreIn?: Array<number>;
    duplicateScoreNotIn?: Array<number>;
    aiConfidenceGreaterThan?: number;
    aiConfidenceLessThan?: number;
    aiConfidenceGreaterThanOrEqual?: number;
    aiConfidenceLessThanOrEqual?: number;
    aiConfidenceEquals?: number;
    aiConfidenceNotEquals?: number;
    aiConfidenceSpecified?: boolean;
    aiConfidenceIn?: Array<number>;
    aiConfidenceNotIn?: Array<number>;
    duplicateTicketIdGreaterThan?: number;
    duplicateTicketIdLessThan?: number;
    duplicateTicketIdGreaterThanOrEqual?: number;
    duplicateTicketIdLessThanOrEqual?: number;
    duplicateTicketIdEquals?: number;
    duplicateTicketIdNotEquals?: number;
    duplicateTicketIdSpecified?: boolean;
    duplicateTicketIdIn?: Array<number>;
    duplicateTicketIdNotIn?: Array<number>;
    deletedEquals?: boolean;
    deletedNotEquals?: boolean;
    deletedSpecified?: boolean;
    deletedIn?: Array<boolean>;
    deletedNotIn?: Array<boolean>;
    deletedDateGreaterThan?: Date;
    deletedDateLessThan?: Date;
    deletedDateGreaterThanOrEqual?: Date;
    deletedDateLessThanOrEqual?: Date;
    deletedDateEquals?: Date;
    deletedDateNotEquals?: Date;
    deletedDateSpecified?: boolean;
    deletedDateIn?: Array<Date>;
    deletedDateNotIn?: Array<Date>;
    reportedByIdGreaterThan?: number;
    reportedByIdLessThan?: number;
    reportedByIdGreaterThanOrEqual?: number;
    reportedByIdLessThanOrEqual?: number;
    reportedByIdEquals?: number;
    reportedByIdNotEquals?: number;
    reportedByIdSpecified?: boolean;
    reportedByIdIn?: Array<number>;
    reportedByIdNotIn?: Array<number>;
    locationIdGreaterThan?: number;
    locationIdLessThan?: number;
    locationIdGreaterThanOrEqual?: number;
    locationIdLessThanOrEqual?: number;
    locationIdEquals?: number;
    locationIdNotEquals?: number;
    locationIdSpecified?: boolean;
    locationIdIn?: Array<number>;
    locationIdNotIn?: Array<number>;
    wardIdGreaterThan?: number;
    wardIdLessThan?: number;
    wardIdGreaterThanOrEqual?: number;
    wardIdLessThanOrEqual?: number;
    wardIdEquals?: number;
    wardIdNotEquals?: number;
    wardIdSpecified?: boolean;
    wardIdIn?: Array<number>;
    wardIdNotIn?: Array<number>;
    assignedDepartmentIdGreaterThan?: number;
    assignedDepartmentIdLessThan?: number;
    assignedDepartmentIdGreaterThanOrEqual?: number;
    assignedDepartmentIdLessThanOrEqual?: number;
    assignedDepartmentIdEquals?: number;
    assignedDepartmentIdNotEquals?: number;
    assignedDepartmentIdSpecified?: boolean;
    assignedDepartmentIdIn?: Array<number>;
    assignedDepartmentIdNotIn?: Array<number>;
    distinct?: boolean;
}

export interface CreateTicketRequest {
    ticketDTO: TicketDTO;
}

export interface DeleteTicketRequest {
    id: number;
}

export interface GetAllTicketsRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    titleContains?: string;
    titleDoesNotContain?: string;
    titleEquals?: string;
    titleNotEquals?: string;
    titleSpecified?: boolean;
    titleIn?: Array<string>;
    titleNotIn?: Array<string>;
    statusEquals?: GetAllTicketsStatusEqualsEnum;
    statusNotEquals?: GetAllTicketsStatusNotEqualsEnum;
    statusSpecified?: boolean;
    statusIn?: Array<GetAllTicketsStatusInEnum>;
    statusNotIn?: Array<GetAllTicketsStatusNotInEnum>;
    priorityEquals?: GetAllTicketsPriorityEqualsEnum;
    priorityNotEquals?: GetAllTicketsPriorityNotEqualsEnum;
    prioritySpecified?: boolean;
    priorityIn?: Array<GetAllTicketsPriorityInEnum>;
    priorityNotIn?: Array<GetAllTicketsPriorityNotInEnum>;
    visibilityEquals?: GetAllTicketsVisibilityEqualsEnum;
    visibilityNotEquals?: GetAllTicketsVisibilityNotEqualsEnum;
    visibilitySpecified?: boolean;
    visibilityIn?: Array<GetAllTicketsVisibilityInEnum>;
    visibilityNotIn?: Array<GetAllTicketsVisibilityNotInEnum>;
    categoryEquals?: GetAllTicketsCategoryEqualsEnum;
    categoryNotEquals?: GetAllTicketsCategoryNotEqualsEnum;
    categorySpecified?: boolean;
    categoryIn?: Array<GetAllTicketsCategoryInEnum>;
    categoryNotIn?: Array<GetAllTicketsCategoryNotInEnum>;
    createdDateGreaterThan?: Date;
    createdDateLessThan?: Date;
    createdDateGreaterThanOrEqual?: Date;
    createdDateLessThanOrEqual?: Date;
    createdDateEquals?: Date;
    createdDateNotEquals?: Date;
    createdDateSpecified?: boolean;
    createdDateIn?: Array<Date>;
    createdDateNotIn?: Array<Date>;
    updatedDateGreaterThan?: Date;
    updatedDateLessThan?: Date;
    updatedDateGreaterThanOrEqual?: Date;
    updatedDateLessThanOrEqual?: Date;
    updatedDateEquals?: Date;
    updatedDateNotEquals?: Date;
    updatedDateSpecified?: boolean;
    updatedDateIn?: Array<Date>;
    updatedDateNotIn?: Array<Date>;
    expectedResolutionDateGreaterThan?: Date;
    expectedResolutionDateLessThan?: Date;
    expectedResolutionDateGreaterThanOrEqual?: Date;
    expectedResolutionDateLessThanOrEqual?: Date;
    expectedResolutionDateEquals?: Date;
    expectedResolutionDateNotEquals?: Date;
    expectedResolutionDateSpecified?: boolean;
    expectedResolutionDateIn?: Array<Date>;
    expectedResolutionDateNotIn?: Array<Date>;
    resolvedDateGreaterThan?: Date;
    resolvedDateLessThan?: Date;
    resolvedDateGreaterThanOrEqual?: Date;
    resolvedDateLessThanOrEqual?: Date;
    resolvedDateEquals?: Date;
    resolvedDateNotEquals?: Date;
    resolvedDateSpecified?: boolean;
    resolvedDateIn?: Array<Date>;
    resolvedDateNotIn?: Array<Date>;
    aiDuplicateEquals?: boolean;
    aiDuplicateNotEquals?: boolean;
    aiDuplicateSpecified?: boolean;
    aiDuplicateIn?: Array<boolean>;
    aiDuplicateNotIn?: Array<boolean>;
    duplicateScoreGreaterThan?: number;
    duplicateScoreLessThan?: number;
    duplicateScoreGreaterThanOrEqual?: number;
    duplicateScoreLessThanOrEqual?: number;
    duplicateScoreEquals?: number;
    duplicateScoreNotEquals?: number;
    duplicateScoreSpecified?: boolean;
    duplicateScoreIn?: Array<number>;
    duplicateScoreNotIn?: Array<number>;
    aiConfidenceGreaterThan?: number;
    aiConfidenceLessThan?: number;
    aiConfidenceGreaterThanOrEqual?: number;
    aiConfidenceLessThanOrEqual?: number;
    aiConfidenceEquals?: number;
    aiConfidenceNotEquals?: number;
    aiConfidenceSpecified?: boolean;
    aiConfidenceIn?: Array<number>;
    aiConfidenceNotIn?: Array<number>;
    duplicateTicketIdGreaterThan?: number;
    duplicateTicketIdLessThan?: number;
    duplicateTicketIdGreaterThanOrEqual?: number;
    duplicateTicketIdLessThanOrEqual?: number;
    duplicateTicketIdEquals?: number;
    duplicateTicketIdNotEquals?: number;
    duplicateTicketIdSpecified?: boolean;
    duplicateTicketIdIn?: Array<number>;
    duplicateTicketIdNotIn?: Array<number>;
    deletedEquals?: boolean;
    deletedNotEquals?: boolean;
    deletedSpecified?: boolean;
    deletedIn?: Array<boolean>;
    deletedNotIn?: Array<boolean>;
    deletedDateGreaterThan?: Date;
    deletedDateLessThan?: Date;
    deletedDateGreaterThanOrEqual?: Date;
    deletedDateLessThanOrEqual?: Date;
    deletedDateEquals?: Date;
    deletedDateNotEquals?: Date;
    deletedDateSpecified?: boolean;
    deletedDateIn?: Array<Date>;
    deletedDateNotIn?: Array<Date>;
    reportedByIdGreaterThan?: number;
    reportedByIdLessThan?: number;
    reportedByIdGreaterThanOrEqual?: number;
    reportedByIdLessThanOrEqual?: number;
    reportedByIdEquals?: number;
    reportedByIdNotEquals?: number;
    reportedByIdSpecified?: boolean;
    reportedByIdIn?: Array<number>;
    reportedByIdNotIn?: Array<number>;
    locationIdGreaterThan?: number;
    locationIdLessThan?: number;
    locationIdGreaterThanOrEqual?: number;
    locationIdLessThanOrEqual?: number;
    locationIdEquals?: number;
    locationIdNotEquals?: number;
    locationIdSpecified?: boolean;
    locationIdIn?: Array<number>;
    locationIdNotIn?: Array<number>;
    wardIdGreaterThan?: number;
    wardIdLessThan?: number;
    wardIdGreaterThanOrEqual?: number;
    wardIdLessThanOrEqual?: number;
    wardIdEquals?: number;
    wardIdNotEquals?: number;
    wardIdSpecified?: boolean;
    wardIdIn?: Array<number>;
    wardIdNotIn?: Array<number>;
    assignedDepartmentIdGreaterThan?: number;
    assignedDepartmentIdLessThan?: number;
    assignedDepartmentIdGreaterThanOrEqual?: number;
    assignedDepartmentIdLessThanOrEqual?: number;
    assignedDepartmentIdEquals?: number;
    assignedDepartmentIdNotEquals?: number;
    assignedDepartmentIdSpecified?: boolean;
    assignedDepartmentIdIn?: Array<number>;
    assignedDepartmentIdNotIn?: Array<number>;
    distinct?: boolean;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetTicketRequest {
    id: number;
}

export interface PartialUpdateTicketRequest {
    id: number;
    ticketDTO: TicketDTO;
}

export interface UpdateTicketRequest {
    id: number;
    ticketDTO: TicketDTO;
}

/**
 * 
 */
export class TicketResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for countTickets without sending the request
     */
    async countTicketsRequestOpts(requestParameters: CountTicketsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['titleContains'] != null) {
            queryParameters['title.contains'] = requestParameters['titleContains'];
        }

        if (requestParameters['titleDoesNotContain'] != null) {
            queryParameters['title.doesNotContain'] = requestParameters['titleDoesNotContain'];
        }

        if (requestParameters['titleEquals'] != null) {
            queryParameters['title.equals'] = requestParameters['titleEquals'];
        }

        if (requestParameters['titleNotEquals'] != null) {
            queryParameters['title.notEquals'] = requestParameters['titleNotEquals'];
        }

        if (requestParameters['titleSpecified'] != null) {
            queryParameters['title.specified'] = requestParameters['titleSpecified'];
        }

        if (requestParameters['titleIn'] != null) {
            queryParameters['title.in'] = requestParameters['titleIn'];
        }

        if (requestParameters['titleNotIn'] != null) {
            queryParameters['title.notIn'] = requestParameters['titleNotIn'];
        }

        if (requestParameters['statusEquals'] != null) {
            queryParameters['status.equals'] = requestParameters['statusEquals'];
        }

        if (requestParameters['statusNotEquals'] != null) {
            queryParameters['status.notEquals'] = requestParameters['statusNotEquals'];
        }

        if (requestParameters['statusSpecified'] != null) {
            queryParameters['status.specified'] = requestParameters['statusSpecified'];
        }

        if (requestParameters['statusIn'] != null) {
            queryParameters['status.in'] = requestParameters['statusIn'];
        }

        if (requestParameters['statusNotIn'] != null) {
            queryParameters['status.notIn'] = requestParameters['statusNotIn'];
        }

        if (requestParameters['priorityEquals'] != null) {
            queryParameters['priority.equals'] = requestParameters['priorityEquals'];
        }

        if (requestParameters['priorityNotEquals'] != null) {
            queryParameters['priority.notEquals'] = requestParameters['priorityNotEquals'];
        }

        if (requestParameters['prioritySpecified'] != null) {
            queryParameters['priority.specified'] = requestParameters['prioritySpecified'];
        }

        if (requestParameters['priorityIn'] != null) {
            queryParameters['priority.in'] = requestParameters['priorityIn'];
        }

        if (requestParameters['priorityNotIn'] != null) {
            queryParameters['priority.notIn'] = requestParameters['priorityNotIn'];
        }

        if (requestParameters['visibilityEquals'] != null) {
            queryParameters['visibility.equals'] = requestParameters['visibilityEquals'];
        }

        if (requestParameters['visibilityNotEquals'] != null) {
            queryParameters['visibility.notEquals'] = requestParameters['visibilityNotEquals'];
        }

        if (requestParameters['visibilitySpecified'] != null) {
            queryParameters['visibility.specified'] = requestParameters['visibilitySpecified'];
        }

        if (requestParameters['visibilityIn'] != null) {
            queryParameters['visibility.in'] = requestParameters['visibilityIn'];
        }

        if (requestParameters['visibilityNotIn'] != null) {
            queryParameters['visibility.notIn'] = requestParameters['visibilityNotIn'];
        }

        if (requestParameters['categoryEquals'] != null) {
            queryParameters['category.equals'] = requestParameters['categoryEquals'];
        }

        if (requestParameters['categoryNotEquals'] != null) {
            queryParameters['category.notEquals'] = requestParameters['categoryNotEquals'];
        }

        if (requestParameters['categorySpecified'] != null) {
            queryParameters['category.specified'] = requestParameters['categorySpecified'];
        }

        if (requestParameters['categoryIn'] != null) {
            queryParameters['category.in'] = requestParameters['categoryIn'];
        }

        if (requestParameters['categoryNotIn'] != null) {
            queryParameters['category.notIn'] = requestParameters['categoryNotIn'];
        }

        if (requestParameters['createdDateGreaterThan'] != null) {
            queryParameters['createdDate.greaterThan'] = (requestParameters['createdDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThan'] != null) {
            queryParameters['createdDate.lessThan'] = (requestParameters['createdDateLessThan'] as any).toISOString();
        }

        if (requestParameters['createdDateGreaterThanOrEqual'] != null) {
            queryParameters['createdDate.greaterThanOrEqual'] = (requestParameters['createdDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThanOrEqual'] != null) {
            queryParameters['createdDate.lessThanOrEqual'] = (requestParameters['createdDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateEquals'] != null) {
            queryParameters['createdDate.equals'] = (requestParameters['createdDateEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateNotEquals'] != null) {
            queryParameters['createdDate.notEquals'] = (requestParameters['createdDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateSpecified'] != null) {
            queryParameters['createdDate.specified'] = requestParameters['createdDateSpecified'];
        }

        if (requestParameters['createdDateIn'] != null) {
            queryParameters['createdDate.in'] = requestParameters['createdDateIn'];
        }

        if (requestParameters['createdDateNotIn'] != null) {
            queryParameters['createdDate.notIn'] = requestParameters['createdDateNotIn'];
        }

        if (requestParameters['updatedDateGreaterThan'] != null) {
            queryParameters['updatedDate.greaterThan'] = (requestParameters['updatedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThan'] != null) {
            queryParameters['updatedDate.lessThan'] = (requestParameters['updatedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateGreaterThanOrEqual'] != null) {
            queryParameters['updatedDate.greaterThanOrEqual'] = (requestParameters['updatedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThanOrEqual'] != null) {
            queryParameters['updatedDate.lessThanOrEqual'] = (requestParameters['updatedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateEquals'] != null) {
            queryParameters['updatedDate.equals'] = (requestParameters['updatedDateEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateNotEquals'] != null) {
            queryParameters['updatedDate.notEquals'] = (requestParameters['updatedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateSpecified'] != null) {
            queryParameters['updatedDate.specified'] = requestParameters['updatedDateSpecified'];
        }

        if (requestParameters['updatedDateIn'] != null) {
            queryParameters['updatedDate.in'] = requestParameters['updatedDateIn'];
        }

        if (requestParameters['updatedDateNotIn'] != null) {
            queryParameters['updatedDate.notIn'] = requestParameters['updatedDateNotIn'];
        }

        if (requestParameters['expectedResolutionDateGreaterThan'] != null) {
            queryParameters['expectedResolutionDate.greaterThan'] = (requestParameters['expectedResolutionDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateLessThan'] != null) {
            queryParameters['expectedResolutionDate.lessThan'] = (requestParameters['expectedResolutionDateLessThan'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateGreaterThanOrEqual'] != null) {
            queryParameters['expectedResolutionDate.greaterThanOrEqual'] = (requestParameters['expectedResolutionDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateLessThanOrEqual'] != null) {
            queryParameters['expectedResolutionDate.lessThanOrEqual'] = (requestParameters['expectedResolutionDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateEquals'] != null) {
            queryParameters['expectedResolutionDate.equals'] = (requestParameters['expectedResolutionDateEquals'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateNotEquals'] != null) {
            queryParameters['expectedResolutionDate.notEquals'] = (requestParameters['expectedResolutionDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateSpecified'] != null) {
            queryParameters['expectedResolutionDate.specified'] = requestParameters['expectedResolutionDateSpecified'];
        }

        if (requestParameters['expectedResolutionDateIn'] != null) {
            queryParameters['expectedResolutionDate.in'] = requestParameters['expectedResolutionDateIn'];
        }

        if (requestParameters['expectedResolutionDateNotIn'] != null) {
            queryParameters['expectedResolutionDate.notIn'] = requestParameters['expectedResolutionDateNotIn'];
        }

        if (requestParameters['resolvedDateGreaterThan'] != null) {
            queryParameters['resolvedDate.greaterThan'] = (requestParameters['resolvedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['resolvedDateLessThan'] != null) {
            queryParameters['resolvedDate.lessThan'] = (requestParameters['resolvedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['resolvedDateGreaterThanOrEqual'] != null) {
            queryParameters['resolvedDate.greaterThanOrEqual'] = (requestParameters['resolvedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['resolvedDateLessThanOrEqual'] != null) {
            queryParameters['resolvedDate.lessThanOrEqual'] = (requestParameters['resolvedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['resolvedDateEquals'] != null) {
            queryParameters['resolvedDate.equals'] = (requestParameters['resolvedDateEquals'] as any).toISOString();
        }

        if (requestParameters['resolvedDateNotEquals'] != null) {
            queryParameters['resolvedDate.notEquals'] = (requestParameters['resolvedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['resolvedDateSpecified'] != null) {
            queryParameters['resolvedDate.specified'] = requestParameters['resolvedDateSpecified'];
        }

        if (requestParameters['resolvedDateIn'] != null) {
            queryParameters['resolvedDate.in'] = requestParameters['resolvedDateIn'];
        }

        if (requestParameters['resolvedDateNotIn'] != null) {
            queryParameters['resolvedDate.notIn'] = requestParameters['resolvedDateNotIn'];
        }

        if (requestParameters['aiDuplicateEquals'] != null) {
            queryParameters['aiDuplicate.equals'] = requestParameters['aiDuplicateEquals'];
        }

        if (requestParameters['aiDuplicateNotEquals'] != null) {
            queryParameters['aiDuplicate.notEquals'] = requestParameters['aiDuplicateNotEquals'];
        }

        if (requestParameters['aiDuplicateSpecified'] != null) {
            queryParameters['aiDuplicate.specified'] = requestParameters['aiDuplicateSpecified'];
        }

        if (requestParameters['aiDuplicateIn'] != null) {
            queryParameters['aiDuplicate.in'] = requestParameters['aiDuplicateIn'];
        }

        if (requestParameters['aiDuplicateNotIn'] != null) {
            queryParameters['aiDuplicate.notIn'] = requestParameters['aiDuplicateNotIn'];
        }

        if (requestParameters['duplicateScoreGreaterThan'] != null) {
            queryParameters['duplicateScore.greaterThan'] = requestParameters['duplicateScoreGreaterThan'];
        }

        if (requestParameters['duplicateScoreLessThan'] != null) {
            queryParameters['duplicateScore.lessThan'] = requestParameters['duplicateScoreLessThan'];
        }

        if (requestParameters['duplicateScoreGreaterThanOrEqual'] != null) {
            queryParameters['duplicateScore.greaterThanOrEqual'] = requestParameters['duplicateScoreGreaterThanOrEqual'];
        }

        if (requestParameters['duplicateScoreLessThanOrEqual'] != null) {
            queryParameters['duplicateScore.lessThanOrEqual'] = requestParameters['duplicateScoreLessThanOrEqual'];
        }

        if (requestParameters['duplicateScoreEquals'] != null) {
            queryParameters['duplicateScore.equals'] = requestParameters['duplicateScoreEquals'];
        }

        if (requestParameters['duplicateScoreNotEquals'] != null) {
            queryParameters['duplicateScore.notEquals'] = requestParameters['duplicateScoreNotEquals'];
        }

        if (requestParameters['duplicateScoreSpecified'] != null) {
            queryParameters['duplicateScore.specified'] = requestParameters['duplicateScoreSpecified'];
        }

        if (requestParameters['duplicateScoreIn'] != null) {
            queryParameters['duplicateScore.in'] = requestParameters['duplicateScoreIn'];
        }

        if (requestParameters['duplicateScoreNotIn'] != null) {
            queryParameters['duplicateScore.notIn'] = requestParameters['duplicateScoreNotIn'];
        }

        if (requestParameters['aiConfidenceGreaterThan'] != null) {
            queryParameters['aiConfidence.greaterThan'] = requestParameters['aiConfidenceGreaterThan'];
        }

        if (requestParameters['aiConfidenceLessThan'] != null) {
            queryParameters['aiConfidence.lessThan'] = requestParameters['aiConfidenceLessThan'];
        }

        if (requestParameters['aiConfidenceGreaterThanOrEqual'] != null) {
            queryParameters['aiConfidence.greaterThanOrEqual'] = requestParameters['aiConfidenceGreaterThanOrEqual'];
        }

        if (requestParameters['aiConfidenceLessThanOrEqual'] != null) {
            queryParameters['aiConfidence.lessThanOrEqual'] = requestParameters['aiConfidenceLessThanOrEqual'];
        }

        if (requestParameters['aiConfidenceEquals'] != null) {
            queryParameters['aiConfidence.equals'] = requestParameters['aiConfidenceEquals'];
        }

        if (requestParameters['aiConfidenceNotEquals'] != null) {
            queryParameters['aiConfidence.notEquals'] = requestParameters['aiConfidenceNotEquals'];
        }

        if (requestParameters['aiConfidenceSpecified'] != null) {
            queryParameters['aiConfidence.specified'] = requestParameters['aiConfidenceSpecified'];
        }

        if (requestParameters['aiConfidenceIn'] != null) {
            queryParameters['aiConfidence.in'] = requestParameters['aiConfidenceIn'];
        }

        if (requestParameters['aiConfidenceNotIn'] != null) {
            queryParameters['aiConfidence.notIn'] = requestParameters['aiConfidenceNotIn'];
        }

        if (requestParameters['duplicateTicketIdGreaterThan'] != null) {
            queryParameters['duplicateTicketId.greaterThan'] = requestParameters['duplicateTicketIdGreaterThan'];
        }

        if (requestParameters['duplicateTicketIdLessThan'] != null) {
            queryParameters['duplicateTicketId.lessThan'] = requestParameters['duplicateTicketIdLessThan'];
        }

        if (requestParameters['duplicateTicketIdGreaterThanOrEqual'] != null) {
            queryParameters['duplicateTicketId.greaterThanOrEqual'] = requestParameters['duplicateTicketIdGreaterThanOrEqual'];
        }

        if (requestParameters['duplicateTicketIdLessThanOrEqual'] != null) {
            queryParameters['duplicateTicketId.lessThanOrEqual'] = requestParameters['duplicateTicketIdLessThanOrEqual'];
        }

        if (requestParameters['duplicateTicketIdEquals'] != null) {
            queryParameters['duplicateTicketId.equals'] = requestParameters['duplicateTicketIdEquals'];
        }

        if (requestParameters['duplicateTicketIdNotEquals'] != null) {
            queryParameters['duplicateTicketId.notEquals'] = requestParameters['duplicateTicketIdNotEquals'];
        }

        if (requestParameters['duplicateTicketIdSpecified'] != null) {
            queryParameters['duplicateTicketId.specified'] = requestParameters['duplicateTicketIdSpecified'];
        }

        if (requestParameters['duplicateTicketIdIn'] != null) {
            queryParameters['duplicateTicketId.in'] = requestParameters['duplicateTicketIdIn'];
        }

        if (requestParameters['duplicateTicketIdNotIn'] != null) {
            queryParameters['duplicateTicketId.notIn'] = requestParameters['duplicateTicketIdNotIn'];
        }

        if (requestParameters['deletedEquals'] != null) {
            queryParameters['deleted.equals'] = requestParameters['deletedEquals'];
        }

        if (requestParameters['deletedNotEquals'] != null) {
            queryParameters['deleted.notEquals'] = requestParameters['deletedNotEquals'];
        }

        if (requestParameters['deletedSpecified'] != null) {
            queryParameters['deleted.specified'] = requestParameters['deletedSpecified'];
        }

        if (requestParameters['deletedIn'] != null) {
            queryParameters['deleted.in'] = requestParameters['deletedIn'];
        }

        if (requestParameters['deletedNotIn'] != null) {
            queryParameters['deleted.notIn'] = requestParameters['deletedNotIn'];
        }

        if (requestParameters['deletedDateGreaterThan'] != null) {
            queryParameters['deletedDate.greaterThan'] = (requestParameters['deletedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThan'] != null) {
            queryParameters['deletedDate.lessThan'] = (requestParameters['deletedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateGreaterThanOrEqual'] != null) {
            queryParameters['deletedDate.greaterThanOrEqual'] = (requestParameters['deletedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThanOrEqual'] != null) {
            queryParameters['deletedDate.lessThanOrEqual'] = (requestParameters['deletedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateEquals'] != null) {
            queryParameters['deletedDate.equals'] = (requestParameters['deletedDateEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateNotEquals'] != null) {
            queryParameters['deletedDate.notEquals'] = (requestParameters['deletedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateSpecified'] != null) {
            queryParameters['deletedDate.specified'] = requestParameters['deletedDateSpecified'];
        }

        if (requestParameters['deletedDateIn'] != null) {
            queryParameters['deletedDate.in'] = requestParameters['deletedDateIn'];
        }

        if (requestParameters['deletedDateNotIn'] != null) {
            queryParameters['deletedDate.notIn'] = requestParameters['deletedDateNotIn'];
        }

        if (requestParameters['reportedByIdGreaterThan'] != null) {
            queryParameters['reportedById.greaterThan'] = requestParameters['reportedByIdGreaterThan'];
        }

        if (requestParameters['reportedByIdLessThan'] != null) {
            queryParameters['reportedById.lessThan'] = requestParameters['reportedByIdLessThan'];
        }

        if (requestParameters['reportedByIdGreaterThanOrEqual'] != null) {
            queryParameters['reportedById.greaterThanOrEqual'] = requestParameters['reportedByIdGreaterThanOrEqual'];
        }

        if (requestParameters['reportedByIdLessThanOrEqual'] != null) {
            queryParameters['reportedById.lessThanOrEqual'] = requestParameters['reportedByIdLessThanOrEqual'];
        }

        if (requestParameters['reportedByIdEquals'] != null) {
            queryParameters['reportedById.equals'] = requestParameters['reportedByIdEquals'];
        }

        if (requestParameters['reportedByIdNotEquals'] != null) {
            queryParameters['reportedById.notEquals'] = requestParameters['reportedByIdNotEquals'];
        }

        if (requestParameters['reportedByIdSpecified'] != null) {
            queryParameters['reportedById.specified'] = requestParameters['reportedByIdSpecified'];
        }

        if (requestParameters['reportedByIdIn'] != null) {
            queryParameters['reportedById.in'] = requestParameters['reportedByIdIn'];
        }

        if (requestParameters['reportedByIdNotIn'] != null) {
            queryParameters['reportedById.notIn'] = requestParameters['reportedByIdNotIn'];
        }

        if (requestParameters['locationIdGreaterThan'] != null) {
            queryParameters['locationId.greaterThan'] = requestParameters['locationIdGreaterThan'];
        }

        if (requestParameters['locationIdLessThan'] != null) {
            queryParameters['locationId.lessThan'] = requestParameters['locationIdLessThan'];
        }

        if (requestParameters['locationIdGreaterThanOrEqual'] != null) {
            queryParameters['locationId.greaterThanOrEqual'] = requestParameters['locationIdGreaterThanOrEqual'];
        }

        if (requestParameters['locationIdLessThanOrEqual'] != null) {
            queryParameters['locationId.lessThanOrEqual'] = requestParameters['locationIdLessThanOrEqual'];
        }

        if (requestParameters['locationIdEquals'] != null) {
            queryParameters['locationId.equals'] = requestParameters['locationIdEquals'];
        }

        if (requestParameters['locationIdNotEquals'] != null) {
            queryParameters['locationId.notEquals'] = requestParameters['locationIdNotEquals'];
        }

        if (requestParameters['locationIdSpecified'] != null) {
            queryParameters['locationId.specified'] = requestParameters['locationIdSpecified'];
        }

        if (requestParameters['locationIdIn'] != null) {
            queryParameters['locationId.in'] = requestParameters['locationIdIn'];
        }

        if (requestParameters['locationIdNotIn'] != null) {
            queryParameters['locationId.notIn'] = requestParameters['locationIdNotIn'];
        }

        if (requestParameters['wardIdGreaterThan'] != null) {
            queryParameters['wardId.greaterThan'] = requestParameters['wardIdGreaterThan'];
        }

        if (requestParameters['wardIdLessThan'] != null) {
            queryParameters['wardId.lessThan'] = requestParameters['wardIdLessThan'];
        }

        if (requestParameters['wardIdGreaterThanOrEqual'] != null) {
            queryParameters['wardId.greaterThanOrEqual'] = requestParameters['wardIdGreaterThanOrEqual'];
        }

        if (requestParameters['wardIdLessThanOrEqual'] != null) {
            queryParameters['wardId.lessThanOrEqual'] = requestParameters['wardIdLessThanOrEqual'];
        }

        if (requestParameters['wardIdEquals'] != null) {
            queryParameters['wardId.equals'] = requestParameters['wardIdEquals'];
        }

        if (requestParameters['wardIdNotEquals'] != null) {
            queryParameters['wardId.notEquals'] = requestParameters['wardIdNotEquals'];
        }

        if (requestParameters['wardIdSpecified'] != null) {
            queryParameters['wardId.specified'] = requestParameters['wardIdSpecified'];
        }

        if (requestParameters['wardIdIn'] != null) {
            queryParameters['wardId.in'] = requestParameters['wardIdIn'];
        }

        if (requestParameters['wardIdNotIn'] != null) {
            queryParameters['wardId.notIn'] = requestParameters['wardIdNotIn'];
        }

        if (requestParameters['assignedDepartmentIdGreaterThan'] != null) {
            queryParameters['assignedDepartmentId.greaterThan'] = requestParameters['assignedDepartmentIdGreaterThan'];
        }

        if (requestParameters['assignedDepartmentIdLessThan'] != null) {
            queryParameters['assignedDepartmentId.lessThan'] = requestParameters['assignedDepartmentIdLessThan'];
        }

        if (requestParameters['assignedDepartmentIdGreaterThanOrEqual'] != null) {
            queryParameters['assignedDepartmentId.greaterThanOrEqual'] = requestParameters['assignedDepartmentIdGreaterThanOrEqual'];
        }

        if (requestParameters['assignedDepartmentIdLessThanOrEqual'] != null) {
            queryParameters['assignedDepartmentId.lessThanOrEqual'] = requestParameters['assignedDepartmentIdLessThanOrEqual'];
        }

        if (requestParameters['assignedDepartmentIdEquals'] != null) {
            queryParameters['assignedDepartmentId.equals'] = requestParameters['assignedDepartmentIdEquals'];
        }

        if (requestParameters['assignedDepartmentIdNotEquals'] != null) {
            queryParameters['assignedDepartmentId.notEquals'] = requestParameters['assignedDepartmentIdNotEquals'];
        }

        if (requestParameters['assignedDepartmentIdSpecified'] != null) {
            queryParameters['assignedDepartmentId.specified'] = requestParameters['assignedDepartmentIdSpecified'];
        }

        if (requestParameters['assignedDepartmentIdIn'] != null) {
            queryParameters['assignedDepartmentId.in'] = requestParameters['assignedDepartmentIdIn'];
        }

        if (requestParameters['assignedDepartmentIdNotIn'] != null) {
            queryParameters['assignedDepartmentId.notIn'] = requestParameters['assignedDepartmentIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets/count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async countTicketsRaw(requestParameters: CountTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.countTicketsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async countTickets(requestParameters: CountTicketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTicket without sending the request
     */
    async createTicketRequestOpts(requestParameters: CreateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketDTO',
                'Required parameter "ticketDTO" was null or undefined when calling createTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/tickets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketDTOToJSON(requestParameters['ticketDTO']),
        };
    }

    /**
     */
    async createTicketRaw(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketDTO>> {
        const requestOptions = await this.createTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketDTOFromJSON(jsonValue));
    }

    /**
     */
    async createTicket(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketDTO> {
        const response = await this.createTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTicket without sending the request
     */
    async deleteTicketRequestOpts(requestParameters: DeleteTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteTicketRaw(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteTicket(requestParameters: DeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllTickets without sending the request
     */
    async getAllTicketsRequestOpts(requestParameters: GetAllTicketsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['titleContains'] != null) {
            queryParameters['title.contains'] = requestParameters['titleContains'];
        }

        if (requestParameters['titleDoesNotContain'] != null) {
            queryParameters['title.doesNotContain'] = requestParameters['titleDoesNotContain'];
        }

        if (requestParameters['titleEquals'] != null) {
            queryParameters['title.equals'] = requestParameters['titleEquals'];
        }

        if (requestParameters['titleNotEquals'] != null) {
            queryParameters['title.notEquals'] = requestParameters['titleNotEquals'];
        }

        if (requestParameters['titleSpecified'] != null) {
            queryParameters['title.specified'] = requestParameters['titleSpecified'];
        }

        if (requestParameters['titleIn'] != null) {
            queryParameters['title.in'] = requestParameters['titleIn'];
        }

        if (requestParameters['titleNotIn'] != null) {
            queryParameters['title.notIn'] = requestParameters['titleNotIn'];
        }

        if (requestParameters['statusEquals'] != null) {
            queryParameters['status.equals'] = requestParameters['statusEquals'];
        }

        if (requestParameters['statusNotEquals'] != null) {
            queryParameters['status.notEquals'] = requestParameters['statusNotEquals'];
        }

        if (requestParameters['statusSpecified'] != null) {
            queryParameters['status.specified'] = requestParameters['statusSpecified'];
        }

        if (requestParameters['statusIn'] != null) {
            queryParameters['status.in'] = requestParameters['statusIn'];
        }

        if (requestParameters['statusNotIn'] != null) {
            queryParameters['status.notIn'] = requestParameters['statusNotIn'];
        }

        if (requestParameters['priorityEquals'] != null) {
            queryParameters['priority.equals'] = requestParameters['priorityEquals'];
        }

        if (requestParameters['priorityNotEquals'] != null) {
            queryParameters['priority.notEquals'] = requestParameters['priorityNotEquals'];
        }

        if (requestParameters['prioritySpecified'] != null) {
            queryParameters['priority.specified'] = requestParameters['prioritySpecified'];
        }

        if (requestParameters['priorityIn'] != null) {
            queryParameters['priority.in'] = requestParameters['priorityIn'];
        }

        if (requestParameters['priorityNotIn'] != null) {
            queryParameters['priority.notIn'] = requestParameters['priorityNotIn'];
        }

        if (requestParameters['visibilityEquals'] != null) {
            queryParameters['visibility.equals'] = requestParameters['visibilityEquals'];
        }

        if (requestParameters['visibilityNotEquals'] != null) {
            queryParameters['visibility.notEquals'] = requestParameters['visibilityNotEquals'];
        }

        if (requestParameters['visibilitySpecified'] != null) {
            queryParameters['visibility.specified'] = requestParameters['visibilitySpecified'];
        }

        if (requestParameters['visibilityIn'] != null) {
            queryParameters['visibility.in'] = requestParameters['visibilityIn'];
        }

        if (requestParameters['visibilityNotIn'] != null) {
            queryParameters['visibility.notIn'] = requestParameters['visibilityNotIn'];
        }

        if (requestParameters['categoryEquals'] != null) {
            queryParameters['category.equals'] = requestParameters['categoryEquals'];
        }

        if (requestParameters['categoryNotEquals'] != null) {
            queryParameters['category.notEquals'] = requestParameters['categoryNotEquals'];
        }

        if (requestParameters['categorySpecified'] != null) {
            queryParameters['category.specified'] = requestParameters['categorySpecified'];
        }

        if (requestParameters['categoryIn'] != null) {
            queryParameters['category.in'] = requestParameters['categoryIn'];
        }

        if (requestParameters['categoryNotIn'] != null) {
            queryParameters['category.notIn'] = requestParameters['categoryNotIn'];
        }

        if (requestParameters['createdDateGreaterThan'] != null) {
            queryParameters['createdDate.greaterThan'] = (requestParameters['createdDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThan'] != null) {
            queryParameters['createdDate.lessThan'] = (requestParameters['createdDateLessThan'] as any).toISOString();
        }

        if (requestParameters['createdDateGreaterThanOrEqual'] != null) {
            queryParameters['createdDate.greaterThanOrEqual'] = (requestParameters['createdDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThanOrEqual'] != null) {
            queryParameters['createdDate.lessThanOrEqual'] = (requestParameters['createdDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateEquals'] != null) {
            queryParameters['createdDate.equals'] = (requestParameters['createdDateEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateNotEquals'] != null) {
            queryParameters['createdDate.notEquals'] = (requestParameters['createdDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateSpecified'] != null) {
            queryParameters['createdDate.specified'] = requestParameters['createdDateSpecified'];
        }

        if (requestParameters['createdDateIn'] != null) {
            queryParameters['createdDate.in'] = requestParameters['createdDateIn'];
        }

        if (requestParameters['createdDateNotIn'] != null) {
            queryParameters['createdDate.notIn'] = requestParameters['createdDateNotIn'];
        }

        if (requestParameters['updatedDateGreaterThan'] != null) {
            queryParameters['updatedDate.greaterThan'] = (requestParameters['updatedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThan'] != null) {
            queryParameters['updatedDate.lessThan'] = (requestParameters['updatedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['updatedDateGreaterThanOrEqual'] != null) {
            queryParameters['updatedDate.greaterThanOrEqual'] = (requestParameters['updatedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateLessThanOrEqual'] != null) {
            queryParameters['updatedDate.lessThanOrEqual'] = (requestParameters['updatedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['updatedDateEquals'] != null) {
            queryParameters['updatedDate.equals'] = (requestParameters['updatedDateEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateNotEquals'] != null) {
            queryParameters['updatedDate.notEquals'] = (requestParameters['updatedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['updatedDateSpecified'] != null) {
            queryParameters['updatedDate.specified'] = requestParameters['updatedDateSpecified'];
        }

        if (requestParameters['updatedDateIn'] != null) {
            queryParameters['updatedDate.in'] = requestParameters['updatedDateIn'];
        }

        if (requestParameters['updatedDateNotIn'] != null) {
            queryParameters['updatedDate.notIn'] = requestParameters['updatedDateNotIn'];
        }

        if (requestParameters['expectedResolutionDateGreaterThan'] != null) {
            queryParameters['expectedResolutionDate.greaterThan'] = (requestParameters['expectedResolutionDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateLessThan'] != null) {
            queryParameters['expectedResolutionDate.lessThan'] = (requestParameters['expectedResolutionDateLessThan'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateGreaterThanOrEqual'] != null) {
            queryParameters['expectedResolutionDate.greaterThanOrEqual'] = (requestParameters['expectedResolutionDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateLessThanOrEqual'] != null) {
            queryParameters['expectedResolutionDate.lessThanOrEqual'] = (requestParameters['expectedResolutionDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateEquals'] != null) {
            queryParameters['expectedResolutionDate.equals'] = (requestParameters['expectedResolutionDateEquals'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateNotEquals'] != null) {
            queryParameters['expectedResolutionDate.notEquals'] = (requestParameters['expectedResolutionDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['expectedResolutionDateSpecified'] != null) {
            queryParameters['expectedResolutionDate.specified'] = requestParameters['expectedResolutionDateSpecified'];
        }

        if (requestParameters['expectedResolutionDateIn'] != null) {
            queryParameters['expectedResolutionDate.in'] = requestParameters['expectedResolutionDateIn'];
        }

        if (requestParameters['expectedResolutionDateNotIn'] != null) {
            queryParameters['expectedResolutionDate.notIn'] = requestParameters['expectedResolutionDateNotIn'];
        }

        if (requestParameters['resolvedDateGreaterThan'] != null) {
            queryParameters['resolvedDate.greaterThan'] = (requestParameters['resolvedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['resolvedDateLessThan'] != null) {
            queryParameters['resolvedDate.lessThan'] = (requestParameters['resolvedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['resolvedDateGreaterThanOrEqual'] != null) {
            queryParameters['resolvedDate.greaterThanOrEqual'] = (requestParameters['resolvedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['resolvedDateLessThanOrEqual'] != null) {
            queryParameters['resolvedDate.lessThanOrEqual'] = (requestParameters['resolvedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['resolvedDateEquals'] != null) {
            queryParameters['resolvedDate.equals'] = (requestParameters['resolvedDateEquals'] as any).toISOString();
        }

        if (requestParameters['resolvedDateNotEquals'] != null) {
            queryParameters['resolvedDate.notEquals'] = (requestParameters['resolvedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['resolvedDateSpecified'] != null) {
            queryParameters['resolvedDate.specified'] = requestParameters['resolvedDateSpecified'];
        }

        if (requestParameters['resolvedDateIn'] != null) {
            queryParameters['resolvedDate.in'] = requestParameters['resolvedDateIn'];
        }

        if (requestParameters['resolvedDateNotIn'] != null) {
            queryParameters['resolvedDate.notIn'] = requestParameters['resolvedDateNotIn'];
        }

        if (requestParameters['aiDuplicateEquals'] != null) {
            queryParameters['aiDuplicate.equals'] = requestParameters['aiDuplicateEquals'];
        }

        if (requestParameters['aiDuplicateNotEquals'] != null) {
            queryParameters['aiDuplicate.notEquals'] = requestParameters['aiDuplicateNotEquals'];
        }

        if (requestParameters['aiDuplicateSpecified'] != null) {
            queryParameters['aiDuplicate.specified'] = requestParameters['aiDuplicateSpecified'];
        }

        if (requestParameters['aiDuplicateIn'] != null) {
            queryParameters['aiDuplicate.in'] = requestParameters['aiDuplicateIn'];
        }

        if (requestParameters['aiDuplicateNotIn'] != null) {
            queryParameters['aiDuplicate.notIn'] = requestParameters['aiDuplicateNotIn'];
        }

        if (requestParameters['duplicateScoreGreaterThan'] != null) {
            queryParameters['duplicateScore.greaterThan'] = requestParameters['duplicateScoreGreaterThan'];
        }

        if (requestParameters['duplicateScoreLessThan'] != null) {
            queryParameters['duplicateScore.lessThan'] = requestParameters['duplicateScoreLessThan'];
        }

        if (requestParameters['duplicateScoreGreaterThanOrEqual'] != null) {
            queryParameters['duplicateScore.greaterThanOrEqual'] = requestParameters['duplicateScoreGreaterThanOrEqual'];
        }

        if (requestParameters['duplicateScoreLessThanOrEqual'] != null) {
            queryParameters['duplicateScore.lessThanOrEqual'] = requestParameters['duplicateScoreLessThanOrEqual'];
        }

        if (requestParameters['duplicateScoreEquals'] != null) {
            queryParameters['duplicateScore.equals'] = requestParameters['duplicateScoreEquals'];
        }

        if (requestParameters['duplicateScoreNotEquals'] != null) {
            queryParameters['duplicateScore.notEquals'] = requestParameters['duplicateScoreNotEquals'];
        }

        if (requestParameters['duplicateScoreSpecified'] != null) {
            queryParameters['duplicateScore.specified'] = requestParameters['duplicateScoreSpecified'];
        }

        if (requestParameters['duplicateScoreIn'] != null) {
            queryParameters['duplicateScore.in'] = requestParameters['duplicateScoreIn'];
        }

        if (requestParameters['duplicateScoreNotIn'] != null) {
            queryParameters['duplicateScore.notIn'] = requestParameters['duplicateScoreNotIn'];
        }

        if (requestParameters['aiConfidenceGreaterThan'] != null) {
            queryParameters['aiConfidence.greaterThan'] = requestParameters['aiConfidenceGreaterThan'];
        }

        if (requestParameters['aiConfidenceLessThan'] != null) {
            queryParameters['aiConfidence.lessThan'] = requestParameters['aiConfidenceLessThan'];
        }

        if (requestParameters['aiConfidenceGreaterThanOrEqual'] != null) {
            queryParameters['aiConfidence.greaterThanOrEqual'] = requestParameters['aiConfidenceGreaterThanOrEqual'];
        }

        if (requestParameters['aiConfidenceLessThanOrEqual'] != null) {
            queryParameters['aiConfidence.lessThanOrEqual'] = requestParameters['aiConfidenceLessThanOrEqual'];
        }

        if (requestParameters['aiConfidenceEquals'] != null) {
            queryParameters['aiConfidence.equals'] = requestParameters['aiConfidenceEquals'];
        }

        if (requestParameters['aiConfidenceNotEquals'] != null) {
            queryParameters['aiConfidence.notEquals'] = requestParameters['aiConfidenceNotEquals'];
        }

        if (requestParameters['aiConfidenceSpecified'] != null) {
            queryParameters['aiConfidence.specified'] = requestParameters['aiConfidenceSpecified'];
        }

        if (requestParameters['aiConfidenceIn'] != null) {
            queryParameters['aiConfidence.in'] = requestParameters['aiConfidenceIn'];
        }

        if (requestParameters['aiConfidenceNotIn'] != null) {
            queryParameters['aiConfidence.notIn'] = requestParameters['aiConfidenceNotIn'];
        }

        if (requestParameters['duplicateTicketIdGreaterThan'] != null) {
            queryParameters['duplicateTicketId.greaterThan'] = requestParameters['duplicateTicketIdGreaterThan'];
        }

        if (requestParameters['duplicateTicketIdLessThan'] != null) {
            queryParameters['duplicateTicketId.lessThan'] = requestParameters['duplicateTicketIdLessThan'];
        }

        if (requestParameters['duplicateTicketIdGreaterThanOrEqual'] != null) {
            queryParameters['duplicateTicketId.greaterThanOrEqual'] = requestParameters['duplicateTicketIdGreaterThanOrEqual'];
        }

        if (requestParameters['duplicateTicketIdLessThanOrEqual'] != null) {
            queryParameters['duplicateTicketId.lessThanOrEqual'] = requestParameters['duplicateTicketIdLessThanOrEqual'];
        }

        if (requestParameters['duplicateTicketIdEquals'] != null) {
            queryParameters['duplicateTicketId.equals'] = requestParameters['duplicateTicketIdEquals'];
        }

        if (requestParameters['duplicateTicketIdNotEquals'] != null) {
            queryParameters['duplicateTicketId.notEquals'] = requestParameters['duplicateTicketIdNotEquals'];
        }

        if (requestParameters['duplicateTicketIdSpecified'] != null) {
            queryParameters['duplicateTicketId.specified'] = requestParameters['duplicateTicketIdSpecified'];
        }

        if (requestParameters['duplicateTicketIdIn'] != null) {
            queryParameters['duplicateTicketId.in'] = requestParameters['duplicateTicketIdIn'];
        }

        if (requestParameters['duplicateTicketIdNotIn'] != null) {
            queryParameters['duplicateTicketId.notIn'] = requestParameters['duplicateTicketIdNotIn'];
        }

        if (requestParameters['deletedEquals'] != null) {
            queryParameters['deleted.equals'] = requestParameters['deletedEquals'];
        }

        if (requestParameters['deletedNotEquals'] != null) {
            queryParameters['deleted.notEquals'] = requestParameters['deletedNotEquals'];
        }

        if (requestParameters['deletedSpecified'] != null) {
            queryParameters['deleted.specified'] = requestParameters['deletedSpecified'];
        }

        if (requestParameters['deletedIn'] != null) {
            queryParameters['deleted.in'] = requestParameters['deletedIn'];
        }

        if (requestParameters['deletedNotIn'] != null) {
            queryParameters['deleted.notIn'] = requestParameters['deletedNotIn'];
        }

        if (requestParameters['deletedDateGreaterThan'] != null) {
            queryParameters['deletedDate.greaterThan'] = (requestParameters['deletedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThan'] != null) {
            queryParameters['deletedDate.lessThan'] = (requestParameters['deletedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateGreaterThanOrEqual'] != null) {
            queryParameters['deletedDate.greaterThanOrEqual'] = (requestParameters['deletedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThanOrEqual'] != null) {
            queryParameters['deletedDate.lessThanOrEqual'] = (requestParameters['deletedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateEquals'] != null) {
            queryParameters['deletedDate.equals'] = (requestParameters['deletedDateEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateNotEquals'] != null) {
            queryParameters['deletedDate.notEquals'] = (requestParameters['deletedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateSpecified'] != null) {
            queryParameters['deletedDate.specified'] = requestParameters['deletedDateSpecified'];
        }

        if (requestParameters['deletedDateIn'] != null) {
            queryParameters['deletedDate.in'] = requestParameters['deletedDateIn'];
        }

        if (requestParameters['deletedDateNotIn'] != null) {
            queryParameters['deletedDate.notIn'] = requestParameters['deletedDateNotIn'];
        }

        if (requestParameters['reportedByIdGreaterThan'] != null) {
            queryParameters['reportedById.greaterThan'] = requestParameters['reportedByIdGreaterThan'];
        }

        if (requestParameters['reportedByIdLessThan'] != null) {
            queryParameters['reportedById.lessThan'] = requestParameters['reportedByIdLessThan'];
        }

        if (requestParameters['reportedByIdGreaterThanOrEqual'] != null) {
            queryParameters['reportedById.greaterThanOrEqual'] = requestParameters['reportedByIdGreaterThanOrEqual'];
        }

        if (requestParameters['reportedByIdLessThanOrEqual'] != null) {
            queryParameters['reportedById.lessThanOrEqual'] = requestParameters['reportedByIdLessThanOrEqual'];
        }

        if (requestParameters['reportedByIdEquals'] != null) {
            queryParameters['reportedById.equals'] = requestParameters['reportedByIdEquals'];
        }

        if (requestParameters['reportedByIdNotEquals'] != null) {
            queryParameters['reportedById.notEquals'] = requestParameters['reportedByIdNotEquals'];
        }

        if (requestParameters['reportedByIdSpecified'] != null) {
            queryParameters['reportedById.specified'] = requestParameters['reportedByIdSpecified'];
        }

        if (requestParameters['reportedByIdIn'] != null) {
            queryParameters['reportedById.in'] = requestParameters['reportedByIdIn'];
        }

        if (requestParameters['reportedByIdNotIn'] != null) {
            queryParameters['reportedById.notIn'] = requestParameters['reportedByIdNotIn'];
        }

        if (requestParameters['locationIdGreaterThan'] != null) {
            queryParameters['locationId.greaterThan'] = requestParameters['locationIdGreaterThan'];
        }

        if (requestParameters['locationIdLessThan'] != null) {
            queryParameters['locationId.lessThan'] = requestParameters['locationIdLessThan'];
        }

        if (requestParameters['locationIdGreaterThanOrEqual'] != null) {
            queryParameters['locationId.greaterThanOrEqual'] = requestParameters['locationIdGreaterThanOrEqual'];
        }

        if (requestParameters['locationIdLessThanOrEqual'] != null) {
            queryParameters['locationId.lessThanOrEqual'] = requestParameters['locationIdLessThanOrEqual'];
        }

        if (requestParameters['locationIdEquals'] != null) {
            queryParameters['locationId.equals'] = requestParameters['locationIdEquals'];
        }

        if (requestParameters['locationIdNotEquals'] != null) {
            queryParameters['locationId.notEquals'] = requestParameters['locationIdNotEquals'];
        }

        if (requestParameters['locationIdSpecified'] != null) {
            queryParameters['locationId.specified'] = requestParameters['locationIdSpecified'];
        }

        if (requestParameters['locationIdIn'] != null) {
            queryParameters['locationId.in'] = requestParameters['locationIdIn'];
        }

        if (requestParameters['locationIdNotIn'] != null) {
            queryParameters['locationId.notIn'] = requestParameters['locationIdNotIn'];
        }

        if (requestParameters['wardIdGreaterThan'] != null) {
            queryParameters['wardId.greaterThan'] = requestParameters['wardIdGreaterThan'];
        }

        if (requestParameters['wardIdLessThan'] != null) {
            queryParameters['wardId.lessThan'] = requestParameters['wardIdLessThan'];
        }

        if (requestParameters['wardIdGreaterThanOrEqual'] != null) {
            queryParameters['wardId.greaterThanOrEqual'] = requestParameters['wardIdGreaterThanOrEqual'];
        }

        if (requestParameters['wardIdLessThanOrEqual'] != null) {
            queryParameters['wardId.lessThanOrEqual'] = requestParameters['wardIdLessThanOrEqual'];
        }

        if (requestParameters['wardIdEquals'] != null) {
            queryParameters['wardId.equals'] = requestParameters['wardIdEquals'];
        }

        if (requestParameters['wardIdNotEquals'] != null) {
            queryParameters['wardId.notEquals'] = requestParameters['wardIdNotEquals'];
        }

        if (requestParameters['wardIdSpecified'] != null) {
            queryParameters['wardId.specified'] = requestParameters['wardIdSpecified'];
        }

        if (requestParameters['wardIdIn'] != null) {
            queryParameters['wardId.in'] = requestParameters['wardIdIn'];
        }

        if (requestParameters['wardIdNotIn'] != null) {
            queryParameters['wardId.notIn'] = requestParameters['wardIdNotIn'];
        }

        if (requestParameters['assignedDepartmentIdGreaterThan'] != null) {
            queryParameters['assignedDepartmentId.greaterThan'] = requestParameters['assignedDepartmentIdGreaterThan'];
        }

        if (requestParameters['assignedDepartmentIdLessThan'] != null) {
            queryParameters['assignedDepartmentId.lessThan'] = requestParameters['assignedDepartmentIdLessThan'];
        }

        if (requestParameters['assignedDepartmentIdGreaterThanOrEqual'] != null) {
            queryParameters['assignedDepartmentId.greaterThanOrEqual'] = requestParameters['assignedDepartmentIdGreaterThanOrEqual'];
        }

        if (requestParameters['assignedDepartmentIdLessThanOrEqual'] != null) {
            queryParameters['assignedDepartmentId.lessThanOrEqual'] = requestParameters['assignedDepartmentIdLessThanOrEqual'];
        }

        if (requestParameters['assignedDepartmentIdEquals'] != null) {
            queryParameters['assignedDepartmentId.equals'] = requestParameters['assignedDepartmentIdEquals'];
        }

        if (requestParameters['assignedDepartmentIdNotEquals'] != null) {
            queryParameters['assignedDepartmentId.notEquals'] = requestParameters['assignedDepartmentIdNotEquals'];
        }

        if (requestParameters['assignedDepartmentIdSpecified'] != null) {
            queryParameters['assignedDepartmentId.specified'] = requestParameters['assignedDepartmentIdSpecified'];
        }

        if (requestParameters['assignedDepartmentIdIn'] != null) {
            queryParameters['assignedDepartmentId.in'] = requestParameters['assignedDepartmentIdIn'];
        }

        if (requestParameters['assignedDepartmentIdNotIn'] != null) {
            queryParameters['assignedDepartmentId.notIn'] = requestParameters['assignedDepartmentIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllTicketsRaw(requestParameters: GetAllTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketDTO>>> {
        const requestOptions = await this.getAllTicketsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketDTOFromJSON));
    }

    /**
     */
    async getAllTickets(requestParameters: GetAllTicketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketDTO>> {
        const response = await this.getAllTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTicket without sending the request
     */
    async getTicketRequestOpts(requestParameters: GetTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTicketRaw(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketDTO>> {
        const requestOptions = await this.getTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketDTOFromJSON(jsonValue));
    }

    /**
     */
    async getTicket(requestParameters: GetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketDTO> {
        const response = await this.getTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateTicket without sending the request
     */
    async partialUpdateTicketRequestOpts(requestParameters: PartialUpdateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdateTicket().'
            );
        }

        if (requestParameters['ticketDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketDTO',
                'Required parameter "ticketDTO" was null or undefined when calling partialUpdateTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TicketDTOToJSON(requestParameters['ticketDTO']),
        };
    }

    /**
     */
    async partialUpdateTicketRaw(requestParameters: PartialUpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketDTO>> {
        const requestOptions = await this.partialUpdateTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketDTOFromJSON(jsonValue));
    }

    /**
     */
    async partialUpdateTicket(requestParameters: PartialUpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketDTO> {
        const response = await this.partialUpdateTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTicket without sending the request
     */
    async updateTicketRequestOpts(requestParameters: UpdateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTicket().'
            );
        }

        if (requestParameters['ticketDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketDTO',
                'Required parameter "ticketDTO" was null or undefined when calling updateTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/tickets/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TicketDTOToJSON(requestParameters['ticketDTO']),
        };
    }

    /**
     */
    async updateTicketRaw(requestParameters: UpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketDTO>> {
        const requestOptions = await this.updateTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateTicket(requestParameters: UpdateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketDTO> {
        const response = await this.updateTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CountTicketsStatusEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketsStatusEqualsEnum = typeof CountTicketsStatusEqualsEnum[keyof typeof CountTicketsStatusEqualsEnum];
/**
 * @export
 */
export const CountTicketsStatusNotEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketsStatusNotEqualsEnum = typeof CountTicketsStatusNotEqualsEnum[keyof typeof CountTicketsStatusNotEqualsEnum];
/**
 * @export
 */
export const CountTicketsStatusInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketsStatusInEnum = typeof CountTicketsStatusInEnum[keyof typeof CountTicketsStatusInEnum];
/**
 * @export
 */
export const CountTicketsStatusNotInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketsStatusNotInEnum = typeof CountTicketsStatusNotInEnum[keyof typeof CountTicketsStatusNotInEnum];
/**
 * @export
 */
export const CountTicketsPriorityEqualsEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type CountTicketsPriorityEqualsEnum = typeof CountTicketsPriorityEqualsEnum[keyof typeof CountTicketsPriorityEqualsEnum];
/**
 * @export
 */
export const CountTicketsPriorityNotEqualsEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type CountTicketsPriorityNotEqualsEnum = typeof CountTicketsPriorityNotEqualsEnum[keyof typeof CountTicketsPriorityNotEqualsEnum];
/**
 * @export
 */
export const CountTicketsPriorityInEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type CountTicketsPriorityInEnum = typeof CountTicketsPriorityInEnum[keyof typeof CountTicketsPriorityInEnum];
/**
 * @export
 */
export const CountTicketsPriorityNotInEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type CountTicketsPriorityNotInEnum = typeof CountTicketsPriorityNotInEnum[keyof typeof CountTicketsPriorityNotInEnum];
/**
 * @export
 */
export const CountTicketsVisibilityEqualsEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type CountTicketsVisibilityEqualsEnum = typeof CountTicketsVisibilityEqualsEnum[keyof typeof CountTicketsVisibilityEqualsEnum];
/**
 * @export
 */
export const CountTicketsVisibilityNotEqualsEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type CountTicketsVisibilityNotEqualsEnum = typeof CountTicketsVisibilityNotEqualsEnum[keyof typeof CountTicketsVisibilityNotEqualsEnum];
/**
 * @export
 */
export const CountTicketsVisibilityInEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type CountTicketsVisibilityInEnum = typeof CountTicketsVisibilityInEnum[keyof typeof CountTicketsVisibilityInEnum];
/**
 * @export
 */
export const CountTicketsVisibilityNotInEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type CountTicketsVisibilityNotInEnum = typeof CountTicketsVisibilityNotInEnum[keyof typeof CountTicketsVisibilityNotInEnum];
/**
 * @export
 */
export const CountTicketsCategoryEqualsEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type CountTicketsCategoryEqualsEnum = typeof CountTicketsCategoryEqualsEnum[keyof typeof CountTicketsCategoryEqualsEnum];
/**
 * @export
 */
export const CountTicketsCategoryNotEqualsEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type CountTicketsCategoryNotEqualsEnum = typeof CountTicketsCategoryNotEqualsEnum[keyof typeof CountTicketsCategoryNotEqualsEnum];
/**
 * @export
 */
export const CountTicketsCategoryInEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type CountTicketsCategoryInEnum = typeof CountTicketsCategoryInEnum[keyof typeof CountTicketsCategoryInEnum];
/**
 * @export
 */
export const CountTicketsCategoryNotInEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type CountTicketsCategoryNotInEnum = typeof CountTicketsCategoryNotInEnum[keyof typeof CountTicketsCategoryNotInEnum];
/**
 * @export
 */
export const GetAllTicketsStatusEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketsStatusEqualsEnum = typeof GetAllTicketsStatusEqualsEnum[keyof typeof GetAllTicketsStatusEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsStatusNotEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketsStatusNotEqualsEnum = typeof GetAllTicketsStatusNotEqualsEnum[keyof typeof GetAllTicketsStatusNotEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsStatusInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketsStatusInEnum = typeof GetAllTicketsStatusInEnum[keyof typeof GetAllTicketsStatusInEnum];
/**
 * @export
 */
export const GetAllTicketsStatusNotInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketsStatusNotInEnum = typeof GetAllTicketsStatusNotInEnum[keyof typeof GetAllTicketsStatusNotInEnum];
/**
 * @export
 */
export const GetAllTicketsPriorityEqualsEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type GetAllTicketsPriorityEqualsEnum = typeof GetAllTicketsPriorityEqualsEnum[keyof typeof GetAllTicketsPriorityEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsPriorityNotEqualsEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type GetAllTicketsPriorityNotEqualsEnum = typeof GetAllTicketsPriorityNotEqualsEnum[keyof typeof GetAllTicketsPriorityNotEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsPriorityInEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type GetAllTicketsPriorityInEnum = typeof GetAllTicketsPriorityInEnum[keyof typeof GetAllTicketsPriorityInEnum];
/**
 * @export
 */
export const GetAllTicketsPriorityNotInEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Urgent: 'URGENT'
} as const;
export type GetAllTicketsPriorityNotInEnum = typeof GetAllTicketsPriorityNotInEnum[keyof typeof GetAllTicketsPriorityNotInEnum];
/**
 * @export
 */
export const GetAllTicketsVisibilityEqualsEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type GetAllTicketsVisibilityEqualsEnum = typeof GetAllTicketsVisibilityEqualsEnum[keyof typeof GetAllTicketsVisibilityEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsVisibilityNotEqualsEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type GetAllTicketsVisibilityNotEqualsEnum = typeof GetAllTicketsVisibilityNotEqualsEnum[keyof typeof GetAllTicketsVisibilityNotEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsVisibilityInEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type GetAllTicketsVisibilityInEnum = typeof GetAllTicketsVisibilityInEnum[keyof typeof GetAllTicketsVisibilityInEnum];
/**
 * @export
 */
export const GetAllTicketsVisibilityNotInEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type GetAllTicketsVisibilityNotInEnum = typeof GetAllTicketsVisibilityNotInEnum[keyof typeof GetAllTicketsVisibilityNotInEnum];
/**
 * @export
 */
export const GetAllTicketsCategoryEqualsEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type GetAllTicketsCategoryEqualsEnum = typeof GetAllTicketsCategoryEqualsEnum[keyof typeof GetAllTicketsCategoryEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsCategoryNotEqualsEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type GetAllTicketsCategoryNotEqualsEnum = typeof GetAllTicketsCategoryNotEqualsEnum[keyof typeof GetAllTicketsCategoryNotEqualsEnum];
/**
 * @export
 */
export const GetAllTicketsCategoryInEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type GetAllTicketsCategoryInEnum = typeof GetAllTicketsCategoryInEnum[keyof typeof GetAllTicketsCategoryInEnum];
/**
 * @export
 */
export const GetAllTicketsCategoryNotInEnum = {
    RoadDamage: 'ROAD_DAMAGE',
    WaterSupply: 'WATER_SUPPLY',
    StreetLight: 'STREET_LIGHT',
    Drainage: 'DRAINAGE',
    Garbage: 'GARBAGE',
    Electricity: 'ELECTRICITY',
    Tree: 'TREE',
    Other: 'OTHER'
} as const;
export type GetAllTicketsCategoryNotInEnum = typeof GetAllTicketsCategoryNotInEnum[keyof typeof GetAllTicketsCategoryNotInEnum];
