/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TicketVoteDTO,
} from '../models/index';
import {
    TicketVoteDTOFromJSON,
    TicketVoteDTOToJSON,
} from '../models/index';

export interface CountTicketVotesRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    voteTypeEquals?: CountTicketVotesVoteTypeEqualsEnum;
    voteTypeNotEquals?: CountTicketVotesVoteTypeNotEqualsEnum;
    voteTypeSpecified?: boolean;
    voteTypeIn?: Array<CountTicketVotesVoteTypeInEnum>;
    voteTypeNotIn?: Array<CountTicketVotesVoteTypeNotInEnum>;
    createdDateGreaterThan?: Date;
    createdDateLessThan?: Date;
    createdDateGreaterThanOrEqual?: Date;
    createdDateLessThanOrEqual?: Date;
    createdDateEquals?: Date;
    createdDateNotEquals?: Date;
    createdDateSpecified?: boolean;
    createdDateIn?: Array<Date>;
    createdDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    userIdGreaterThan?: number;
    userIdLessThan?: number;
    userIdGreaterThanOrEqual?: number;
    userIdLessThanOrEqual?: number;
    userIdEquals?: number;
    userIdNotEquals?: number;
    userIdSpecified?: boolean;
    userIdIn?: Array<number>;
    userIdNotIn?: Array<number>;
    distinct?: boolean;
}

export interface CreateTicketVoteRequest {
    ticketVoteDTO: TicketVoteDTO;
}

export interface DeleteTicketVoteRequest {
    id: number;
}

export interface GetAllTicketVotesRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    voteTypeEquals?: GetAllTicketVotesVoteTypeEqualsEnum;
    voteTypeNotEquals?: GetAllTicketVotesVoteTypeNotEqualsEnum;
    voteTypeSpecified?: boolean;
    voteTypeIn?: Array<GetAllTicketVotesVoteTypeInEnum>;
    voteTypeNotIn?: Array<GetAllTicketVotesVoteTypeNotInEnum>;
    createdDateGreaterThan?: Date;
    createdDateLessThan?: Date;
    createdDateGreaterThanOrEqual?: Date;
    createdDateLessThanOrEqual?: Date;
    createdDateEquals?: Date;
    createdDateNotEquals?: Date;
    createdDateSpecified?: boolean;
    createdDateIn?: Array<Date>;
    createdDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    userIdGreaterThan?: number;
    userIdLessThan?: number;
    userIdGreaterThanOrEqual?: number;
    userIdLessThanOrEqual?: number;
    userIdEquals?: number;
    userIdNotEquals?: number;
    userIdSpecified?: boolean;
    userIdIn?: Array<number>;
    userIdNotIn?: Array<number>;
    distinct?: boolean;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetTicketVoteRequest {
    id: number;
}

export interface PartialUpdateTicketVoteRequest {
    id: number;
    ticketVoteDTO: TicketVoteDTO;
}

export interface UpdateTicketVoteRequest {
    id: number;
    ticketVoteDTO: TicketVoteDTO;
}

/**
 * 
 */
export class TicketVoteResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for countTicketVotes without sending the request
     */
    async countTicketVotesRequestOpts(requestParameters: CountTicketVotesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['voteTypeEquals'] != null) {
            queryParameters['voteType.equals'] = requestParameters['voteTypeEquals'];
        }

        if (requestParameters['voteTypeNotEquals'] != null) {
            queryParameters['voteType.notEquals'] = requestParameters['voteTypeNotEquals'];
        }

        if (requestParameters['voteTypeSpecified'] != null) {
            queryParameters['voteType.specified'] = requestParameters['voteTypeSpecified'];
        }

        if (requestParameters['voteTypeIn'] != null) {
            queryParameters['voteType.in'] = requestParameters['voteTypeIn'];
        }

        if (requestParameters['voteTypeNotIn'] != null) {
            queryParameters['voteType.notIn'] = requestParameters['voteTypeNotIn'];
        }

        if (requestParameters['createdDateGreaterThan'] != null) {
            queryParameters['createdDate.greaterThan'] = (requestParameters['createdDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThan'] != null) {
            queryParameters['createdDate.lessThan'] = (requestParameters['createdDateLessThan'] as any).toISOString();
        }

        if (requestParameters['createdDateGreaterThanOrEqual'] != null) {
            queryParameters['createdDate.greaterThanOrEqual'] = (requestParameters['createdDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThanOrEqual'] != null) {
            queryParameters['createdDate.lessThanOrEqual'] = (requestParameters['createdDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateEquals'] != null) {
            queryParameters['createdDate.equals'] = (requestParameters['createdDateEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateNotEquals'] != null) {
            queryParameters['createdDate.notEquals'] = (requestParameters['createdDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateSpecified'] != null) {
            queryParameters['createdDate.specified'] = requestParameters['createdDateSpecified'];
        }

        if (requestParameters['createdDateIn'] != null) {
            queryParameters['createdDate.in'] = requestParameters['createdDateIn'];
        }

        if (requestParameters['createdDateNotIn'] != null) {
            queryParameters['createdDate.notIn'] = requestParameters['createdDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['userIdGreaterThan'] != null) {
            queryParameters['userId.greaterThan'] = requestParameters['userIdGreaterThan'];
        }

        if (requestParameters['userIdLessThan'] != null) {
            queryParameters['userId.lessThan'] = requestParameters['userIdLessThan'];
        }

        if (requestParameters['userIdGreaterThanOrEqual'] != null) {
            queryParameters['userId.greaterThanOrEqual'] = requestParameters['userIdGreaterThanOrEqual'];
        }

        if (requestParameters['userIdLessThanOrEqual'] != null) {
            queryParameters['userId.lessThanOrEqual'] = requestParameters['userIdLessThanOrEqual'];
        }

        if (requestParameters['userIdEquals'] != null) {
            queryParameters['userId.equals'] = requestParameters['userIdEquals'];
        }

        if (requestParameters['userIdNotEquals'] != null) {
            queryParameters['userId.notEquals'] = requestParameters['userIdNotEquals'];
        }

        if (requestParameters['userIdSpecified'] != null) {
            queryParameters['userId.specified'] = requestParameters['userIdSpecified'];
        }

        if (requestParameters['userIdIn'] != null) {
            queryParameters['userId.in'] = requestParameters['userIdIn'];
        }

        if (requestParameters['userIdNotIn'] != null) {
            queryParameters['userId.notIn'] = requestParameters['userIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-votes/count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async countTicketVotesRaw(requestParameters: CountTicketVotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.countTicketVotesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async countTicketVotes(requestParameters: CountTicketVotesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countTicketVotesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTicketVote without sending the request
     */
    async createTicketVoteRequestOpts(requestParameters: CreateTicketVoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketVoteDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketVoteDTO',
                'Required parameter "ticketVoteDTO" was null or undefined when calling createTicketVote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ticket-votes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketVoteDTOToJSON(requestParameters['ticketVoteDTO']),
        };
    }

    /**
     */
    async createTicketVoteRaw(requestParameters: CreateTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketVoteDTO>> {
        const requestOptions = await this.createTicketVoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketVoteDTOFromJSON(jsonValue));
    }

    /**
     */
    async createTicketVote(requestParameters: CreateTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketVoteDTO> {
        const response = await this.createTicketVoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTicketVote without sending the request
     */
    async deleteTicketVoteRequestOpts(requestParameters: DeleteTicketVoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTicketVote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-votes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteTicketVoteRaw(requestParameters: DeleteTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTicketVoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteTicketVote(requestParameters: DeleteTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketVoteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllTicketVotes without sending the request
     */
    async getAllTicketVotesRequestOpts(requestParameters: GetAllTicketVotesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['voteTypeEquals'] != null) {
            queryParameters['voteType.equals'] = requestParameters['voteTypeEquals'];
        }

        if (requestParameters['voteTypeNotEquals'] != null) {
            queryParameters['voteType.notEquals'] = requestParameters['voteTypeNotEquals'];
        }

        if (requestParameters['voteTypeSpecified'] != null) {
            queryParameters['voteType.specified'] = requestParameters['voteTypeSpecified'];
        }

        if (requestParameters['voteTypeIn'] != null) {
            queryParameters['voteType.in'] = requestParameters['voteTypeIn'];
        }

        if (requestParameters['voteTypeNotIn'] != null) {
            queryParameters['voteType.notIn'] = requestParameters['voteTypeNotIn'];
        }

        if (requestParameters['createdDateGreaterThan'] != null) {
            queryParameters['createdDate.greaterThan'] = (requestParameters['createdDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThan'] != null) {
            queryParameters['createdDate.lessThan'] = (requestParameters['createdDateLessThan'] as any).toISOString();
        }

        if (requestParameters['createdDateGreaterThanOrEqual'] != null) {
            queryParameters['createdDate.greaterThanOrEqual'] = (requestParameters['createdDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateLessThanOrEqual'] != null) {
            queryParameters['createdDate.lessThanOrEqual'] = (requestParameters['createdDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['createdDateEquals'] != null) {
            queryParameters['createdDate.equals'] = (requestParameters['createdDateEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateNotEquals'] != null) {
            queryParameters['createdDate.notEquals'] = (requestParameters['createdDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['createdDateSpecified'] != null) {
            queryParameters['createdDate.specified'] = requestParameters['createdDateSpecified'];
        }

        if (requestParameters['createdDateIn'] != null) {
            queryParameters['createdDate.in'] = requestParameters['createdDateIn'];
        }

        if (requestParameters['createdDateNotIn'] != null) {
            queryParameters['createdDate.notIn'] = requestParameters['createdDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['userIdGreaterThan'] != null) {
            queryParameters['userId.greaterThan'] = requestParameters['userIdGreaterThan'];
        }

        if (requestParameters['userIdLessThan'] != null) {
            queryParameters['userId.lessThan'] = requestParameters['userIdLessThan'];
        }

        if (requestParameters['userIdGreaterThanOrEqual'] != null) {
            queryParameters['userId.greaterThanOrEqual'] = requestParameters['userIdGreaterThanOrEqual'];
        }

        if (requestParameters['userIdLessThanOrEqual'] != null) {
            queryParameters['userId.lessThanOrEqual'] = requestParameters['userIdLessThanOrEqual'];
        }

        if (requestParameters['userIdEquals'] != null) {
            queryParameters['userId.equals'] = requestParameters['userIdEquals'];
        }

        if (requestParameters['userIdNotEquals'] != null) {
            queryParameters['userId.notEquals'] = requestParameters['userIdNotEquals'];
        }

        if (requestParameters['userIdSpecified'] != null) {
            queryParameters['userId.specified'] = requestParameters['userIdSpecified'];
        }

        if (requestParameters['userIdIn'] != null) {
            queryParameters['userId.in'] = requestParameters['userIdIn'];
        }

        if (requestParameters['userIdNotIn'] != null) {
            queryParameters['userId.notIn'] = requestParameters['userIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-votes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllTicketVotesRaw(requestParameters: GetAllTicketVotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketVoteDTO>>> {
        const requestOptions = await this.getAllTicketVotesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketVoteDTOFromJSON));
    }

    /**
     */
    async getAllTicketVotes(requestParameters: GetAllTicketVotesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketVoteDTO>> {
        const response = await this.getAllTicketVotesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTicketVote without sending the request
     */
    async getTicketVoteRequestOpts(requestParameters: GetTicketVoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTicketVote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-votes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTicketVoteRaw(requestParameters: GetTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketVoteDTO>> {
        const requestOptions = await this.getTicketVoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketVoteDTOFromJSON(jsonValue));
    }

    /**
     */
    async getTicketVote(requestParameters: GetTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketVoteDTO> {
        const response = await this.getTicketVoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateTicketVote without sending the request
     */
    async partialUpdateTicketVoteRequestOpts(requestParameters: PartialUpdateTicketVoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdateTicketVote().'
            );
        }

        if (requestParameters['ticketVoteDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketVoteDTO',
                'Required parameter "ticketVoteDTO" was null or undefined when calling partialUpdateTicketVote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ticket-votes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TicketVoteDTOToJSON(requestParameters['ticketVoteDTO']),
        };
    }

    /**
     */
    async partialUpdateTicketVoteRaw(requestParameters: PartialUpdateTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketVoteDTO>> {
        const requestOptions = await this.partialUpdateTicketVoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketVoteDTOFromJSON(jsonValue));
    }

    /**
     */
    async partialUpdateTicketVote(requestParameters: PartialUpdateTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketVoteDTO> {
        const response = await this.partialUpdateTicketVoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTicketVote without sending the request
     */
    async updateTicketVoteRequestOpts(requestParameters: UpdateTicketVoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTicketVote().'
            );
        }

        if (requestParameters['ticketVoteDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketVoteDTO',
                'Required parameter "ticketVoteDTO" was null or undefined when calling updateTicketVote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ticket-votes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TicketVoteDTOToJSON(requestParameters['ticketVoteDTO']),
        };
    }

    /**
     */
    async updateTicketVoteRaw(requestParameters: UpdateTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketVoteDTO>> {
        const requestOptions = await this.updateTicketVoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketVoteDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateTicketVote(requestParameters: UpdateTicketVoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketVoteDTO> {
        const response = await this.updateTicketVoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CountTicketVotesVoteTypeEqualsEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type CountTicketVotesVoteTypeEqualsEnum = typeof CountTicketVotesVoteTypeEqualsEnum[keyof typeof CountTicketVotesVoteTypeEqualsEnum];
/**
 * @export
 */
export const CountTicketVotesVoteTypeNotEqualsEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type CountTicketVotesVoteTypeNotEqualsEnum = typeof CountTicketVotesVoteTypeNotEqualsEnum[keyof typeof CountTicketVotesVoteTypeNotEqualsEnum];
/**
 * @export
 */
export const CountTicketVotesVoteTypeInEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type CountTicketVotesVoteTypeInEnum = typeof CountTicketVotesVoteTypeInEnum[keyof typeof CountTicketVotesVoteTypeInEnum];
/**
 * @export
 */
export const CountTicketVotesVoteTypeNotInEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type CountTicketVotesVoteTypeNotInEnum = typeof CountTicketVotesVoteTypeNotInEnum[keyof typeof CountTicketVotesVoteTypeNotInEnum];
/**
 * @export
 */
export const GetAllTicketVotesVoteTypeEqualsEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type GetAllTicketVotesVoteTypeEqualsEnum = typeof GetAllTicketVotesVoteTypeEqualsEnum[keyof typeof GetAllTicketVotesVoteTypeEqualsEnum];
/**
 * @export
 */
export const GetAllTicketVotesVoteTypeNotEqualsEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type GetAllTicketVotesVoteTypeNotEqualsEnum = typeof GetAllTicketVotesVoteTypeNotEqualsEnum[keyof typeof GetAllTicketVotesVoteTypeNotEqualsEnum];
/**
 * @export
 */
export const GetAllTicketVotesVoteTypeInEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type GetAllTicketVotesVoteTypeInEnum = typeof GetAllTicketVotesVoteTypeInEnum[keyof typeof GetAllTicketVotesVoteTypeInEnum];
/**
 * @export
 */
export const GetAllTicketVotesVoteTypeNotInEnum = {
    Upvote: 'UPVOTE',
    Downvote: 'DOWNVOTE'
} as const;
export type GetAllTicketVotesVoteTypeNotInEnum = typeof GetAllTicketVotesVoteTypeNotInEnum[keyof typeof GetAllTicketVotesVoteTypeNotInEnum];
