/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TicketStatusHistoryDTO,
} from '../models/index';
import {
    TicketStatusHistoryDTOFromJSON,
    TicketStatusHistoryDTOToJSON,
} from '../models/index';

export interface CountTicketStatusHistoriesRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    oldStatusEquals?: CountTicketStatusHistoriesOldStatusEqualsEnum;
    oldStatusNotEquals?: CountTicketStatusHistoriesOldStatusNotEqualsEnum;
    oldStatusSpecified?: boolean;
    oldStatusIn?: Array<CountTicketStatusHistoriesOldStatusInEnum>;
    oldStatusNotIn?: Array<CountTicketStatusHistoriesOldStatusNotInEnum>;
    newStatusEquals?: CountTicketStatusHistoriesNewStatusEqualsEnum;
    newStatusNotEquals?: CountTicketStatusHistoriesNewStatusNotEqualsEnum;
    newStatusSpecified?: boolean;
    newStatusIn?: Array<CountTicketStatusHistoriesNewStatusInEnum>;
    newStatusNotIn?: Array<CountTicketStatusHistoriesNewStatusNotInEnum>;
    changedDateGreaterThan?: Date;
    changedDateLessThan?: Date;
    changedDateGreaterThanOrEqual?: Date;
    changedDateLessThanOrEqual?: Date;
    changedDateEquals?: Date;
    changedDateNotEquals?: Date;
    changedDateSpecified?: boolean;
    changedDateIn?: Array<Date>;
    changedDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    changedByIdGreaterThan?: number;
    changedByIdLessThan?: number;
    changedByIdGreaterThanOrEqual?: number;
    changedByIdLessThanOrEqual?: number;
    changedByIdEquals?: number;
    changedByIdNotEquals?: number;
    changedByIdSpecified?: boolean;
    changedByIdIn?: Array<number>;
    changedByIdNotIn?: Array<number>;
    distinct?: boolean;
}

export interface CreateTicketStatusHistoryRequest {
    ticketStatusHistoryDTO: TicketStatusHistoryDTO;
}

export interface DeleteTicketStatusHistoryRequest {
    id: number;
}

export interface GetAllTicketStatusHistoriesRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    oldStatusEquals?: GetAllTicketStatusHistoriesOldStatusEqualsEnum;
    oldStatusNotEquals?: GetAllTicketStatusHistoriesOldStatusNotEqualsEnum;
    oldStatusSpecified?: boolean;
    oldStatusIn?: Array<GetAllTicketStatusHistoriesOldStatusInEnum>;
    oldStatusNotIn?: Array<GetAllTicketStatusHistoriesOldStatusNotInEnum>;
    newStatusEquals?: GetAllTicketStatusHistoriesNewStatusEqualsEnum;
    newStatusNotEquals?: GetAllTicketStatusHistoriesNewStatusNotEqualsEnum;
    newStatusSpecified?: boolean;
    newStatusIn?: Array<GetAllTicketStatusHistoriesNewStatusInEnum>;
    newStatusNotIn?: Array<GetAllTicketStatusHistoriesNewStatusNotInEnum>;
    changedDateGreaterThan?: Date;
    changedDateLessThan?: Date;
    changedDateGreaterThanOrEqual?: Date;
    changedDateLessThanOrEqual?: Date;
    changedDateEquals?: Date;
    changedDateNotEquals?: Date;
    changedDateSpecified?: boolean;
    changedDateIn?: Array<Date>;
    changedDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    changedByIdGreaterThan?: number;
    changedByIdLessThan?: number;
    changedByIdGreaterThanOrEqual?: number;
    changedByIdLessThanOrEqual?: number;
    changedByIdEquals?: number;
    changedByIdNotEquals?: number;
    changedByIdSpecified?: boolean;
    changedByIdIn?: Array<number>;
    changedByIdNotIn?: Array<number>;
    distinct?: boolean;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetTicketStatusHistoryRequest {
    id: number;
}

export interface PartialUpdateTicketStatusHistoryRequest {
    id: number;
    ticketStatusHistoryDTO: TicketStatusHistoryDTO;
}

export interface UpdateTicketStatusHistoryRequest {
    id: number;
    ticketStatusHistoryDTO: TicketStatusHistoryDTO;
}

/**
 * 
 */
export class TicketStatusHistoryResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for countTicketStatusHistories without sending the request
     */
    async countTicketStatusHistoriesRequestOpts(requestParameters: CountTicketStatusHistoriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['oldStatusEquals'] != null) {
            queryParameters['oldStatus.equals'] = requestParameters['oldStatusEquals'];
        }

        if (requestParameters['oldStatusNotEquals'] != null) {
            queryParameters['oldStatus.notEquals'] = requestParameters['oldStatusNotEquals'];
        }

        if (requestParameters['oldStatusSpecified'] != null) {
            queryParameters['oldStatus.specified'] = requestParameters['oldStatusSpecified'];
        }

        if (requestParameters['oldStatusIn'] != null) {
            queryParameters['oldStatus.in'] = requestParameters['oldStatusIn'];
        }

        if (requestParameters['oldStatusNotIn'] != null) {
            queryParameters['oldStatus.notIn'] = requestParameters['oldStatusNotIn'];
        }

        if (requestParameters['newStatusEquals'] != null) {
            queryParameters['newStatus.equals'] = requestParameters['newStatusEquals'];
        }

        if (requestParameters['newStatusNotEquals'] != null) {
            queryParameters['newStatus.notEquals'] = requestParameters['newStatusNotEquals'];
        }

        if (requestParameters['newStatusSpecified'] != null) {
            queryParameters['newStatus.specified'] = requestParameters['newStatusSpecified'];
        }

        if (requestParameters['newStatusIn'] != null) {
            queryParameters['newStatus.in'] = requestParameters['newStatusIn'];
        }

        if (requestParameters['newStatusNotIn'] != null) {
            queryParameters['newStatus.notIn'] = requestParameters['newStatusNotIn'];
        }

        if (requestParameters['changedDateGreaterThan'] != null) {
            queryParameters['changedDate.greaterThan'] = (requestParameters['changedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['changedDateLessThan'] != null) {
            queryParameters['changedDate.lessThan'] = (requestParameters['changedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['changedDateGreaterThanOrEqual'] != null) {
            queryParameters['changedDate.greaterThanOrEqual'] = (requestParameters['changedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['changedDateLessThanOrEqual'] != null) {
            queryParameters['changedDate.lessThanOrEqual'] = (requestParameters['changedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['changedDateEquals'] != null) {
            queryParameters['changedDate.equals'] = (requestParameters['changedDateEquals'] as any).toISOString();
        }

        if (requestParameters['changedDateNotEquals'] != null) {
            queryParameters['changedDate.notEquals'] = (requestParameters['changedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['changedDateSpecified'] != null) {
            queryParameters['changedDate.specified'] = requestParameters['changedDateSpecified'];
        }

        if (requestParameters['changedDateIn'] != null) {
            queryParameters['changedDate.in'] = requestParameters['changedDateIn'];
        }

        if (requestParameters['changedDateNotIn'] != null) {
            queryParameters['changedDate.notIn'] = requestParameters['changedDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['changedByIdGreaterThan'] != null) {
            queryParameters['changedById.greaterThan'] = requestParameters['changedByIdGreaterThan'];
        }

        if (requestParameters['changedByIdLessThan'] != null) {
            queryParameters['changedById.lessThan'] = requestParameters['changedByIdLessThan'];
        }

        if (requestParameters['changedByIdGreaterThanOrEqual'] != null) {
            queryParameters['changedById.greaterThanOrEqual'] = requestParameters['changedByIdGreaterThanOrEqual'];
        }

        if (requestParameters['changedByIdLessThanOrEqual'] != null) {
            queryParameters['changedById.lessThanOrEqual'] = requestParameters['changedByIdLessThanOrEqual'];
        }

        if (requestParameters['changedByIdEquals'] != null) {
            queryParameters['changedById.equals'] = requestParameters['changedByIdEquals'];
        }

        if (requestParameters['changedByIdNotEquals'] != null) {
            queryParameters['changedById.notEquals'] = requestParameters['changedByIdNotEquals'];
        }

        if (requestParameters['changedByIdSpecified'] != null) {
            queryParameters['changedById.specified'] = requestParameters['changedByIdSpecified'];
        }

        if (requestParameters['changedByIdIn'] != null) {
            queryParameters['changedById.in'] = requestParameters['changedByIdIn'];
        }

        if (requestParameters['changedByIdNotIn'] != null) {
            queryParameters['changedById.notIn'] = requestParameters['changedByIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-status-histories/count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async countTicketStatusHistoriesRaw(requestParameters: CountTicketStatusHistoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.countTicketStatusHistoriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async countTicketStatusHistories(requestParameters: CountTicketStatusHistoriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countTicketStatusHistoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTicketStatusHistory without sending the request
     */
    async createTicketStatusHistoryRequestOpts(requestParameters: CreateTicketStatusHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketStatusHistoryDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketStatusHistoryDTO',
                'Required parameter "ticketStatusHistoryDTO" was null or undefined when calling createTicketStatusHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ticket-status-histories`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TicketStatusHistoryDTOToJSON(requestParameters['ticketStatusHistoryDTO']),
        };
    }

    /**
     */
    async createTicketStatusHistoryRaw(requestParameters: CreateTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketStatusHistoryDTO>> {
        const requestOptions = await this.createTicketStatusHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketStatusHistoryDTOFromJSON(jsonValue));
    }

    /**
     */
    async createTicketStatusHistory(requestParameters: CreateTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketStatusHistoryDTO> {
        const response = await this.createTicketStatusHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteTicketStatusHistory without sending the request
     */
    async deleteTicketStatusHistoryRequestOpts(requestParameters: DeleteTicketStatusHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteTicketStatusHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-status-histories/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteTicketStatusHistoryRaw(requestParameters: DeleteTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteTicketStatusHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteTicketStatusHistory(requestParameters: DeleteTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTicketStatusHistoryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllTicketStatusHistories without sending the request
     */
    async getAllTicketStatusHistoriesRequestOpts(requestParameters: GetAllTicketStatusHistoriesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['oldStatusEquals'] != null) {
            queryParameters['oldStatus.equals'] = requestParameters['oldStatusEquals'];
        }

        if (requestParameters['oldStatusNotEquals'] != null) {
            queryParameters['oldStatus.notEquals'] = requestParameters['oldStatusNotEquals'];
        }

        if (requestParameters['oldStatusSpecified'] != null) {
            queryParameters['oldStatus.specified'] = requestParameters['oldStatusSpecified'];
        }

        if (requestParameters['oldStatusIn'] != null) {
            queryParameters['oldStatus.in'] = requestParameters['oldStatusIn'];
        }

        if (requestParameters['oldStatusNotIn'] != null) {
            queryParameters['oldStatus.notIn'] = requestParameters['oldStatusNotIn'];
        }

        if (requestParameters['newStatusEquals'] != null) {
            queryParameters['newStatus.equals'] = requestParameters['newStatusEquals'];
        }

        if (requestParameters['newStatusNotEquals'] != null) {
            queryParameters['newStatus.notEquals'] = requestParameters['newStatusNotEquals'];
        }

        if (requestParameters['newStatusSpecified'] != null) {
            queryParameters['newStatus.specified'] = requestParameters['newStatusSpecified'];
        }

        if (requestParameters['newStatusIn'] != null) {
            queryParameters['newStatus.in'] = requestParameters['newStatusIn'];
        }

        if (requestParameters['newStatusNotIn'] != null) {
            queryParameters['newStatus.notIn'] = requestParameters['newStatusNotIn'];
        }

        if (requestParameters['changedDateGreaterThan'] != null) {
            queryParameters['changedDate.greaterThan'] = (requestParameters['changedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['changedDateLessThan'] != null) {
            queryParameters['changedDate.lessThan'] = (requestParameters['changedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['changedDateGreaterThanOrEqual'] != null) {
            queryParameters['changedDate.greaterThanOrEqual'] = (requestParameters['changedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['changedDateLessThanOrEqual'] != null) {
            queryParameters['changedDate.lessThanOrEqual'] = (requestParameters['changedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['changedDateEquals'] != null) {
            queryParameters['changedDate.equals'] = (requestParameters['changedDateEquals'] as any).toISOString();
        }

        if (requestParameters['changedDateNotEquals'] != null) {
            queryParameters['changedDate.notEquals'] = (requestParameters['changedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['changedDateSpecified'] != null) {
            queryParameters['changedDate.specified'] = requestParameters['changedDateSpecified'];
        }

        if (requestParameters['changedDateIn'] != null) {
            queryParameters['changedDate.in'] = requestParameters['changedDateIn'];
        }

        if (requestParameters['changedDateNotIn'] != null) {
            queryParameters['changedDate.notIn'] = requestParameters['changedDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['changedByIdGreaterThan'] != null) {
            queryParameters['changedById.greaterThan'] = requestParameters['changedByIdGreaterThan'];
        }

        if (requestParameters['changedByIdLessThan'] != null) {
            queryParameters['changedById.lessThan'] = requestParameters['changedByIdLessThan'];
        }

        if (requestParameters['changedByIdGreaterThanOrEqual'] != null) {
            queryParameters['changedById.greaterThanOrEqual'] = requestParameters['changedByIdGreaterThanOrEqual'];
        }

        if (requestParameters['changedByIdLessThanOrEqual'] != null) {
            queryParameters['changedById.lessThanOrEqual'] = requestParameters['changedByIdLessThanOrEqual'];
        }

        if (requestParameters['changedByIdEquals'] != null) {
            queryParameters['changedById.equals'] = requestParameters['changedByIdEquals'];
        }

        if (requestParameters['changedByIdNotEquals'] != null) {
            queryParameters['changedById.notEquals'] = requestParameters['changedByIdNotEquals'];
        }

        if (requestParameters['changedByIdSpecified'] != null) {
            queryParameters['changedById.specified'] = requestParameters['changedByIdSpecified'];
        }

        if (requestParameters['changedByIdIn'] != null) {
            queryParameters['changedById.in'] = requestParameters['changedByIdIn'];
        }

        if (requestParameters['changedByIdNotIn'] != null) {
            queryParameters['changedById.notIn'] = requestParameters['changedByIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-status-histories`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllTicketStatusHistoriesRaw(requestParameters: GetAllTicketStatusHistoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TicketStatusHistoryDTO>>> {
        const requestOptions = await this.getAllTicketStatusHistoriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TicketStatusHistoryDTOFromJSON));
    }

    /**
     */
    async getAllTicketStatusHistories(requestParameters: GetAllTicketStatusHistoriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TicketStatusHistoryDTO>> {
        const response = await this.getAllTicketStatusHistoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTicketStatusHistory without sending the request
     */
    async getTicketStatusHistoryRequestOpts(requestParameters: GetTicketStatusHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getTicketStatusHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ticket-status-histories/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getTicketStatusHistoryRaw(requestParameters: GetTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketStatusHistoryDTO>> {
        const requestOptions = await this.getTicketStatusHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketStatusHistoryDTOFromJSON(jsonValue));
    }

    /**
     */
    async getTicketStatusHistory(requestParameters: GetTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketStatusHistoryDTO> {
        const response = await this.getTicketStatusHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateTicketStatusHistory without sending the request
     */
    async partialUpdateTicketStatusHistoryRequestOpts(requestParameters: PartialUpdateTicketStatusHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdateTicketStatusHistory().'
            );
        }

        if (requestParameters['ticketStatusHistoryDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketStatusHistoryDTO',
                'Required parameter "ticketStatusHistoryDTO" was null or undefined when calling partialUpdateTicketStatusHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ticket-status-histories/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TicketStatusHistoryDTOToJSON(requestParameters['ticketStatusHistoryDTO']),
        };
    }

    /**
     */
    async partialUpdateTicketStatusHistoryRaw(requestParameters: PartialUpdateTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketStatusHistoryDTO>> {
        const requestOptions = await this.partialUpdateTicketStatusHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketStatusHistoryDTOFromJSON(jsonValue));
    }

    /**
     */
    async partialUpdateTicketStatusHistory(requestParameters: PartialUpdateTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketStatusHistoryDTO> {
        const response = await this.partialUpdateTicketStatusHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTicketStatusHistory without sending the request
     */
    async updateTicketStatusHistoryRequestOpts(requestParameters: UpdateTicketStatusHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTicketStatusHistory().'
            );
        }

        if (requestParameters['ticketStatusHistoryDTO'] == null) {
            throw new runtime.RequiredError(
                'ticketStatusHistoryDTO',
                'Required parameter "ticketStatusHistoryDTO" was null or undefined when calling updateTicketStatusHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ticket-status-histories/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TicketStatusHistoryDTOToJSON(requestParameters['ticketStatusHistoryDTO']),
        };
    }

    /**
     */
    async updateTicketStatusHistoryRaw(requestParameters: UpdateTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketStatusHistoryDTO>> {
        const requestOptions = await this.updateTicketStatusHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketStatusHistoryDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateTicketStatusHistory(requestParameters: UpdateTicketStatusHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketStatusHistoryDTO> {
        const response = await this.updateTicketStatusHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CountTicketStatusHistoriesOldStatusEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesOldStatusEqualsEnum = typeof CountTicketStatusHistoriesOldStatusEqualsEnum[keyof typeof CountTicketStatusHistoriesOldStatusEqualsEnum];
/**
 * @export
 */
export const CountTicketStatusHistoriesOldStatusNotEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesOldStatusNotEqualsEnum = typeof CountTicketStatusHistoriesOldStatusNotEqualsEnum[keyof typeof CountTicketStatusHistoriesOldStatusNotEqualsEnum];
/**
 * @export
 */
export const CountTicketStatusHistoriesOldStatusInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesOldStatusInEnum = typeof CountTicketStatusHistoriesOldStatusInEnum[keyof typeof CountTicketStatusHistoriesOldStatusInEnum];
/**
 * @export
 */
export const CountTicketStatusHistoriesOldStatusNotInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesOldStatusNotInEnum = typeof CountTicketStatusHistoriesOldStatusNotInEnum[keyof typeof CountTicketStatusHistoriesOldStatusNotInEnum];
/**
 * @export
 */
export const CountTicketStatusHistoriesNewStatusEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesNewStatusEqualsEnum = typeof CountTicketStatusHistoriesNewStatusEqualsEnum[keyof typeof CountTicketStatusHistoriesNewStatusEqualsEnum];
/**
 * @export
 */
export const CountTicketStatusHistoriesNewStatusNotEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesNewStatusNotEqualsEnum = typeof CountTicketStatusHistoriesNewStatusNotEqualsEnum[keyof typeof CountTicketStatusHistoriesNewStatusNotEqualsEnum];
/**
 * @export
 */
export const CountTicketStatusHistoriesNewStatusInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesNewStatusInEnum = typeof CountTicketStatusHistoriesNewStatusInEnum[keyof typeof CountTicketStatusHistoriesNewStatusInEnum];
/**
 * @export
 */
export const CountTicketStatusHistoriesNewStatusNotInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type CountTicketStatusHistoriesNewStatusNotInEnum = typeof CountTicketStatusHistoriesNewStatusNotInEnum[keyof typeof CountTicketStatusHistoriesNewStatusNotInEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesOldStatusEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesOldStatusEqualsEnum = typeof GetAllTicketStatusHistoriesOldStatusEqualsEnum[keyof typeof GetAllTicketStatusHistoriesOldStatusEqualsEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesOldStatusNotEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesOldStatusNotEqualsEnum = typeof GetAllTicketStatusHistoriesOldStatusNotEqualsEnum[keyof typeof GetAllTicketStatusHistoriesOldStatusNotEqualsEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesOldStatusInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesOldStatusInEnum = typeof GetAllTicketStatusHistoriesOldStatusInEnum[keyof typeof GetAllTicketStatusHistoriesOldStatusInEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesOldStatusNotInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesOldStatusNotInEnum = typeof GetAllTicketStatusHistoriesOldStatusNotInEnum[keyof typeof GetAllTicketStatusHistoriesOldStatusNotInEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesNewStatusEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesNewStatusEqualsEnum = typeof GetAllTicketStatusHistoriesNewStatusEqualsEnum[keyof typeof GetAllTicketStatusHistoriesNewStatusEqualsEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesNewStatusNotEqualsEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesNewStatusNotEqualsEnum = typeof GetAllTicketStatusHistoriesNewStatusNotEqualsEnum[keyof typeof GetAllTicketStatusHistoriesNewStatusNotEqualsEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesNewStatusInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesNewStatusInEnum = typeof GetAllTicketStatusHistoriesNewStatusInEnum[keyof typeof GetAllTicketStatusHistoriesNewStatusInEnum];
/**
 * @export
 */
export const GetAllTicketStatusHistoriesNewStatusNotInEnum = {
    Open: 'OPEN',
    UnderReview: 'UNDER_REVIEW',
    Approved: 'APPROVED',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Resolved: 'RESOLVED',
    Rejected: 'REJECTED',
    Closed: 'CLOSED'
} as const;
export type GetAllTicketStatusHistoriesNewStatusNotInEnum = typeof GetAllTicketStatusHistoriesNewStatusNotInEnum[keyof typeof GetAllTicketStatusHistoriesNewStatusNotInEnum];
