/* tslint:disable */
/* eslint-disable */
/**
 * Spot Fix API
 * Spot Fix API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WorkPlanDTO,
} from '../models/index';
import {
    WorkPlanDTOFromJSON,
    WorkPlanDTOToJSON,
} from '../models/index';

export interface CountWorkPlansRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    estimatedCostGreaterThan?: number;
    estimatedCostLessThan?: number;
    estimatedCostGreaterThanOrEqual?: number;
    estimatedCostLessThanOrEqual?: number;
    estimatedCostEquals?: number;
    estimatedCostNotEquals?: number;
    estimatedCostSpecified?: boolean;
    estimatedCostIn?: Array<number>;
    estimatedCostNotIn?: Array<number>;
    startedDateGreaterThan?: Date;
    startedDateLessThan?: Date;
    startedDateGreaterThanOrEqual?: Date;
    startedDateLessThanOrEqual?: Date;
    startedDateEquals?: Date;
    startedDateNotEquals?: Date;
    startedDateSpecified?: boolean;
    startedDateIn?: Array<Date>;
    startedDateNotIn?: Array<Date>;
    expectedCompletionDateGreaterThan?: Date;
    expectedCompletionDateLessThan?: Date;
    expectedCompletionDateGreaterThanOrEqual?: Date;
    expectedCompletionDateLessThanOrEqual?: Date;
    expectedCompletionDateEquals?: Date;
    expectedCompletionDateNotEquals?: Date;
    expectedCompletionDateSpecified?: boolean;
    expectedCompletionDateIn?: Array<Date>;
    expectedCompletionDateNotIn?: Array<Date>;
    actualCompletionDateGreaterThan?: Date;
    actualCompletionDateLessThan?: Date;
    actualCompletionDateGreaterThanOrEqual?: Date;
    actualCompletionDateLessThanOrEqual?: Date;
    actualCompletionDateEquals?: Date;
    actualCompletionDateNotEquals?: Date;
    actualCompletionDateSpecified?: boolean;
    actualCompletionDateIn?: Array<Date>;
    actualCompletionDateNotIn?: Array<Date>;
    completionPercentageGreaterThan?: number;
    completionPercentageLessThan?: number;
    completionPercentageGreaterThanOrEqual?: number;
    completionPercentageLessThanOrEqual?: number;
    completionPercentageEquals?: number;
    completionPercentageNotEquals?: number;
    completionPercentageSpecified?: boolean;
    completionPercentageIn?: Array<number>;
    completionPercentageNotIn?: Array<number>;
    statusEquals?: CountWorkPlansStatusEqualsEnum;
    statusNotEquals?: CountWorkPlansStatusNotEqualsEnum;
    statusSpecified?: boolean;
    statusIn?: Array<CountWorkPlansStatusInEnum>;
    statusNotIn?: Array<CountWorkPlansStatusNotInEnum>;
    deletedEquals?: boolean;
    deletedNotEquals?: boolean;
    deletedSpecified?: boolean;
    deletedIn?: Array<boolean>;
    deletedNotIn?: Array<boolean>;
    deletedDateGreaterThan?: Date;
    deletedDateLessThan?: Date;
    deletedDateGreaterThanOrEqual?: Date;
    deletedDateLessThanOrEqual?: Date;
    deletedDateEquals?: Date;
    deletedDateNotEquals?: Date;
    deletedDateSpecified?: boolean;
    deletedDateIn?: Array<Date>;
    deletedDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    departmentIdGreaterThan?: number;
    departmentIdLessThan?: number;
    departmentIdGreaterThanOrEqual?: number;
    departmentIdLessThanOrEqual?: number;
    departmentIdEquals?: number;
    departmentIdNotEquals?: number;
    departmentIdSpecified?: boolean;
    departmentIdIn?: Array<number>;
    departmentIdNotIn?: Array<number>;
    distinct?: boolean;
}

export interface CreateWorkPlanRequest {
    workPlanDTO: WorkPlanDTO;
}

export interface DeleteWorkPlanRequest {
    id: number;
}

export interface GetAllWorkPlansRequest {
    idGreaterThan?: number;
    idLessThan?: number;
    idGreaterThanOrEqual?: number;
    idLessThanOrEqual?: number;
    idEquals?: number;
    idNotEquals?: number;
    idSpecified?: boolean;
    idIn?: Array<number>;
    idNotIn?: Array<number>;
    estimatedCostGreaterThan?: number;
    estimatedCostLessThan?: number;
    estimatedCostGreaterThanOrEqual?: number;
    estimatedCostLessThanOrEqual?: number;
    estimatedCostEquals?: number;
    estimatedCostNotEquals?: number;
    estimatedCostSpecified?: boolean;
    estimatedCostIn?: Array<number>;
    estimatedCostNotIn?: Array<number>;
    startedDateGreaterThan?: Date;
    startedDateLessThan?: Date;
    startedDateGreaterThanOrEqual?: Date;
    startedDateLessThanOrEqual?: Date;
    startedDateEquals?: Date;
    startedDateNotEquals?: Date;
    startedDateSpecified?: boolean;
    startedDateIn?: Array<Date>;
    startedDateNotIn?: Array<Date>;
    expectedCompletionDateGreaterThan?: Date;
    expectedCompletionDateLessThan?: Date;
    expectedCompletionDateGreaterThanOrEqual?: Date;
    expectedCompletionDateLessThanOrEqual?: Date;
    expectedCompletionDateEquals?: Date;
    expectedCompletionDateNotEquals?: Date;
    expectedCompletionDateSpecified?: boolean;
    expectedCompletionDateIn?: Array<Date>;
    expectedCompletionDateNotIn?: Array<Date>;
    actualCompletionDateGreaterThan?: Date;
    actualCompletionDateLessThan?: Date;
    actualCompletionDateGreaterThanOrEqual?: Date;
    actualCompletionDateLessThanOrEqual?: Date;
    actualCompletionDateEquals?: Date;
    actualCompletionDateNotEquals?: Date;
    actualCompletionDateSpecified?: boolean;
    actualCompletionDateIn?: Array<Date>;
    actualCompletionDateNotIn?: Array<Date>;
    completionPercentageGreaterThan?: number;
    completionPercentageLessThan?: number;
    completionPercentageGreaterThanOrEqual?: number;
    completionPercentageLessThanOrEqual?: number;
    completionPercentageEquals?: number;
    completionPercentageNotEquals?: number;
    completionPercentageSpecified?: boolean;
    completionPercentageIn?: Array<number>;
    completionPercentageNotIn?: Array<number>;
    statusEquals?: GetAllWorkPlansStatusEqualsEnum;
    statusNotEquals?: GetAllWorkPlansStatusNotEqualsEnum;
    statusSpecified?: boolean;
    statusIn?: Array<GetAllWorkPlansStatusInEnum>;
    statusNotIn?: Array<GetAllWorkPlansStatusNotInEnum>;
    deletedEquals?: boolean;
    deletedNotEquals?: boolean;
    deletedSpecified?: boolean;
    deletedIn?: Array<boolean>;
    deletedNotIn?: Array<boolean>;
    deletedDateGreaterThan?: Date;
    deletedDateLessThan?: Date;
    deletedDateGreaterThanOrEqual?: Date;
    deletedDateLessThanOrEqual?: Date;
    deletedDateEquals?: Date;
    deletedDateNotEquals?: Date;
    deletedDateSpecified?: boolean;
    deletedDateIn?: Array<Date>;
    deletedDateNotIn?: Array<Date>;
    ticketIdGreaterThan?: number;
    ticketIdLessThan?: number;
    ticketIdGreaterThanOrEqual?: number;
    ticketIdLessThanOrEqual?: number;
    ticketIdEquals?: number;
    ticketIdNotEquals?: number;
    ticketIdSpecified?: boolean;
    ticketIdIn?: Array<number>;
    ticketIdNotIn?: Array<number>;
    departmentIdGreaterThan?: number;
    departmentIdLessThan?: number;
    departmentIdGreaterThanOrEqual?: number;
    departmentIdLessThanOrEqual?: number;
    departmentIdEquals?: number;
    departmentIdNotEquals?: number;
    departmentIdSpecified?: boolean;
    departmentIdIn?: Array<number>;
    departmentIdNotIn?: Array<number>;
    distinct?: boolean;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetWorkPlanRequest {
    id: number;
}

export interface PartialUpdateWorkPlanRequest {
    id: number;
    workPlanDTO: WorkPlanDTO;
}

export interface UpdateWorkPlanRequest {
    id: number;
    workPlanDTO: WorkPlanDTO;
}

/**
 * 
 */
export class WorkPlanResourceApi extends runtime.BaseAPI {

    /**
     * Creates request options for countWorkPlans without sending the request
     */
    async countWorkPlansRequestOpts(requestParameters: CountWorkPlansRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['estimatedCostGreaterThan'] != null) {
            queryParameters['estimatedCost.greaterThan'] = requestParameters['estimatedCostGreaterThan'];
        }

        if (requestParameters['estimatedCostLessThan'] != null) {
            queryParameters['estimatedCost.lessThan'] = requestParameters['estimatedCostLessThan'];
        }

        if (requestParameters['estimatedCostGreaterThanOrEqual'] != null) {
            queryParameters['estimatedCost.greaterThanOrEqual'] = requestParameters['estimatedCostGreaterThanOrEqual'];
        }

        if (requestParameters['estimatedCostLessThanOrEqual'] != null) {
            queryParameters['estimatedCost.lessThanOrEqual'] = requestParameters['estimatedCostLessThanOrEqual'];
        }

        if (requestParameters['estimatedCostEquals'] != null) {
            queryParameters['estimatedCost.equals'] = requestParameters['estimatedCostEquals'];
        }

        if (requestParameters['estimatedCostNotEquals'] != null) {
            queryParameters['estimatedCost.notEquals'] = requestParameters['estimatedCostNotEquals'];
        }

        if (requestParameters['estimatedCostSpecified'] != null) {
            queryParameters['estimatedCost.specified'] = requestParameters['estimatedCostSpecified'];
        }

        if (requestParameters['estimatedCostIn'] != null) {
            queryParameters['estimatedCost.in'] = requestParameters['estimatedCostIn'];
        }

        if (requestParameters['estimatedCostNotIn'] != null) {
            queryParameters['estimatedCost.notIn'] = requestParameters['estimatedCostNotIn'];
        }

        if (requestParameters['startedDateGreaterThan'] != null) {
            queryParameters['startedDate.greaterThan'] = (requestParameters['startedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['startedDateLessThan'] != null) {
            queryParameters['startedDate.lessThan'] = (requestParameters['startedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['startedDateGreaterThanOrEqual'] != null) {
            queryParameters['startedDate.greaterThanOrEqual'] = (requestParameters['startedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['startedDateLessThanOrEqual'] != null) {
            queryParameters['startedDate.lessThanOrEqual'] = (requestParameters['startedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['startedDateEquals'] != null) {
            queryParameters['startedDate.equals'] = (requestParameters['startedDateEquals'] as any).toISOString();
        }

        if (requestParameters['startedDateNotEquals'] != null) {
            queryParameters['startedDate.notEquals'] = (requestParameters['startedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['startedDateSpecified'] != null) {
            queryParameters['startedDate.specified'] = requestParameters['startedDateSpecified'];
        }

        if (requestParameters['startedDateIn'] != null) {
            queryParameters['startedDate.in'] = requestParameters['startedDateIn'];
        }

        if (requestParameters['startedDateNotIn'] != null) {
            queryParameters['startedDate.notIn'] = requestParameters['startedDateNotIn'];
        }

        if (requestParameters['expectedCompletionDateGreaterThan'] != null) {
            queryParameters['expectedCompletionDate.greaterThan'] = (requestParameters['expectedCompletionDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateLessThan'] != null) {
            queryParameters['expectedCompletionDate.lessThan'] = (requestParameters['expectedCompletionDateLessThan'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateGreaterThanOrEqual'] != null) {
            queryParameters['expectedCompletionDate.greaterThanOrEqual'] = (requestParameters['expectedCompletionDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateLessThanOrEqual'] != null) {
            queryParameters['expectedCompletionDate.lessThanOrEqual'] = (requestParameters['expectedCompletionDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateEquals'] != null) {
            queryParameters['expectedCompletionDate.equals'] = (requestParameters['expectedCompletionDateEquals'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateNotEquals'] != null) {
            queryParameters['expectedCompletionDate.notEquals'] = (requestParameters['expectedCompletionDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateSpecified'] != null) {
            queryParameters['expectedCompletionDate.specified'] = requestParameters['expectedCompletionDateSpecified'];
        }

        if (requestParameters['expectedCompletionDateIn'] != null) {
            queryParameters['expectedCompletionDate.in'] = requestParameters['expectedCompletionDateIn'];
        }

        if (requestParameters['expectedCompletionDateNotIn'] != null) {
            queryParameters['expectedCompletionDate.notIn'] = requestParameters['expectedCompletionDateNotIn'];
        }

        if (requestParameters['actualCompletionDateGreaterThan'] != null) {
            queryParameters['actualCompletionDate.greaterThan'] = (requestParameters['actualCompletionDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateLessThan'] != null) {
            queryParameters['actualCompletionDate.lessThan'] = (requestParameters['actualCompletionDateLessThan'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateGreaterThanOrEqual'] != null) {
            queryParameters['actualCompletionDate.greaterThanOrEqual'] = (requestParameters['actualCompletionDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateLessThanOrEqual'] != null) {
            queryParameters['actualCompletionDate.lessThanOrEqual'] = (requestParameters['actualCompletionDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateEquals'] != null) {
            queryParameters['actualCompletionDate.equals'] = (requestParameters['actualCompletionDateEquals'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateNotEquals'] != null) {
            queryParameters['actualCompletionDate.notEquals'] = (requestParameters['actualCompletionDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateSpecified'] != null) {
            queryParameters['actualCompletionDate.specified'] = requestParameters['actualCompletionDateSpecified'];
        }

        if (requestParameters['actualCompletionDateIn'] != null) {
            queryParameters['actualCompletionDate.in'] = requestParameters['actualCompletionDateIn'];
        }

        if (requestParameters['actualCompletionDateNotIn'] != null) {
            queryParameters['actualCompletionDate.notIn'] = requestParameters['actualCompletionDateNotIn'];
        }

        if (requestParameters['completionPercentageGreaterThan'] != null) {
            queryParameters['completionPercentage.greaterThan'] = requestParameters['completionPercentageGreaterThan'];
        }

        if (requestParameters['completionPercentageLessThan'] != null) {
            queryParameters['completionPercentage.lessThan'] = requestParameters['completionPercentageLessThan'];
        }

        if (requestParameters['completionPercentageGreaterThanOrEqual'] != null) {
            queryParameters['completionPercentage.greaterThanOrEqual'] = requestParameters['completionPercentageGreaterThanOrEqual'];
        }

        if (requestParameters['completionPercentageLessThanOrEqual'] != null) {
            queryParameters['completionPercentage.lessThanOrEqual'] = requestParameters['completionPercentageLessThanOrEqual'];
        }

        if (requestParameters['completionPercentageEquals'] != null) {
            queryParameters['completionPercentage.equals'] = requestParameters['completionPercentageEquals'];
        }

        if (requestParameters['completionPercentageNotEquals'] != null) {
            queryParameters['completionPercentage.notEquals'] = requestParameters['completionPercentageNotEquals'];
        }

        if (requestParameters['completionPercentageSpecified'] != null) {
            queryParameters['completionPercentage.specified'] = requestParameters['completionPercentageSpecified'];
        }

        if (requestParameters['completionPercentageIn'] != null) {
            queryParameters['completionPercentage.in'] = requestParameters['completionPercentageIn'];
        }

        if (requestParameters['completionPercentageNotIn'] != null) {
            queryParameters['completionPercentage.notIn'] = requestParameters['completionPercentageNotIn'];
        }

        if (requestParameters['statusEquals'] != null) {
            queryParameters['status.equals'] = requestParameters['statusEquals'];
        }

        if (requestParameters['statusNotEquals'] != null) {
            queryParameters['status.notEquals'] = requestParameters['statusNotEquals'];
        }

        if (requestParameters['statusSpecified'] != null) {
            queryParameters['status.specified'] = requestParameters['statusSpecified'];
        }

        if (requestParameters['statusIn'] != null) {
            queryParameters['status.in'] = requestParameters['statusIn'];
        }

        if (requestParameters['statusNotIn'] != null) {
            queryParameters['status.notIn'] = requestParameters['statusNotIn'];
        }

        if (requestParameters['deletedEquals'] != null) {
            queryParameters['deleted.equals'] = requestParameters['deletedEquals'];
        }

        if (requestParameters['deletedNotEquals'] != null) {
            queryParameters['deleted.notEquals'] = requestParameters['deletedNotEquals'];
        }

        if (requestParameters['deletedSpecified'] != null) {
            queryParameters['deleted.specified'] = requestParameters['deletedSpecified'];
        }

        if (requestParameters['deletedIn'] != null) {
            queryParameters['deleted.in'] = requestParameters['deletedIn'];
        }

        if (requestParameters['deletedNotIn'] != null) {
            queryParameters['deleted.notIn'] = requestParameters['deletedNotIn'];
        }

        if (requestParameters['deletedDateGreaterThan'] != null) {
            queryParameters['deletedDate.greaterThan'] = (requestParameters['deletedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThan'] != null) {
            queryParameters['deletedDate.lessThan'] = (requestParameters['deletedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateGreaterThanOrEqual'] != null) {
            queryParameters['deletedDate.greaterThanOrEqual'] = (requestParameters['deletedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThanOrEqual'] != null) {
            queryParameters['deletedDate.lessThanOrEqual'] = (requestParameters['deletedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateEquals'] != null) {
            queryParameters['deletedDate.equals'] = (requestParameters['deletedDateEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateNotEquals'] != null) {
            queryParameters['deletedDate.notEquals'] = (requestParameters['deletedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateSpecified'] != null) {
            queryParameters['deletedDate.specified'] = requestParameters['deletedDateSpecified'];
        }

        if (requestParameters['deletedDateIn'] != null) {
            queryParameters['deletedDate.in'] = requestParameters['deletedDateIn'];
        }

        if (requestParameters['deletedDateNotIn'] != null) {
            queryParameters['deletedDate.notIn'] = requestParameters['deletedDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['departmentIdGreaterThan'] != null) {
            queryParameters['departmentId.greaterThan'] = requestParameters['departmentIdGreaterThan'];
        }

        if (requestParameters['departmentIdLessThan'] != null) {
            queryParameters['departmentId.lessThan'] = requestParameters['departmentIdLessThan'];
        }

        if (requestParameters['departmentIdGreaterThanOrEqual'] != null) {
            queryParameters['departmentId.greaterThanOrEqual'] = requestParameters['departmentIdGreaterThanOrEqual'];
        }

        if (requestParameters['departmentIdLessThanOrEqual'] != null) {
            queryParameters['departmentId.lessThanOrEqual'] = requestParameters['departmentIdLessThanOrEqual'];
        }

        if (requestParameters['departmentIdEquals'] != null) {
            queryParameters['departmentId.equals'] = requestParameters['departmentIdEquals'];
        }

        if (requestParameters['departmentIdNotEquals'] != null) {
            queryParameters['departmentId.notEquals'] = requestParameters['departmentIdNotEquals'];
        }

        if (requestParameters['departmentIdSpecified'] != null) {
            queryParameters['departmentId.specified'] = requestParameters['departmentIdSpecified'];
        }

        if (requestParameters['departmentIdIn'] != null) {
            queryParameters['departmentId.in'] = requestParameters['departmentIdIn'];
        }

        if (requestParameters['departmentIdNotIn'] != null) {
            queryParameters['departmentId.notIn'] = requestParameters['departmentIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/work-plans/count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async countWorkPlansRaw(requestParameters: CountWorkPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.countWorkPlansRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async countWorkPlans(requestParameters: CountWorkPlansRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countWorkPlansRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createWorkPlan without sending the request
     */
    async createWorkPlanRequestOpts(requestParameters: CreateWorkPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workPlanDTO'] == null) {
            throw new runtime.RequiredError(
                'workPlanDTO',
                'Required parameter "workPlanDTO" was null or undefined when calling createWorkPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/work-plans`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkPlanDTOToJSON(requestParameters['workPlanDTO']),
        };
    }

    /**
     */
    async createWorkPlanRaw(requestParameters: CreateWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkPlanDTO>> {
        const requestOptions = await this.createWorkPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkPlanDTOFromJSON(jsonValue));
    }

    /**
     */
    async createWorkPlan(requestParameters: CreateWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkPlanDTO> {
        const response = await this.createWorkPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWorkPlan without sending the request
     */
    async deleteWorkPlanRequestOpts(requestParameters: DeleteWorkPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWorkPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/work-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteWorkPlanRaw(requestParameters: DeleteWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteWorkPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteWorkPlan(requestParameters: DeleteWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkPlanRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllWorkPlans without sending the request
     */
    async getAllWorkPlansRequestOpts(requestParameters: GetAllWorkPlansRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['idGreaterThan'] != null) {
            queryParameters['id.greaterThan'] = requestParameters['idGreaterThan'];
        }

        if (requestParameters['idLessThan'] != null) {
            queryParameters['id.lessThan'] = requestParameters['idLessThan'];
        }

        if (requestParameters['idGreaterThanOrEqual'] != null) {
            queryParameters['id.greaterThanOrEqual'] = requestParameters['idGreaterThanOrEqual'];
        }

        if (requestParameters['idLessThanOrEqual'] != null) {
            queryParameters['id.lessThanOrEqual'] = requestParameters['idLessThanOrEqual'];
        }

        if (requestParameters['idEquals'] != null) {
            queryParameters['id.equals'] = requestParameters['idEquals'];
        }

        if (requestParameters['idNotEquals'] != null) {
            queryParameters['id.notEquals'] = requestParameters['idNotEquals'];
        }

        if (requestParameters['idSpecified'] != null) {
            queryParameters['id.specified'] = requestParameters['idSpecified'];
        }

        if (requestParameters['idIn'] != null) {
            queryParameters['id.in'] = requestParameters['idIn'];
        }

        if (requestParameters['idNotIn'] != null) {
            queryParameters['id.notIn'] = requestParameters['idNotIn'];
        }

        if (requestParameters['estimatedCostGreaterThan'] != null) {
            queryParameters['estimatedCost.greaterThan'] = requestParameters['estimatedCostGreaterThan'];
        }

        if (requestParameters['estimatedCostLessThan'] != null) {
            queryParameters['estimatedCost.lessThan'] = requestParameters['estimatedCostLessThan'];
        }

        if (requestParameters['estimatedCostGreaterThanOrEqual'] != null) {
            queryParameters['estimatedCost.greaterThanOrEqual'] = requestParameters['estimatedCostGreaterThanOrEqual'];
        }

        if (requestParameters['estimatedCostLessThanOrEqual'] != null) {
            queryParameters['estimatedCost.lessThanOrEqual'] = requestParameters['estimatedCostLessThanOrEqual'];
        }

        if (requestParameters['estimatedCostEquals'] != null) {
            queryParameters['estimatedCost.equals'] = requestParameters['estimatedCostEquals'];
        }

        if (requestParameters['estimatedCostNotEquals'] != null) {
            queryParameters['estimatedCost.notEquals'] = requestParameters['estimatedCostNotEquals'];
        }

        if (requestParameters['estimatedCostSpecified'] != null) {
            queryParameters['estimatedCost.specified'] = requestParameters['estimatedCostSpecified'];
        }

        if (requestParameters['estimatedCostIn'] != null) {
            queryParameters['estimatedCost.in'] = requestParameters['estimatedCostIn'];
        }

        if (requestParameters['estimatedCostNotIn'] != null) {
            queryParameters['estimatedCost.notIn'] = requestParameters['estimatedCostNotIn'];
        }

        if (requestParameters['startedDateGreaterThan'] != null) {
            queryParameters['startedDate.greaterThan'] = (requestParameters['startedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['startedDateLessThan'] != null) {
            queryParameters['startedDate.lessThan'] = (requestParameters['startedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['startedDateGreaterThanOrEqual'] != null) {
            queryParameters['startedDate.greaterThanOrEqual'] = (requestParameters['startedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['startedDateLessThanOrEqual'] != null) {
            queryParameters['startedDate.lessThanOrEqual'] = (requestParameters['startedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['startedDateEquals'] != null) {
            queryParameters['startedDate.equals'] = (requestParameters['startedDateEquals'] as any).toISOString();
        }

        if (requestParameters['startedDateNotEquals'] != null) {
            queryParameters['startedDate.notEquals'] = (requestParameters['startedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['startedDateSpecified'] != null) {
            queryParameters['startedDate.specified'] = requestParameters['startedDateSpecified'];
        }

        if (requestParameters['startedDateIn'] != null) {
            queryParameters['startedDate.in'] = requestParameters['startedDateIn'];
        }

        if (requestParameters['startedDateNotIn'] != null) {
            queryParameters['startedDate.notIn'] = requestParameters['startedDateNotIn'];
        }

        if (requestParameters['expectedCompletionDateGreaterThan'] != null) {
            queryParameters['expectedCompletionDate.greaterThan'] = (requestParameters['expectedCompletionDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateLessThan'] != null) {
            queryParameters['expectedCompletionDate.lessThan'] = (requestParameters['expectedCompletionDateLessThan'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateGreaterThanOrEqual'] != null) {
            queryParameters['expectedCompletionDate.greaterThanOrEqual'] = (requestParameters['expectedCompletionDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateLessThanOrEqual'] != null) {
            queryParameters['expectedCompletionDate.lessThanOrEqual'] = (requestParameters['expectedCompletionDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateEquals'] != null) {
            queryParameters['expectedCompletionDate.equals'] = (requestParameters['expectedCompletionDateEquals'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateNotEquals'] != null) {
            queryParameters['expectedCompletionDate.notEquals'] = (requestParameters['expectedCompletionDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['expectedCompletionDateSpecified'] != null) {
            queryParameters['expectedCompletionDate.specified'] = requestParameters['expectedCompletionDateSpecified'];
        }

        if (requestParameters['expectedCompletionDateIn'] != null) {
            queryParameters['expectedCompletionDate.in'] = requestParameters['expectedCompletionDateIn'];
        }

        if (requestParameters['expectedCompletionDateNotIn'] != null) {
            queryParameters['expectedCompletionDate.notIn'] = requestParameters['expectedCompletionDateNotIn'];
        }

        if (requestParameters['actualCompletionDateGreaterThan'] != null) {
            queryParameters['actualCompletionDate.greaterThan'] = (requestParameters['actualCompletionDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateLessThan'] != null) {
            queryParameters['actualCompletionDate.lessThan'] = (requestParameters['actualCompletionDateLessThan'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateGreaterThanOrEqual'] != null) {
            queryParameters['actualCompletionDate.greaterThanOrEqual'] = (requestParameters['actualCompletionDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateLessThanOrEqual'] != null) {
            queryParameters['actualCompletionDate.lessThanOrEqual'] = (requestParameters['actualCompletionDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateEquals'] != null) {
            queryParameters['actualCompletionDate.equals'] = (requestParameters['actualCompletionDateEquals'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateNotEquals'] != null) {
            queryParameters['actualCompletionDate.notEquals'] = (requestParameters['actualCompletionDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['actualCompletionDateSpecified'] != null) {
            queryParameters['actualCompletionDate.specified'] = requestParameters['actualCompletionDateSpecified'];
        }

        if (requestParameters['actualCompletionDateIn'] != null) {
            queryParameters['actualCompletionDate.in'] = requestParameters['actualCompletionDateIn'];
        }

        if (requestParameters['actualCompletionDateNotIn'] != null) {
            queryParameters['actualCompletionDate.notIn'] = requestParameters['actualCompletionDateNotIn'];
        }

        if (requestParameters['completionPercentageGreaterThan'] != null) {
            queryParameters['completionPercentage.greaterThan'] = requestParameters['completionPercentageGreaterThan'];
        }

        if (requestParameters['completionPercentageLessThan'] != null) {
            queryParameters['completionPercentage.lessThan'] = requestParameters['completionPercentageLessThan'];
        }

        if (requestParameters['completionPercentageGreaterThanOrEqual'] != null) {
            queryParameters['completionPercentage.greaterThanOrEqual'] = requestParameters['completionPercentageGreaterThanOrEqual'];
        }

        if (requestParameters['completionPercentageLessThanOrEqual'] != null) {
            queryParameters['completionPercentage.lessThanOrEqual'] = requestParameters['completionPercentageLessThanOrEqual'];
        }

        if (requestParameters['completionPercentageEquals'] != null) {
            queryParameters['completionPercentage.equals'] = requestParameters['completionPercentageEquals'];
        }

        if (requestParameters['completionPercentageNotEquals'] != null) {
            queryParameters['completionPercentage.notEquals'] = requestParameters['completionPercentageNotEquals'];
        }

        if (requestParameters['completionPercentageSpecified'] != null) {
            queryParameters['completionPercentage.specified'] = requestParameters['completionPercentageSpecified'];
        }

        if (requestParameters['completionPercentageIn'] != null) {
            queryParameters['completionPercentage.in'] = requestParameters['completionPercentageIn'];
        }

        if (requestParameters['completionPercentageNotIn'] != null) {
            queryParameters['completionPercentage.notIn'] = requestParameters['completionPercentageNotIn'];
        }

        if (requestParameters['statusEquals'] != null) {
            queryParameters['status.equals'] = requestParameters['statusEquals'];
        }

        if (requestParameters['statusNotEquals'] != null) {
            queryParameters['status.notEquals'] = requestParameters['statusNotEquals'];
        }

        if (requestParameters['statusSpecified'] != null) {
            queryParameters['status.specified'] = requestParameters['statusSpecified'];
        }

        if (requestParameters['statusIn'] != null) {
            queryParameters['status.in'] = requestParameters['statusIn'];
        }

        if (requestParameters['statusNotIn'] != null) {
            queryParameters['status.notIn'] = requestParameters['statusNotIn'];
        }

        if (requestParameters['deletedEquals'] != null) {
            queryParameters['deleted.equals'] = requestParameters['deletedEquals'];
        }

        if (requestParameters['deletedNotEquals'] != null) {
            queryParameters['deleted.notEquals'] = requestParameters['deletedNotEquals'];
        }

        if (requestParameters['deletedSpecified'] != null) {
            queryParameters['deleted.specified'] = requestParameters['deletedSpecified'];
        }

        if (requestParameters['deletedIn'] != null) {
            queryParameters['deleted.in'] = requestParameters['deletedIn'];
        }

        if (requestParameters['deletedNotIn'] != null) {
            queryParameters['deleted.notIn'] = requestParameters['deletedNotIn'];
        }

        if (requestParameters['deletedDateGreaterThan'] != null) {
            queryParameters['deletedDate.greaterThan'] = (requestParameters['deletedDateGreaterThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThan'] != null) {
            queryParameters['deletedDate.lessThan'] = (requestParameters['deletedDateLessThan'] as any).toISOString();
        }

        if (requestParameters['deletedDateGreaterThanOrEqual'] != null) {
            queryParameters['deletedDate.greaterThanOrEqual'] = (requestParameters['deletedDateGreaterThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateLessThanOrEqual'] != null) {
            queryParameters['deletedDate.lessThanOrEqual'] = (requestParameters['deletedDateLessThanOrEqual'] as any).toISOString();
        }

        if (requestParameters['deletedDateEquals'] != null) {
            queryParameters['deletedDate.equals'] = (requestParameters['deletedDateEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateNotEquals'] != null) {
            queryParameters['deletedDate.notEquals'] = (requestParameters['deletedDateNotEquals'] as any).toISOString();
        }

        if (requestParameters['deletedDateSpecified'] != null) {
            queryParameters['deletedDate.specified'] = requestParameters['deletedDateSpecified'];
        }

        if (requestParameters['deletedDateIn'] != null) {
            queryParameters['deletedDate.in'] = requestParameters['deletedDateIn'];
        }

        if (requestParameters['deletedDateNotIn'] != null) {
            queryParameters['deletedDate.notIn'] = requestParameters['deletedDateNotIn'];
        }

        if (requestParameters['ticketIdGreaterThan'] != null) {
            queryParameters['ticketId.greaterThan'] = requestParameters['ticketIdGreaterThan'];
        }

        if (requestParameters['ticketIdLessThan'] != null) {
            queryParameters['ticketId.lessThan'] = requestParameters['ticketIdLessThan'];
        }

        if (requestParameters['ticketIdGreaterThanOrEqual'] != null) {
            queryParameters['ticketId.greaterThanOrEqual'] = requestParameters['ticketIdGreaterThanOrEqual'];
        }

        if (requestParameters['ticketIdLessThanOrEqual'] != null) {
            queryParameters['ticketId.lessThanOrEqual'] = requestParameters['ticketIdLessThanOrEqual'];
        }

        if (requestParameters['ticketIdEquals'] != null) {
            queryParameters['ticketId.equals'] = requestParameters['ticketIdEquals'];
        }

        if (requestParameters['ticketIdNotEquals'] != null) {
            queryParameters['ticketId.notEquals'] = requestParameters['ticketIdNotEquals'];
        }

        if (requestParameters['ticketIdSpecified'] != null) {
            queryParameters['ticketId.specified'] = requestParameters['ticketIdSpecified'];
        }

        if (requestParameters['ticketIdIn'] != null) {
            queryParameters['ticketId.in'] = requestParameters['ticketIdIn'];
        }

        if (requestParameters['ticketIdNotIn'] != null) {
            queryParameters['ticketId.notIn'] = requestParameters['ticketIdNotIn'];
        }

        if (requestParameters['departmentIdGreaterThan'] != null) {
            queryParameters['departmentId.greaterThan'] = requestParameters['departmentIdGreaterThan'];
        }

        if (requestParameters['departmentIdLessThan'] != null) {
            queryParameters['departmentId.lessThan'] = requestParameters['departmentIdLessThan'];
        }

        if (requestParameters['departmentIdGreaterThanOrEqual'] != null) {
            queryParameters['departmentId.greaterThanOrEqual'] = requestParameters['departmentIdGreaterThanOrEqual'];
        }

        if (requestParameters['departmentIdLessThanOrEqual'] != null) {
            queryParameters['departmentId.lessThanOrEqual'] = requestParameters['departmentIdLessThanOrEqual'];
        }

        if (requestParameters['departmentIdEquals'] != null) {
            queryParameters['departmentId.equals'] = requestParameters['departmentIdEquals'];
        }

        if (requestParameters['departmentIdNotEquals'] != null) {
            queryParameters['departmentId.notEquals'] = requestParameters['departmentIdNotEquals'];
        }

        if (requestParameters['departmentIdSpecified'] != null) {
            queryParameters['departmentId.specified'] = requestParameters['departmentIdSpecified'];
        }

        if (requestParameters['departmentIdIn'] != null) {
            queryParameters['departmentId.in'] = requestParameters['departmentIdIn'];
        }

        if (requestParameters['departmentIdNotIn'] != null) {
            queryParameters['departmentId.notIn'] = requestParameters['departmentIdNotIn'];
        }

        if (requestParameters['distinct'] != null) {
            queryParameters['distinct'] = requestParameters['distinct'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/work-plans`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAllWorkPlansRaw(requestParameters: GetAllWorkPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkPlanDTO>>> {
        const requestOptions = await this.getAllWorkPlansRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkPlanDTOFromJSON));
    }

    /**
     */
    async getAllWorkPlans(requestParameters: GetAllWorkPlansRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkPlanDTO>> {
        const response = await this.getAllWorkPlansRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWorkPlan without sending the request
     */
    async getWorkPlanRequestOpts(requestParameters: GetWorkPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/work-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getWorkPlanRaw(requestParameters: GetWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkPlanDTO>> {
        const requestOptions = await this.getWorkPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkPlanDTOFromJSON(jsonValue));
    }

    /**
     */
    async getWorkPlan(requestParameters: GetWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkPlanDTO> {
        const response = await this.getWorkPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for partialUpdateWorkPlan without sending the request
     */
    async partialUpdateWorkPlanRequestOpts(requestParameters: PartialUpdateWorkPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling partialUpdateWorkPlan().'
            );
        }

        if (requestParameters['workPlanDTO'] == null) {
            throw new runtime.RequiredError(
                'workPlanDTO',
                'Required parameter "workPlanDTO" was null or undefined when calling partialUpdateWorkPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/work-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WorkPlanDTOToJSON(requestParameters['workPlanDTO']),
        };
    }

    /**
     */
    async partialUpdateWorkPlanRaw(requestParameters: PartialUpdateWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkPlanDTO>> {
        const requestOptions = await this.partialUpdateWorkPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkPlanDTOFromJSON(jsonValue));
    }

    /**
     */
    async partialUpdateWorkPlan(requestParameters: PartialUpdateWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkPlanDTO> {
        const response = await this.partialUpdateWorkPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateWorkPlan without sending the request
     */
    async updateWorkPlanRequestOpts(requestParameters: UpdateWorkPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWorkPlan().'
            );
        }

        if (requestParameters['workPlanDTO'] == null) {
            throw new runtime.RequiredError(
                'workPlanDTO',
                'Required parameter "workPlanDTO" was null or undefined when calling updateWorkPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/work-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WorkPlanDTOToJSON(requestParameters['workPlanDTO']),
        };
    }

    /**
     */
    async updateWorkPlanRaw(requestParameters: UpdateWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkPlanDTO>> {
        const requestOptions = await this.updateWorkPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkPlanDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateWorkPlan(requestParameters: UpdateWorkPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkPlanDTO> {
        const response = await this.updateWorkPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CountWorkPlansStatusEqualsEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type CountWorkPlansStatusEqualsEnum = typeof CountWorkPlansStatusEqualsEnum[keyof typeof CountWorkPlansStatusEqualsEnum];
/**
 * @export
 */
export const CountWorkPlansStatusNotEqualsEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type CountWorkPlansStatusNotEqualsEnum = typeof CountWorkPlansStatusNotEqualsEnum[keyof typeof CountWorkPlansStatusNotEqualsEnum];
/**
 * @export
 */
export const CountWorkPlansStatusInEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type CountWorkPlansStatusInEnum = typeof CountWorkPlansStatusInEnum[keyof typeof CountWorkPlansStatusInEnum];
/**
 * @export
 */
export const CountWorkPlansStatusNotInEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type CountWorkPlansStatusNotInEnum = typeof CountWorkPlansStatusNotInEnum[keyof typeof CountWorkPlansStatusNotInEnum];
/**
 * @export
 */
export const GetAllWorkPlansStatusEqualsEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type GetAllWorkPlansStatusEqualsEnum = typeof GetAllWorkPlansStatusEqualsEnum[keyof typeof GetAllWorkPlansStatusEqualsEnum];
/**
 * @export
 */
export const GetAllWorkPlansStatusNotEqualsEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type GetAllWorkPlansStatusNotEqualsEnum = typeof GetAllWorkPlansStatusNotEqualsEnum[keyof typeof GetAllWorkPlansStatusNotEqualsEnum];
/**
 * @export
 */
export const GetAllWorkPlansStatusInEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type GetAllWorkPlansStatusInEnum = typeof GetAllWorkPlansStatusInEnum[keyof typeof GetAllWorkPlansStatusInEnum];
/**
 * @export
 */
export const GetAllWorkPlansStatusNotInEnum = {
    Planned: 'PLANNED',
    Assigned: 'ASSIGNED',
    Active: 'ACTIVE',
    OnHold: 'ON_HOLD',
    Delayed: 'DELAYED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type GetAllWorkPlansStatusNotInEnum = typeof GetAllWorkPlansStatusNotInEnum[keyof typeof GetAllWorkPlansStatusNotInEnum];
