# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: postgres
    password: root

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2U4M2E0MzM4YWRiYzdmYmQwOWEyODMyOWQ2MmE1NDM0YWZiMTcxYTU0MDJmMjE4MWViNjU0MmRjNjFkNGNlYjBlOWQxODllMjJmMzk0YjdkOGRhMmZjMzA1ZjI1MTYwMWM3MjM0MTdhY2QxZjEzZjRmOGZhMTkzMTQwOTVmZDU=
