package com.diviso.spot_fix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketStatusHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStatusHistoryAllPropertiesEquals(TicketStatusHistory expected, TicketStatusHistory actual) {
        assertTicketStatusHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketStatusHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStatusHistoryAllUpdatablePropertiesEquals(TicketStatusHistory expected, TicketStatusHistory actual) {
        assertTicketStatusHistoryUpdatableFieldsEquals(expected, actual);
        assertTicketStatusHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStatusHistoryAutoGeneratedPropertiesEquals(TicketStatusHistory expected, TicketStatusHistory actual) {
        assertThat(actual)
            .as("Verify TicketStatusHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStatusHistoryUpdatableFieldsEquals(TicketStatusHistory expected, TicketStatusHistory actual) {
        assertThat(actual)
            .as("Verify TicketStatusHistory relevant properties")
            .satisfies(a -> assertThat(a.getOldStatus()).as("check oldStatus").isEqualTo(expected.getOldStatus()))
            .satisfies(a -> assertThat(a.getNewStatus()).as("check newStatus").isEqualTo(expected.getNewStatus()))
            .satisfies(a -> assertThat(a.getChangedDate()).as("check changedDate").isEqualTo(expected.getChangedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketStatusHistoryUpdatableRelationshipsEquals(TicketStatusHistory expected, TicketStatusHistory actual) {
        assertThat(actual)
            .as("Verify TicketStatusHistory relationships")
            .satisfies(a -> assertThat(a.getTicket()).as("check ticket").isEqualTo(expected.getTicket()));
    }
}
