package com.diviso.spot_fix.domain;

import static com.diviso.spot_fix.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class WorkPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkPlanAllPropertiesEquals(WorkPlan expected, WorkPlan actual) {
        assertWorkPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkPlanAllUpdatablePropertiesEquals(WorkPlan expected, WorkPlan actual) {
        assertWorkPlanUpdatableFieldsEquals(expected, actual);
        assertWorkPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkPlanAutoGeneratedPropertiesEquals(WorkPlan expected, WorkPlan actual) {
        assertThat(actual)
            .as("Verify WorkPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkPlanUpdatableFieldsEquals(WorkPlan expected, WorkPlan actual) {
        assertThat(actual)
            .as("Verify WorkPlan relevant properties")
            .satisfies(a ->
                assertThat(a.getEstimatedCost())
                    .as("check estimatedCost")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getEstimatedCost())
            )
            .satisfies(a -> assertThat(a.getStartedDate()).as("check startedDate").isEqualTo(expected.getStartedDate()))
            .satisfies(a ->
                assertThat(a.getExpectedCompletionDate()).as("check expectedCompletionDate").isEqualTo(expected.getExpectedCompletionDate())
            )
            .satisfies(a ->
                assertThat(a.getActualCompletionDate()).as("check actualCompletionDate").isEqualTo(expected.getActualCompletionDate())
            )
            .satisfies(a ->
                assertThat(a.getCompletionPercentage()).as("check completionPercentage").isEqualTo(expected.getCompletionPercentage())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()))
            .satisfies(a -> assertThat(a.getDeleted()).as("check deleted").isEqualTo(expected.getDeleted()))
            .satisfies(a -> assertThat(a.getDeletedDate()).as("check deletedDate").isEqualTo(expected.getDeletedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkPlanUpdatableRelationshipsEquals(WorkPlan expected, WorkPlan actual) {
        assertThat(actual)
            .as("Verify WorkPlan relationships")
            .satisfies(a -> assertThat(a.getTicket()).as("check ticket").isEqualTo(expected.getTicket()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()));
    }
}
